# ADRD hospitalization rates per county

## Limited to NC

```{r, message=F, warning=F}
## The interactive Rstudio session was started with 36 GB and 8 cores
## The  default working directory of an Rmd in Rstudio is the Rmd location
## The details of the symbolic links to the input data are provided in the README of the  /data/input folder

## load packages ----
library(tidyverse)
library(magrittr)
library(fst)
library(data.table)
library(sf)
library(tictoc)
```

### Read num enrollees

```{r}
fips_num_enroll <- read_csv("../data/input/fips_num_enroll.csv") %>% 
  filter(race %in% c("1", "2")) %>% 
  rename(fips = fips5) %>% 
  mutate(fips = as.character(fips))
```

### Read shp files

* read county shp files

```{r}
county_sf <- read_sf("../data/input/scratch/tl_2022_us_county/tl_2022_us_county.shp") %>% 
  rename(fips = GEOID) %>% 
  mutate(fips = as.character(as.numeric(fips)))

dim(county_sf)
names(county_sf)
```

### Read ADRD events

```{r}
adrd_df <- read_rds("../data/intermediate/adrd_df.rds") %>% 
  rename(fips = FIPS) %>% 
  filter(race_cat %in% c("black", "white")) %>% 
  mutate(fips = as.character(fips))
adrd_df$race <- as.character(NA)
adrd_df$race[adrd_df$race_cat == "black"] <- "2"
adrd_df$race[adrd_df$race_cat == "white"] <- "1"
```

### Compute ADRD rates per county-race

* get num_enroll

```{r}
xx <- fips_num_enroll %>% 
  filter(race %in% c(1,2)) %>% 
  group_by(year, fips, race) %>% 
  summarise(count = sum(count)) %>% 
  group_by(fips, race) %>% 
  summarise(
    num_enrollee = mean(count, na.rm = T) 
  ) %>% 
  ungroup()

head(xx)
```

* get adrd count

```{r}
yy <- adrd_df %>% 
  group_by(fips, race) %>% 
  summarize(adrd_count = sum(w)) %>% 
  ungroup()

tapply(yy$adrd_count, yy$race, summary)
```

```{r}
zz <- left_join(xx, yy) %>% 
  mutate(adrd_rate = adrd_count / num_enrollee)

tapply(zz$adrd_rate, zz$race, summary)
```

* Map adrd rates

```{r}
county_sf %>% 
  filter(STATEFP == "37") %>% 
  select(fips) %>% 
  left_join(zz) %>% 
  ggplot() + 
  geom_sf(aes(fill = adrd_rate)) +
  facet_grid(~race)
```

<!-- #  -->
<!-- # # Aggregate by zipcode -->
<!-- # -->
<!-- # # Merge zipcode data -->
<!-- # data(zipcode) -->
<!-- # zipcode$zip <- as.numeric(zipcode$zip) -->
<!-- # adrd_df <- merge(adrd_df, zipcode, -->
<!-- #                              by.x = c("ADRD_zip"), -->
<!-- #                              by.y = c("zip"), all.x = TRUE) -->
<!-- # adrd_df <- adrd_df[!is.na(ADRD_zip)] -->
<!-- #  -->
<!-- # # Aggregate -->
<!-- # ADRD_agg <- adrd_df[sex != 0 & race != 0 & # remove unknown sex/race -->
<!-- #                                   age_grp != "<65" & -->
<!-- #                                   state == "NC", # limit to North Carolina -->
<!-- #                                 .(n_persons = .N,  -->
<!-- #                                   n_ADRDhosp = sum(ADRD_hosp), -->
<!-- #                                   mean_age = mean(ADRD_age, na.rm = TRUE)), -->
<!-- #                                 by = .(exit_fips, # grouping for sums -->
<!-- #                                        age_grp,  -->
<!-- #                                        sexM,  -->
<!-- #                                        race_cat)] -->
<!-- #  -->
<!-- # # Visualize hosp rate -->
<!-- # library(ggplot2) -->
<!-- # ADRD_agg <- droplevels(ADRD_agg) -->
<!-- # ADRD_agg[, sex := ifelse(sexM, "Male", "Female")] -->
<!-- # ggplot(ADRD_agg) + -->
<!-- #   geom_boxplot(aes(x = race_cat, y = n_ADRDhosp/n_persons, fill = race_cat)) + -->
<!-- #   facet_grid(sex ~ age_grp) + -->
<!-- #   theme_bw() + -->
<!-- #   theme(axis.text.x = element_text(angle = 30, hjust = 1), legend.position = "none") + -->
<!-- #   scale_y_continuous(limits = c(0, 1)) + -->
<!-- #   labs(x = "", fill = "", y = "# ADRD Hosp / Medicare Bene.") -->
