
```{r setup, include=FALSE}
## Set working directory as project root
library(here)
knitr::opts_knit$set(root.dir = here())
```

```{r, message=FALSE, warning=FALSE}
## Load libraries ----
library(tidyverse)
library(magrittr)
library(rstan)
```

```{r}
# Load data

# load all models in working model directory
stanfit_list <- lapply(paste0("results/models/working/", 
                            list.files("results/models/working/", pattern = "adrd")), read_rds) 

# name list elements
names(stanfit_list) <- str_remove_all(list.files("results/models/working/", pattern = "adrd"), "stanfit_object_|\\.rds")

# load adrd ratios and county fips data
adrd_ratios_df <- read_rds('data/symlinks/scratch/adrd_ratios_df.rds')
county_fips_df <- read_rds("data/symlinks/scratch/county_fips_df.rds")
```



```{r}
###--- choose model
#model <- "m1"
#model <- "m2"
#model <- "m3"
# model <- "m4"


# #slurm job number 1307317 for m0 is labeled model_run_20230311_185502
# if(model == "m1"){
#   stanfit_object <- read_rds(paste0(
#     #"results/models/adrd/m1/model_run_20231109_142035/stanfit_object.rds"
#     #"results/models/adrd/m1/model_run_20240131_215726/stanfit_object.rds"
#     "results/models/adrd/m1/model_run_20240307/stanfit_object.rds"
#   ))
# } else if(model == "m2"){
#   stanfit_object <- read_rds(paste0(
#     #"results/models/adrd/m2/model_run_20240216_1406/stanfit_object.rds"
#     "results/models/adrd/m2/model_run_20240307/stanfit_object.rds"
#     ))
# } else if(model == "m3"){
#   stanfit_object <- read_rds(paste0(
#     "results/models/adrd/m3/model_run_20240308/stanfit_object.rds"
#     ))
# } else if(model == "m4"){
#   stanfit_object <- read_rds(paste0(
#     "results/models/adrd/m4/model_run_*/stanfit_object.rds"
#     ))
# }
# 
# 
# 
# class(stanfit_object)
```

```{r}
# stanfit_summary <- summary(stanfit_object)
# ## summary stats of fixed effects ----
# 
# 
# if(model == "m1"){
#   stanfit_summary$summary[c('alpha[1]', 'alpha[2]', 'delta'), ]
# }else if(model == "m2" | model == "m3"){
#   stanfit_summary$summary[c('alpha[1]', 'alpha[2]', 'delta', 'beta[1]', 'beta[2]'), ]
# }else if(model == "m4"){
#   stanfit_summary$summary[c('alpha[1]', 'alpha[2]', 'delta',
#                             'beta[1]', 'beta[2]', 'beta[3]', 'beta[4]', 'beta[5]', 'beta[6]'), ]
# }
```

```{r}
## Define functions ----
extract_samples <- function(stanfit) {
    ## Extract samples from a stanfit object and return a list of variables
    ## NOTE: Random effects will be matrices of dimensions iterations x areas
    ##       while the fixed effects will just be columns of length iterations
    
    ## Extract the samples of fixed effects from stan_fit object
    fixed_pars <- stanfit@model_pars[grepl(stanfit@model_pars,
                                           pattern = "alpha|beta|delta|sigma")]
    x <- as.matrix(stanfit, pars = fixed_pars)
    
    ## Get a list of the names and make them prettier
    var_names <-
        gsub(x = colnames(x),
             pattern = "\\[|\\]",
             replacement = "")
    
    ## Turn the named matrix into a list of vectors
    x <- split(x, c(col(x)))
    
    ## Put back in the variable names
    names(x) <- var_names
    
    ## Now extract the random effects and attach the random effects
    random_pars <- stanfit@model_pars[grepl(stanfit@model_pars,
                                            pattern = "nu|psi|phi")]
    r_effs <- as.matrix(stanfit, pars = random_pars)
    x$psi1 <- r_effs[, grep(x = colnames(r_effs),
                            pattern = 'psi[1',
                            fixed = TRUE)]
    x$psi2 <- r_effs[, grep(x = colnames(r_effs),
                            pattern = 'psi[2',
                            fixed = TRUE)]
    x$phi  <- r_effs[, grep(x = colnames(r_effs),
                            pattern = 'phi',
                            fixed = TRUE)]
    x$nu   <- r_effs[, grep(x = colnames(r_effs),
                            pattern = 'nu',
                            fixed = TRUE)]
    
    return(x)
}
```

```{r}
# run function to extract samples
stanfit_samples <- lapply(stanfit_list, extract_samples)

names(stanfit_samples[[1]])
length(stanfit_samples[[1]]$alpha1)
dim(stanfit_samples[[1]]$phi)
dim(stanfit_samples[[1]]$nu)
```

# log relative risk

```{r}
## obtain posterior predictive values ----
## Make a version of nu that is expanded such that every state column
## repeats as many times as their are counties. Then we can just add
## the expanded matrix when calculating posterior quantities.
nu_counts <- county_fips_df %>%
    dplyr::group_by(s_idx) %>%
    dplyr::summarize(count = dplyr::n()) %>%
    dplyr::mutate(c_sum = cumsum(count))

# initialize lists for posterior_white and posterior_black
posterior_white <- list()
posterior_black <- list()
nu_expanded <- list()

# loop through models
for (i in seq_along(stanfit_samples)){

  ## Initialize a holder for each model
  nu_expanded[[i]] <- matrix(NA,
                      nrow = nrow(stanfit_samples[[i]]$psi1),
                      ncol = max(nu_counts$c_sum))
  
  for (s in 1:nrow(nu_counts)) {
    start_ix <- ifelse(length(nu_counts$c_sum[s - 1]) > 0,
                       nu_counts$c_sum[s - 1], 0) + 1
    end_ix <- nu_counts$c_sum[s]
    
    nu_expanded[[i]][, start_ix:end_ix] <- stanfit_samples[[i]]$nu[, s]
  }
  
  # white log relative risk
  posterior_white[[i]] <- stanfit_samples[[i]]$alpha1 + stanfit_samples[[i]]$psi1 + 
    (stanfit_samples[[i]]$phi * stanfit_samples[[i]]$delta) + 
    nu_expanded[[i]]

  # black log relative risk
  posterior_black[[i]] <- stanfit_samples[[i]]$alpha2 + stanfit_samples[[i]]$psi2 +
    (stanfit_samples[[i]]$phi / stanfit_samples[[i]]$delta) +
    nu_expanded[[i]]

}


dim(posterior_white[[1]])
dim(posterior_black[[1]])
```

```{r}
# risk ratios

# initialize list for risk ratios
pos_med_rr <- list()

# loop through models
for (i in seq_along(stanfit_samples)) {
  
  # calculate risk ratios
  posterior_risk_ratio <- exp(posterior_black[[i]] - posterior_white[[i]])
  
  pos_med_rr[[i]] <- data.frame(
    risk_ratio = matrixStats::colMedians(posterior_risk_ratio),
    c_idx = 1:ncol(posterior_risk_ratio)
  )

  # which columns (counties) have risk ratios significantly different from 1?
  pos_med_rr[[i]]$risk_ratio_sig <- (colMeans(posterior_risk_ratio > 1) > 0.8) |
    (colMeans(posterior_risk_ratio < 1) > 0.8)

}
```


```{r}
# posterior median log relative risk

# initialize list for log relative risks
pos_med <- list()

# loop through models
for (i in seq_along(stanfit_samples)){
  
  pos_med[[i]] <- rbind(
  tibble(
    pos_med_y = matrixStats::colMedians(posterior_white[[i]]), 
    race = 1, 
    c_idx = 1:ncol(posterior_white[[i]])), 
  tibble(
    pos_med_y = matrixStats::colMedians(posterior_black[[i]]), 
    race = 2, 
    c_idx = 1:ncol(posterior_black[[i]]))
  )
}
```

```{r}
# join pos_med and pos_med_rr

# loop through models
for(i in seq_along(stanfit_samples)){
  pos_med[[i]] <- pos_med[[i]] %>%
  dplyr::left_join(pos_med_rr[[i]], by = c("c_idx"))
}
```


```{r}
## Add in correct fipschar, new column for y ----

# loop through models
for (i in seq_along(stanfit_samples)){
  
  pos_med[[i]] <- adrd_ratios_df %>%
    mutate(y = log(observed) - log(expected)) %>% 
    dplyr::left_join(pos_med[[i]], by = c("c_idx", "race"))
}


pos_med[[1]] %>%
  ggplot() +
  geom_point(aes(x = y, y = pos_med_y, col = as.factor(race)))
```

## Decompose log ratios

```{r}
# look at delta
lapply(stanfit_samples, function(x){
  summary(x$delta)
})
```


```{r}
# initialize list
shared <- list()

# loop through models
for(i in seq_along(stanfit_samples)){
  
  shared_w <- (stanfit_samples[[i]]$phi * stanfit_samples[[i]]$delta)
  shared_b <- (stanfit_samples[[i]]$phi / stanfit_samples[[i]]$delta)
  
  # posterior median
  shared[[i]] <- rbind(
    tibble(
      shared = matrixStats::colMedians(shared_w), 
      shared_unscaled = matrixStats::colMedians(stanfit_samples[[i]]$phi), 
      race = 1, 
      c_idx = 1:ncol(shared_w)), 
    tibble(
      shared = matrixStats::colMedians(shared_b), 
      shared_unscaled = matrixStats::colMedians(stanfit_samples[[i]]$phi), 
      race = 2, 
      c_idx = 1:ncol(shared_b))
  )
  
  # is exp(shared) (phi*delta for white, phi/delta for black) for each country for each race 
  # sig diff from 1?
  # note: delta is same for white and black in a give county, shared_sig will be the same 
  # for white and black in a given county
  phi_delta_sig <- rbind(
    tibble(
      race = 1,  
      shared_sig = 
        (colMeans(exp(shared_w) > 1) > 0.8) | 
        (colMeans(exp(shared_w) < 1) > 0.8),
      c_idx = 1:ncol(shared_w)),
    tibble(
      race = 2,  
      shared_sig = 
        (colMeans(exp(shared_b) > 1) > 0.8) | 
        (colMeans(exp(shared_b) < 1) > 0.8),
      c_idx = 1:ncol(shared_b))
  )
  
  # is exp(phi) (shared, unscaled) for each county significantly different from 1?
  # (this is how significance is defined in figure 2 caption)
  phi_sig <- data.frame(
      shared_unscaled_sig = 
        (colMeans(exp(stanfit_samples[[i]]$phi) > 1) > 0.8) | 
        (colMeans(exp(stanfit_samples[[i]]$phi) < 1) > 0.8),
      c_idx = 1:ncol(stanfit_samples[[i]]$phi)
  )
  
  # Join sig columns
  shared[[i]] %<>% 
  dplyr::left_join(phi_delta_sig, by = c("c_idx", "race")) %>%
  dplyr::left_join(phi_sig, by = c("c_idx"))
  
  ## Add in correct fipschar ----
  pos_med[[i]] %<>% 
  dplyr::left_join(shared[[i]], by = c("c_idx", "race"))
  
}


shared[[1]] %>% 
  mutate(race = as.character(race)) %>% 
  ggplot() + 
  geom_density(aes(x = shared_unscaled), linewidth = 1) + 
  geom_density(aes(x = shared, color = race), linewidth = 1) + 
  theme_classic()
```

```{r}
# initialize list
specific <- list()

# loop through models
for (i in seq_along(stanfit_list)) {
  
  specific_w <- stanfit_samples[[i]]$psi1
  specific_b <- stanfit_samples[[i]]$psi2
  
  # posterior median
  specific[[i]] <- rbind(
    tibble(
      specific = matrixStats::colMedians(specific_w), 
      race = 1, 
      c_idx = 1:ncol(specific_w)), 
    tibble(
      specific = matrixStats::colMedians(specific_b), 
      race = 2, 
      c_idx = 1:ncol(specific_b))
    )
  
  # is exp(psi) for each county for each race significantly different from 1?
  # (this is how significance is defined in figure 2 caption)
  psi_sig <- rbind(
    tibble(
      race = 1,  
      specific_sig = 
        (colMeans(exp(specific_w) > 1) > 0.8) | 
        (colMeans(exp(specific_w) < 1) > 0.8),
      c_idx = 1:ncol(specific_w)),
    tibble(
      race = 2,  
      specific_sig = 
        (colMeans(exp(specific_b) > 1) > 0.8) | 
        (colMeans(exp(specific_b) < 1) > 0.8),
      c_idx = 1:ncol(specific_b))
  )

  # Join sig column
  specific[[i]] %<>% 
    dplyr::left_join(psi_sig, by = c("c_idx", "race"))

  ## Add in correct fipschar ----
  pos_med[[i]] %<>% 
    dplyr::left_join(specific[[i]], by = c("c_idx", "race"))
}

specific[[1]] %>% 
  mutate(race = as.character(race)) %>% 
  ggplot() + 
  geom_density(aes(x = specific, color = race), linewidth = 1) + 
  theme_classic()
```


## Calculate empirical variances

```{r}
# function to get median, mean, 2.5 percentile, 97.5 percentile
quick_summarize <- function(x) {
    new_df <- x %>%
        dplyr::as_data_frame() %>%
        dplyr::summarize(
            median = stats::median(value),
            p025 = stats::quantile(value, .025),
            p975 = stats::quantile(value, .975)
        )
    return(new_df)
}
```

```{r}
# initialize list
empiric_vars <- list()

# loop through models
for (i in seq_along(stanfit_list)){
  
  # mini table for total risk
  empiric_var_risks <- rbind(
      matrixStats::rowVars(
          stanfit_samples[[i]]$alpha1 + stanfit_samples[[i]]$psi1 +
              (stanfit_samples[[i]]$phi * stanfit_samples[[i]]$delta) +
              nu_expanded[[i]]
      )  %>%
          quick_summarize() %>%
          dplyr::mutate(race = "White"),
      matrixStats::rowVars(
          stanfit_samples[[i]]$alpha2 + stanfit_samples[[i]]$psi2 +
              (stanfit_samples[[i]]$phi / stanfit_samples[[i]]$delta) +
              nu_expanded[[i]]
      ) %>%
          quick_summarize() %>%
          dplyr::mutate(race = "Black")
  ) %>%
      dplyr::mutate(param = "total risk")
  
  
  # mini table for shared risk
  empiric_shared_risk <- rbind(
      matrixStats::rowVars(stanfit_samples[[i]]$phi * stanfit_samples[[i]]$delta)  %>%
          quick_summarize() %>%
          dplyr::mutate(race = "White"),
      matrixStats::rowVars(stanfit_samples[[i]]$phi / stanfit_samples[[i]]$delta)  %>%
          quick_summarize() %>%
          dplyr::mutate(race = "Black")
  ) %>%
      dplyr::mutate(param = "shared risk")
  
  
  # mini table for specific risk
  empiric_specific_risks <- rbind(
      matrixStats::rowVars(stanfit_samples[[i]]$psi1)  %>%
          quick_summarize() %>%
          dplyr::mutate(race = "White"),
      matrixStats::rowVars(stanfit_samples[[i]]$psi2)  %>%
          quick_summarize() %>%
          dplyr::mutate(race = "Black")
  ) %>%
      dplyr::mutate(param = "specific risk")
  
  # mini table for fraction shared risk
  empiric_shared_var_frac <- rbind(
      quick_summarize(
          matrixStats::rowVars(stanfit_samples[[i]]$phi * stanfit_samples[[i]]$delta) /
              (
                  matrixStats::rowVars(stanfit_samples[[i]]$phi * stanfit_samples[[i]]$delta) +
                      matrixStats::rowVars(stanfit_samples[[i]]$psi1)
              )
      ) %>%
          dplyr::mutate(race = "White"),
      quick_summarize(
          matrixStats::rowVars(stanfit_samples[[i]]$phi / stanfit_samples[[i]]$delta) /
              (
                  matrixStats::rowVars(stanfit_samples[[i]]$phi / stanfit_samples[[i]]$delta) +
                      matrixStats::rowVars(stanfit_samples[[i]]$psi2)
              )
      ) %>%
          dplyr::mutate(race = "Black")
  ) %>%
      dplyr::mutate(param = "fraction shared risk")
  
  
  # mini table for state risk
  state_vars <- rbind(
      quick_summarize(stanfit_samples[[i]]$sigma_s ^ 2) %>%
          dplyr::mutate(
              race = "both",
              param = "state variance"
          )
  )
  
  # bind all mini tables together
  empiric_vars[[i]] <- rbind(
      empiric_var_risks,
      state_vars,
      empiric_shared_risk,
      empiric_specific_risks,
      empiric_shared_var_frac
  ) %>%
      dplyr::select(race, param, dplyr::everything()) %>%
      dplyr::mutate(
          param = factor(
              param,
              levels =  c(
                  "total risk",
                  "shared risk",
                  "specific risk",
                  "fraction shared risk",
                  "state variance"
              ),
              ordered = TRUE
          ),
          race = factor(
              race,
              levels = c("White", "Black", "both"),
              ordered = TRUE
          )
      )
  
  # sort table
  empiric_vars[[i]] <- empiric_vars[[i]] %>%
      dplyr::arrange(param, race)
  
  # new column formatted with posterior median and 95% CI
  empiric_vars[[i]]$median_ci <- paste0(round(empiric_vars[[i]]$median, 2), " (", 
                                   round(empiric_vars[[i]]$p025, 2), ", ",
                                   round(empiric_vars[[i]]$p975, 2), ")")
  
  # rename columns
  empiric_vars[[i]] <- empiric_vars[[i]] |>
    select(-c(median, p025, p975)) |>
    rename(Parameter = param,
              Race = race,
           Estimate = median_ci)
}
```

```{r}
# before saving pos_med model results, name list elements for clarity
list_names <- c("m1", "m2", "m3")
names(pos_med) <- list_names
names(empiric_vars) <- list_names
names(stanfit_samples) <- list_names
```

```{r}
write_rds(pos_med, paste0("data/intermediate/adrd_pos_med.rds"))
write_rds(empiric_vars, file = paste0("results/tables/empirical_variance.rds"))
write_rds(stanfit_samples, paste0("data/intermediate/adrd_stanfit_samples.rds"))
#write_rds(stanfit_summary, paste0("data/intermediate/adrd_stanfit_summary.rds"))
```
