
```{r, message=FALSE, warning=FALSE}
## Load libraries ----
library(tidyverse)
library(magrittr)
library(ggplot2)
library(sf)
```

```{r}
## Read data ----
adrd_county_df <- read_csv("../data/input/local/adrd_county_df.csv")
county_fips_df <- read_rds("../data/intermediate/county_fips_df.rds")
county_adj_df <- read_rds("../data/intermediate/county_adj_df.rds")
```

```{r}
## read county shp files
county_sf <- read_sf("../data/input/local/tl_2022_us_county/tl_2022_us_county.shp")
```

```{r}
## Subset ----
##  Just get FIPS we want and subset to population of interest --
adrd_county_df %<>%
    filter(county %in% as.integer(county_fips_df$fipschar), 
           age_grp %in% c("[65,75)", "[75,85)", ">85"))

##  Replace NA with 0 --
adrd_county_df$n_enrollees[is.na(adrd_county_df$n_enrollees)] <- 0 
adrd_county_df$n_adrd[is.na(adrd_county_df$n_adrd)] <- 0 

sum(adrd_county_df$n_enrollees)
sum(adrd_county_df$n_adrd)
```

```{r}
## Plot number of enrollees across years ----
adrd_county_df %>% 
  mutate(race = as.character(race)) %>% 
  group_by(year, race) %>% 
  summarise(n_enrollees = sum(n_enrollees)) %>% 
  ggplot() + 
  geom_line(aes(x = year, y = n_enrollees, color = race))
```

```{r}
## Plot number of adrd admissions across years ----
adrd_county_df %>% 
  mutate(race = as.character(race)) %>% 
  group_by(year, race) %>% 
  summarise(n_adrd = sum(n_adrd)) %>% 
  ggplot() + 
  geom_line(aes(x = year, y = n_adrd, color = race))
```

```{r}
#! ----> temporarily remove 2011 onwards
adrd_county_df %<>% 
  filter(year <= 2010)

sum(adrd_county_df$n_enrollees)
sum(adrd_county_df$n_adrd)
```

```{r}
## Number of enrollees by county-sex-age_grp split by race group ----
adrd_county_df %>% 
  mutate(race = as.character(race)) %>% 
  ggplot() + 
  geom_density(aes(x = n_enrollees, color = race))
```

```{r}
## Number of enrollees by county-sex-age_grp split by race group ----
adrd_county_df %>% 
  filter(n_enrollees < 500) %>% 
  mutate(race = as.character(race)) %>% 
  ggplot() + 
  geom_histogram(aes(x = n_enrollees, color = race)) +
  facet_grid(~race)
```

```{r}
## Adrd blind-to-counties rates for each race-sex-age_grp----
adrd_county_df %>% 
  group_by(race, sex, age_grp) %>% 
  summarise(n_enrollees = sum(n_enrollees), 
            n_adrd = sum(n_adrd),
            adrd_rate = n_adrd / n_enrollees * 1e5) %>% 
  mutate(race_sex = paste(race, sex, sep = "_")) %>% 
  ggplot() +
  geom_boxplot(aes(x = age_grp, y = adrd_rate)) + 
  geom_jitter(aes(x = age_grp, y = adrd_rate, col = race_sex))
```

```{r}
## Adrd county rates for each race-sex-age_grp ----
adrd_county_df %>% 
  group_by(county, race, sex, age_grp) %>% 
  summarise(n_enrollees = sum(n_enrollees), 
            n_adrd = sum(n_adrd),
            adrd_rate = n_adrd / n_enrollees * 1e5) %>% 
  mutate(race_sex = paste(race, sex, sep = "_")) %>% 
  ggplot() +
  geom_boxplot(aes(x = age_grp, y = adrd_rate)) + 
  geom_jitter(aes(x = age_grp, y = adrd_rate, col = race_sex)) + 
  facet_wrap(~race)
```

```{r}
xx <- adrd_county_df

xx$sex[adrd_county_df$sex == 1] = "male"
xx$sex[adrd_county_df$sex == 2] = "female"

## Reference adrd rates for each sex/age_grp blind to race ----
xx %>% 
  mutate(race = as.character(race)) %>% 
  group_by(race, sex, age_grp) %>% 
  summarise(n_enrollees = sum(n_enrollees), 
            n_adrd = sum(n_adrd),
            adrd_rate = n_adrd / n_enrollees * 1e5) %>% 
  group_by(sex, age_grp) %>% 
  summarise(adrd_rate = mean(adrd_rate)) %>%  
  ggplot() + 
  geom_point(aes(x = age_grp, y = adrd_rate, color = sex)) + 
  labs(title = "ADRD reference rates", x = "Age group", y = "ADRD rate") + 
  theme_bw()
  
```

```{r}
## look at proportions by race
prettyNum(prop.table(tapply(adrd_county_df$n_enrollees, adrd_county_df$race, sum)))
```

```{r}
xx <- adrd_county_df

## Observed county-level ADRD counts
xx$race[adrd_county_df$race == 1] = "white"
xx$race[adrd_county_df$race == 2] = "black"

xx %<>% 
  group_by(county, race) %>% 
  summarise(n_adrd = sum(n_adrd))

county_sf %>% 
  filter(STATEFP == "37") %>% 
  select(GEOID) %>% 
  left_join(
    xx %>%  
      mutate(county = as.character(county)), 
    by = c("GEOID" = "county")
  ) %>% 
  ggplot() + 
  geom_sf(aes(fill = n_adrd), alpha = 0.75) +
  facet_wrap(~race, nrow = 2) + 
  labs(title = "Observed") + 
  guides(fill = guide_legend(title = "ADRD counts")) + 
  theme_classic()
```

* adrd hospitalizations entangle prevalence and severity, specially in "small" counties 
* biased measurement error? noise systematically affects certain groups
* even if not affecting certain groups, measurement error decreases the power of the model
* variance of the inference, will not detect statistical differences in the output

## Observed vs expected rates

```{r}
## Get the standard rates ----
## We just get the standard rate for each sex/age group combination
## combining all observations over the time period (over fips).
exp_df <- adrd_county_df %>%
    dplyr::group_by(race, sex, age_grp) %>% # race, sex, age_grp
    dplyr::summarize(
        n_adrd = sum(n_adrd),
        n_enrollees = sum(n_enrollees),
        exp_rate = n_adrd / n_enrollees
    ) %>% 
  group_by(sex, age_grp) %>% 
  summarise(exp_rate = mean(exp_rate)) # equal weight to race
exp_df
```

```{r}
## Aggregate over years ----
## Just tally up the number of person years and deaths over all years
obs_df <- adrd_county_df %>%
    dplyr::group_by(county, race, sex, age_grp) %>% #county, race, sex, age_grp
    dplyr::summarize(n_enrollees = sum(n_enrollees),
                     n_adrd = sum(n_adrd), 
                     obs_rate = n_adrd / n_enrollees)

## fill NAs
obs_df %>% 
  filter(n_enrollees == 0) 

obs_df$obs_rate[is.na(obs_df$obs_rate)] <- 0
```

```{r}
## Merge with exp_df ----
adrd_ratios_df <- obs_df %>%
    dplyr::left_join(exp_df %>%
                         dplyr::select(sex, age_grp, exp_rate),
                     by = c("sex", "age_grp"))

## Now aggregate age ----
adrd_ratios_df %<>% 
  mutate(
    expected = n_enrollees * exp_rate, 
    observed = n_adrd
  ) %>% 
  dplyr::group_by(county, race) %>%
  dplyr::summarize(
    person_years = sum(n_enrollees),
    expected = sum(expected), 
    observed = sum(observed)) %>%
  dplyr::ungroup()

adrd_ratios_df %>% 
  mutate(
    rel_ratio = observed / expected,
    race = as.character(race)
  ) %>% 
  ggplot() + 
  geom_density(aes(x = rel_ratio, color = race))
```

```{r}
adrd_ratios_df %>% 
  ggplot() + 
  geom_point(aes(x = observed, y = expected, color = race), alpha = 0.5) + 
  scale_x_sqrt() + 
  scale_y_sqrt()
```


```{r}
adrd_ratios_df %>% 
  mutate(
    log_diff = log(observed) - log(expected),
    race = as.character(race)
    ) %>% 
  ggplot() + 
  geom_density(aes(x = log_diff, color = race))
```


```{r}
## Save ----
write_rds(adrd_ratios_df, "../data/intermediate/adrd_ratios_df.rds")
```
