```{r setup, include=FALSE}
## Set working directory as project root
library(here)
knitr::opts_knit$set(root.dir = here())
```

```{r, message=FALSE, warning=FALSE}
## load packages ----
library(tidyverse)
library(magrittr)
library(sf)
```

In this notebook we make sure that the counties match in all objects: the adjacency matrix, geometry, hosp rates, sociodemographic and pollution data.

## Adjacency matrix

```{r}
####
# Download adjacency
####

## Import data ----
county_adj_df <- readr::read_delim(
    '../data/county/county_adjacency.txt',
    delim = "\t",
    escape_double = FALSE,
    col_names = c("name_i", "fips_i",
                  "name_j", "fips_j"),
    trim_ws = TRUE
)

county_adj_df
```

```{r}
## Forward fill ----
county_adj_df <- zoo::na.locf(county_adj_df)

## Remove self loops and add state fips ----
county_adj_df <- county_adj_df %>%
    dplyr::filter(fips_i != fips_j) %>%
    dplyr::mutate(state_i = substr(fips_i, 1, 2),
                  state_j = substr(fips_j, 1, 2))

## Fix FIPS ----
## Bedford City got lumped together with Bedford county in CMF data
county_adj_df <- county_adj_df %>%
    dplyr::filter(fips_i != "51515",
                  fips_j != "51515")

## Now remove states/territories we won't use ----
county_adj_df <- dplyr::filter(county_adj_df,
                                  !state_i %in% c("02","15", "66", "72", "60", "69", "78"),
                                  !state_j %in% c("02","15", "66", "72", "60", "69", "78"))

county_adj_df %<>% 
  mutate(county = as.numeric(fips_i))

county_adj_df
```

## Shapefiles

```{r}
## read county shp files
county_sf <- read_sf("../data/county/tl_2015_us_county/tl_2015_us_county.shp") %>%
  filter(!STATEFP %in% c("02","15", "66", "72", "60", "69", "78")) %>% 
  mutate(county = as.numeric(GEOID))

dim(county_sf)
length(unique(county_adj_df$fips_i))
length(unique(county_adj_df$fips_j))
length(unique(county_adj_df$county))

counties_adj_ = unique(county_adj_df$county)
counties_shp_ = unique(county_sf$county)

setdiff(counties_shp_, counties_adj_) #46102
setdiff(counties_adj_, counties_shp_) #46113
```

```{r}
county_sf %>%
  st_simplify() %>%
  ggplot() +
  geom_sf() + 
  geom_sf(data = county_sf[!county_sf$county %in% counties_adj_, ], fill="blue")
```

```{r}
county_sf$county[county_sf$county == 46102] <- 46113 #Oglala Lakota County, SD. Shannon County, SD (FIPS code = 46113) was renamed Oglala Lakota County and assigned anew FIPS code (46102) effective in 2014

counties_adj_ = unique(county_adj_df$county)
counties_shp_ = unique(county_sf$county)

setdiff(counties_shp_, counties_adj_)
setdiff(counties_adj_, counties_shp_)

#write_rds(county_sf, "../data/symlinks/temp/county_sf.rds")
```

## All-cause data

```{r}
hosp_county_df <- read_csv("../data/symlinks/temp/hosp_rates.csv") %>% 
  filter(!state %in% c(2, 15, 66, 72, 60, 69, 78))

counties_hosp_ = unique(hosp_county_df$county)

length(counties_hosp_) #3109
setdiff(counties_hosp_, counties_adj_) 
#when using 2010 crosswalk 51515 51560
#when using 2015 crosswalk 46102
setdiff(counties_adj_, counties_hosp_) 
#when using 2010 crosswalk 8014
#when using 2015 crosswalk none
```

```{r}
#Shannon County, SD (FIPS code = 46113) was renamed Oglala Lakota County and assigned anew FIPS code (46102) effective in 2014
zip_county <- read.csv("../data/county/zip_county_2015.csv")

zip_county %>% 
  filter(county %in% c(46113, 46102))
```

```{r}
hosp_county_df$county[hosp_county_df$county == 46102] <- 46113

hosp_county_df %<>% 
  group_by(county, year, race, sex, age_grp, state) %>% 
  summarise(n_enrollees = sum(n_enrollees), 
            n_admissions = sum(n_admissions)) %>% 
  ungroup()
```

```{r}
counties_hosp_ = unique(hosp_county_df$county)

length(counties_hosp_)
setdiff(counties_hosp_, counties_adj_)
setdiff(counties_adj_, counties_hosp_)
```

## Sociodemographic

* year 2000

```{r}
census_county_df <- read_csv("../data/symlinks/prepped_census/census_county_interpolated.csv") %>% 
  rename(county = fips) %>% 
  mutate(county = as.numeric(county), 
         state = round(county / 1000)) %>% 
  filter(!state %in% c(2, 15, 66, 72, 60, 69, 78))

census_county_2000_df <- census_county_df %>% 
  filter(year == 2000, 
         !is.na(median_household_income)) 

counties_census_ = unique(census_county_2000_df$county)

length(counties_census_)
setdiff(counties_census_, counties_adj_) #46102
setdiff(counties_adj_, counties_census_) #46113
```

```{r}
census_county_2000_df$county[census_county_2000_df$county == 46102] <- 46113
sum(is.na(census_county_2000_df$median_household_income))
```

* year 2010

```{r}
census_county_2010_df <- census_county_df %>% 
  filter(year == 2010, 
         !is.na(median_household_income)) 

counties_census_ = unique(census_county_2010_df$county)

length(counties_census_)
setdiff(counties_census_, counties_adj_) #46102
setdiff(counties_adj_, counties_census_) #46113
```

```{r}
census_county_2010_df$county[census_county_2010_df$county == 46102] <- 46113
sum(is.na(census_county_2010_df$median_household_income))
```

```{r}
median_household_df <- census_county_2000_df %>% 
  rename(med_house_income_2000 = median_household_income) %>% 
  select(county, med_house_income_2000) %>% 
  left_join(
    census_county_2010_df %>% 
    rename(med_house_income_2010 = median_household_income) %>% 
    select(county, med_house_income_2010)
  ) 

median_household_df$med_house_income <- rowMeans(median_household_df[,-1])
```

## Pollution

```{r, echo=FALSE, message=FALSE}
pollution_county_df <- read_csv("../data/symlinks/county_rm/data/county_pm25_2000.csv")
years_ <- 2001:2018
for(y_ in years_) {
  pollution_county_df <- rbind(pollution_county_df, 
                               read_csv(paste0("../data/symlinks/county_rm/data/county_pm25_", y_, ".csv")))
}
pollution_county_df %<>% 
  group_by(fips) %>% 
  summarise(pm25 = mean(pm25))
```

```{r}
pollution_county_df %<>% 
  rename(county = fips) %>% 
  mutate(county = as.numeric(county), 
         state = round(county / 1000)) %>% 
  filter(!state %in% c(2, 15, 66, 72, 60, 69, 78))

counties_pollution_ = unique(pollution_county_df$county)

length(counties_pollution_)
setdiff(counties_pollution_, counties_adj_) #46102
setdiff(counties_adj_, counties_pollution_) #46113
```

```{r}
pollution_county_df$county[pollution_county_df$county == 46102] <- 46113
```

* merge datasets

```{r}
hosp_county_df %<>%
  left_join(
    median_household_df %>% select(county, med_house_income)
  ) %>% 
  left_join(
    pollution_county_df %>% select(county, pm25)
  )

write_rds(hosp_county_df, "../data/symlinks/temp/hosp_county_df.rds")
```

```{r}
lapply(hosp_county_df, summary)
```
