
```{r, message=FALSE, warning=FALSE}
## Load libraries ----
library(tidyverse)
library(magrittr)
library(ggplot2)
library(sf)
#library(feather)
#library(cowplot)
library(RColorBrewer)
library(viridis)
```

```{r}
## Read data ----
adrd_county_df <- read_rds("../data/intermediate/adrd_county_df.rds")
county_sf <- read_rds("../data/intermediate/county_sf.rds")
county_fips_df <- read_rds("../data/intermediate/county_fips_df.rds")

length(unique(adrd_county_df$county))
length(unique(county_sf$county))
length(unique(county_fips_df$county))

counties_shp_ = unique(county_sf$county)
counties_adrd_ = unique(adrd_county_df$county)
counties_ = unique(county_fips_df$county)

setdiff(counties_shp_, counties_adrd_)
setdiff(counties_adrd_, counties_shp_)
setdiff(counties_, counties_shp_)
setdiff(counties_shp_, counties_)
```

```{r}
## Subset ----
##  Subset to population of interest --
adrd_county_df %<>%
    filter(age_grp %in% c("[65,75)", "[75,85)", ">85"))

##  Replace NA with 0 --
adrd_county_df$n_enrollees[is.na(adrd_county_df$n_enrollees)] <- 0 
adrd_county_df$n_adrd[is.na(adrd_county_df$n_adrd)] <- 0 

sum(adrd_county_df$n_enrollees)
sum(adrd_county_df$n_adrd)

counties_shp_ = unique(county_sf$county)
counties_adrd_ = unique(adrd_county_df$county)

setdiff(counties_shp_, counties_adrd_)
setdiff(counties_adrd_, counties_shp_)
```

```{r}
## Plot number of enrollees across years ----
adrd_county_df %>% 
  mutate(race = as.character(race)) %>% 
  group_by(year, race) %>% 
  summarise(n_enrollees = sum(n_enrollees)) %>% 
  ggplot() + 
  geom_line(aes(x = year, y = n_enrollees, color = race))
```

```{r}
## Plot number of adrd admissions across years ----
adrd_county_df %>% 
  mutate(race = as.character(race)) %>% 
  group_by(year, race) %>% 
  summarise(n_adrd = sum(n_adrd)) %>% 
  ggplot() + 
  geom_line(aes(x = year, y = n_adrd, color = race))
```

```{r}
## Number of enrollees by county-sex-age_grp split by race group ----
adrd_county_df %>% 
  mutate(race = as.character(race)) %>% 
  ggplot() + 
  geom_density(aes(x = n_enrollees, color = race))
```

```{r}
## Number of enrollees by county-sex-age_grp split by race group ----
adrd_county_df %>% 
  filter(n_enrollees < 500) %>% 
  mutate(race = as.character(race)) %>% 
  ggplot() + 
  geom_histogram(aes(x = n_enrollees, color = race)) +
  facet_grid(~race)
```

```{r}
## Adrd blind-to-counties rates for each race-sex-age_grp----
adrd_county_df %>% 
  group_by(race, sex, age_grp) %>% 
  summarise(n_enrollees = sum(n_enrollees), 
            n_adrd = sum(n_adrd),
            adrd_rate = n_adrd / n_enrollees * 1e5) %>% 
  mutate(race_sex = paste(race, sex, sep = "_")) %>% 
  ggplot() +
  geom_boxplot(aes(x = age_grp, y = adrd_rate)) + 
  geom_jitter(aes(x = age_grp, y = adrd_rate, col = race_sex))
```

```{r}
## Adrd county rates for each race-sex-age_grp ----
adrd_county_df %>% 
  group_by(county, race, sex, age_grp) %>% 
  summarise(n_enrollees = sum(n_enrollees), 
            n_adrd = sum(n_adrd),
            adrd_rate = n_adrd / n_enrollees * 1e5) %>% 
  mutate(race_sex = paste(race, sex, sep = "_")) %>% 
  ggplot() +
  geom_boxplot(aes(x = age_grp, y = adrd_rate)) + 
  geom_jitter(aes(x = age_grp, y = adrd_rate, col = race_sex)) + 
  facet_wrap(~race)
```

```{r}
adrd_county_df %>% 
  group_by(race, sex, age_grp) %>% 
  summarise(n_enrollees = sum(n_enrollees), 
            n_adrd = sum(n_adrd),
            adrd_rate = n_adrd / n_enrollees * 1e5) %>% 
  group_by(sex, age_grp) %>% 
  summarise(adrd_rate = mean(adrd_rate))
```

```{r}
xx <- adrd_county_df

xx$sex[adrd_county_df$sex == 1] = "male"
xx$sex[adrd_county_df$sex == 2] = "female"

## Reference adrd rates for each sex/age_grp blind to race ----
xx %>% 
  mutate(race = as.character(race)) %>% 
  group_by(race, sex, age_grp) %>% 
  summarise(n_enrollees = sum(n_enrollees), 
            n_adrd = sum(n_adrd),
            adrd_rate = n_adrd / n_enrollees * 1e5) %>% 
  group_by(sex, age_grp) %>% 
  summarise(adrd_rate = mean(adrd_rate)) %>%  
  ggplot() + 
  geom_point(aes(x = age_grp, y = adrd_rate, color = sex)) + 
  labs(title = "ADRD reference rates", x = "Age group", y = "ADRD rate") + 
  theme_bw()
ggsave("../results/figures/adrd_reference_rates.png")
```

```{r}
## look at proportions by race
prettyNum(prop.table(tapply(adrd_county_df$n_enrollees, adrd_county_df$race, sum)))
```

```{r}
xx <- adrd_county_df

## Observed county-level ADRD counts
xx$race[xx$race == 1] = "white"
xx$race[xx$race == 2] = "black"

xx %<>% 
  group_by(county, race) %>% 
  summarise(n_adrd = sum(n_adrd))

counties_shp_ = unique(county_sf$county)
counties_xx_w_ = unique(xx$county[xx$race == "white"])
counties_xx_b_ = unique(xx$county[xx$race == "black"])

setdiff(counties_shp_, counties_xx_w_)
setdiff(counties_xx_w_, counties_shp_)
setdiff(counties_shp_, counties_xx_b_)
setdiff(counties_xx_b_, counties_shp_)
```

```{r}
length(unique(xx$county))
sum(is.na(xx$race))
```

```{r}
yy <- county_sf %>% 
  select(county) %>% 
  left_join(xx) 

length(unique(yy$county))
sum(is.na(yy$race))
sum(is.na(yy$n_adrd))
```

```{r}
yy %>%
  filter(race == "white") %>% 
  st_simplify() %>%
  ggplot() +
  geom_sf(aes(fill = n_adrd), alpha = 1, lwd = 0.0)

yy %>%
  filter(race == "black") %>% 
  st_simplify() %>%
  ggplot() +
  geom_sf(aes(fill = n_adrd), alpha = 1, lwd = 0.0)
```

```{r}
n_adrd_ <- yy$n_adrd
myPalette <- colorRampPalette(rev(RColorBrewer::brewer.pal(11, "Spectral")))
sc <- scale_fill_gradientn(colors = myPalette(10), 
                           limits = c(min(n_adrd_, na.rm = TRUE), max(n_adrd_, na.rm = TRUE)))

yy  %>% 
  ggplot() + 
  geom_sf(aes(fill = n_adrd), alpha = 1, lwd = 0.0) +
  facet_wrap(~race, ncol = 2) + 
  labs(title = "Observed") + 
  guides(fill = guide_legend(title = "ADRD counts")) + 
  theme_classic() + 
  theme(legend.position = "bottom") + 
  sc
#the yellow looks like white, try another visualization package
```

```{r}
yy %>% 
  ggplot() + 
  geom_sf(aes(fill = n_adrd), alpha = 1, lwd = 0.0) +
  facet_wrap(~race, ncol = 2) + 
  labs(title = "Observed") + 
  guides(fill = guide_legend(title = "ADRD counts")) + 
  theme_classic() + 
  scale_fill_viridis(name = "n_adrd", option = "D")
```

* adrd hospitalizations entangle prevalence and severity, specially in "small" counties 
* biased measurement error? noise systematically affects certain groups
* even if not affecting certain groups, measurement error decreases the power of the model
* variance of the inference, will not detect statistical differences in the output

## Observed vs expected

```{r}
## Get the standard rates ----
## We just get the standard rate for each sex/age group combination
## combining all observations over the time period (over fips).
exp_df <- adrd_county_df %>%
    dplyr::group_by(race, sex, age_grp) %>% # race, sex, age_grp
    dplyr::summarize(
        n_adrd = sum(n_adrd),
        n_enrollees = sum(n_enrollees),
        exp_rate = n_adrd / n_enrollees
    ) %>% 
  group_by(sex, age_grp) %>% 
  summarise(exp_rate = mean(exp_rate)) # equal weight to race
exp_df
```

```{r}
## Aggregate over years ----
## Just tally up the number of person years and deaths over all years
obs_df <- adrd_county_df %>%
    dplyr::group_by(county, race, sex, age_grp) %>% #county, race, sex, age_grp
    dplyr::summarize(n_enrollees = sum(n_enrollees),
                     n_adrd = sum(n_adrd), 
                     obs_rate = n_adrd / n_enrollees)

## fill NAs
obs_df %>% 
  filter(n_enrollees == 0) 

obs_df$obs_rate[is.na(obs_df$obs_rate)] <- 0
```

```{r}
## Merge with exp_df ----
adrd_ratios_df <- obs_df %>%
    dplyr::left_join(exp_df %>%
                         dplyr::select(sex, age_grp, exp_rate),
                     by = c("sex", "age_grp"))

## Now aggregate age ----
adrd_ratios_df %<>% 
  mutate(
    expected = n_enrollees * exp_rate, 
    observed = n_adrd
  ) %>% 
  dplyr::group_by(county, race) %>%
  dplyr::summarize(
    person_years = sum(n_enrollees),
    expected = sum(expected), 
    observed = sum(observed)) %>%
  dplyr::ungroup()

adrd_ratios_df %>% 
  mutate(
    rel_ratio = observed / expected,
    race = as.character(race)
  ) %>% 
  ggplot() + 
  geom_density(aes(x = rel_ratio, color = race))
```

```{r}
adrd_ratios_df %>% 
  ggplot() + 
  geom_point(aes(x = observed, y = expected, color = as.factor(race)), alpha = 0.5) + 
  scale_x_sqrt() + 
  scale_y_sqrt()
```

```{r}
adrd_ratios_df %>% 
  mutate(
    log_diff = log(observed) - log(expected),
    race = as.character(race)
    ) %>% 
  ggplot() + 
  geom_density(aes(x = log_diff, color = race))
```

```{r}
xx <- adrd_ratios_df
xx$race[xx$race == 1] = "white"
xx$race[xx$race == 2] = "black"

xx %<>% 
  mutate(
    log_diff = log(observed/expected),
    log_diff = if_else(observed == 0, as.numeric(NA), log_diff)
    )

counties_shp_ = unique(county_sf$county)
counties_xx_w_ = unique(xx$county[xx$race == "white"])
counties_xx_b_ = unique(xx$county[xx$race == "black"])

setdiff(counties_shp_, counties_xx_w_)
setdiff(counties_xx_w_, counties_shp_)
setdiff(counties_shp_, counties_xx_b_)
setdiff(counties_xx_b_, counties_shp_)
```

```{r}
length(unique(xx$county))
sum(is.na(xx$race))
```

```{r}
yy <- county_sf %>% 
  select(county) %>% 
  left_join(xx) 

length(unique(yy$county))
sum(is.na(yy$race))
sum(is.na(yy$log_diff))
sum(yy$person_years == 0)
sum(yy$observed == 0)
```

```{r}
yy %>% 
  mutate(person_years = log(person_years)) %>% 
  ggplot() + 
  geom_sf(aes(fill = person_years), alpha = 1, lwd = 0.0) +
  scale_fill_viridis(name = "person_years", option = "D") +
  facet_wrap(~race, ncol = 2) + 
  labs(title = "log person years") + 
  theme(legend.position = "bottom")
```

```{r}
## person years is zero
yy %>%
  st_simplify() %>%
  mutate(zero_persons = (person_years == 0)) %>%
  ggplot() + 
  geom_sf(aes(fill = zero_persons), alpha = 1, lwd = 0.0) + 
  facet_grid(~race)
```

```{r}
## observed is zero
yy %>%
  st_simplify() %>%
  mutate(zero_observed = (observed == 0)) %>%
  ggplot() + 
  geom_sf(aes(fill = zero_observed), alpha = 1, lwd = 0.0) + 
  facet_grid(~race)
```

```{r}
yy %>%
  filter(race == "white") %>% 
  st_simplify() %>%
  ggplot() +
  geom_sf(aes(fill = log_diff), alpha = 1, lwd = 0.0)

yy %>%
  filter(race == "black") %>% 
  st_simplify() %>%
  ggplot() +
  geom_sf(aes(fill = log_diff), alpha = 1, lwd = 0.0)
```

```{r}
yy %>% 
  ggplot() + 
  geom_sf(aes(fill = log_diff), alpha = 1, lwd = 0.0) +
  scale_fill_viridis(name = "log_diff", option = "D") +
  facet_wrap(~race, ncol = 2) + 
  labs(title = "log(observed) - log(expected)") + 
  theme(legend.position = "bottom")
```

```{r}
## Prep data ----
adrd_ratios_df %<>% 
  mutate(
    black = as.integer(if_else(race == 2, 1, 0)),
    expected = as.integer(ceiling(expected)), 
    observed = as.integer(ceiling(observed))
  ) %>% 
  left_join(county_fips_df)

sum(is.na(adrd_ratios_df$c_idx))
sum(is.na(adrd_ratios_df$s_idx))
sum(is.na(adrd_ratios_df$observed))
sum(is.na(adrd_ratios_df$expected))
sum(is.na(adrd_ratios_df$person_years))
```

```{r}
write_rds(adrd_ratios_df, "../data/intermediate/adrd_ratios_df.rds")
```
