
```{r setup, include=FALSE}
## Set working directory as project root
library(here)
knitr::opts_knit$set(root.dir = here())
```

Description:
- Outcome: hospitalizations without ADRD (sex-age standardized only)
- Basic stats (for table 1) and visualizations
- National rates (used for expected counts)
- Observed and expected counts

```{r, message=FALSE, warning=FALSE}
## Load libraries ----
library(tidyverse)
library(magrittr)
library(ggplot2)
library(sf)
library(RColorBrewer)
library(viridis)
library(ggthemes)
library(knitr)
library(kableExtra)
library(xtable)
```

```{r}
## Read data ----
hosp_county_df <- read_rds("data/symlinks/scratch/hosp_county_df.rds")
county_sf <- read_rds("data/symlinks/scratch/county_sf.rds")
county_fips_df <- read_rds("data/symlinks/scratch/county_fips_df.rds")

length(unique(hosp_county_df$county))
length(unique(county_sf$county))
length(unique(county_fips_df$county))

counties_shp_ = unique(county_sf$county)
counties_hosp_ = unique(hosp_county_df$county)
counties_ = unique(county_fips_df$county)

setdiff(counties_shp_, counties_hosp_)
setdiff(counties_hosp_, counties_shp_)
setdiff(counties_, counties_shp_)
setdiff(counties_shp_, counties_)
```

# MUST MAKE NA = 0 BEFORE SUBSTRACTING ADRD HOSP

```{r}
## Subset ----
##  Subset to population of interest --
hosp_county_df %<>%
    filter(age_grp %in% c("[65,75)", "[75,85)", ">85"))

##  Replace NA with 0 --
hosp_county_df$n_enrollees[is.na(hosp_county_df$n_enrollees)] <- 0 
hosp_county_df$n_admissions[is.na(hosp_county_df$n_admissions)] <- 0 

counties_shp_ = unique(county_sf$county)
counties_hosp_ = unique(hosp_county_df$county)

setdiff(counties_shp_, counties_hosp_)
setdiff(counties_hosp_, counties_shp_)
```

```{r}
# subtract ADRD from number of hosp admissions

# read in ADRD data
adrd_county_df <- read_rds("data/symlinks/scratch/adrd_county_df.rds") %>%
  select(-c("n_enrollees", "state", "med_house_income", "house_price_income_ratio", "pm25")) %>%
  rename("n_admissions_adrd" = "n_admissions")

##  Replace NA with 0 -- (HERE TOO)
adrd_county_df$n_admissions_adrd[is.na(adrd_county_df$n_admissions_adrd)] <- 0 

# rename n_admissions for clarity
hosp_county_df %<>%
  rename("n_admissions_hosp" = "n_admissions")

# merge with all-cause hosp data
hosp_county_df <- merge(hosp_county_df, adrd_county_df,
                   by = c("county", "year", "race", "sex", "age_grp"))

# subtract out # of ADRD admissions to get new n_admissions for all-cause hosp minus ADRD
hosp_county_df %<>%
  mutate(n_admissions = n_admissions_hosp - n_admissions_adrd)
```

```{r}
b <- hosp_county_df %>%
  select(county, year, race, sex, age_grp, n_admissions_hosp, n_admissions_adrd, n_admissions) %>%
  arrange(age_grp, sex, race, year, county)
# 
# which(round(b$n_admissions_hosp, 1) != round(b$n_admissions_adrd + b$n_admissions, 1))
```

```{r}
# get basic stats from data (before rounding)

# total # of hospitalizations
sum(hosp_county_df$n_admissions)

# number of hospitalizations by race
hosp_county_df %>%
  group_by(race) %>%
  summarise(total_hosp = sum(n_admissions, na.rm = TRUE))
```

```{r}
## Plot number of enrollees across years ----
hosp_county_df %>% 
  mutate(race = as.character(race)) %>% 
  group_by(year, race) %>% 
  summarise(n_enrollees = sum(n_enrollees)) %>% 
  ggplot() + 
  geom_line(aes(x = year, y = n_enrollees, color = race))
```

```{r}
## Plot number of hosp admissions across years ----
hosp_county_df %>% 
  mutate(race = as.character(race)) %>% 
  group_by(year, race) %>% 
  summarise(n_admissions = sum(n_admissions)) %>% 
  ggplot() + 
  geom_line(aes(x = year, y = n_admissions, color = race))
```

## Observed vs expected

```{r}
# stage 1
# get race-specific national rates for each sex/age combination 
exp_stage1_df <- hosp_county_df %>%
    dplyr::group_by(race, sex, age_grp) %>% # race, sex, age_grp
    dplyr::summarize(
        n_admissions = sum(n_admissions),
        n_enrollee_years = sum(n_enrollees),
        exp_rate_stage1 = n_admissions / n_enrollee_years
    )

# stage 2
# get overall national rates for each sex/age combination 
exp_stage2_df <- hosp_county_df %>%
    dplyr::group_by(sex, age_grp) %>% # sex, age_grp
    dplyr::summarize(
        n_admissions = sum(n_admissions),
        n_enrollee_years = sum(n_enrollees),
        exp_rate_stage2 = n_admissions / n_enrollee_years
    )
```



```{r}
# make tables of standardized rates

#----- stage 1 -----#

exp_rates_stage1_tab <- exp_stage1_df %>%
  select(-c(n_enrollee_years, n_admissions)) %>%
  spread(key = "race", value = "exp_rate_stage1") %>%
  mutate(sex = ifelse(sex == 1, "Male", "Female"),
         age_grp = ifelse(age_grp == "[65,75)", "65-74", age_grp),
         age_grp = ifelse(age_grp == "[75,85)", "75-84", age_grp),
         age_grp = ifelse(age_grp == ">85", "85+", age_grp),
         `1` = format(round(`1`, 3), nsmall = 3),
         `2` = format(round(`2`, 3), nsmall = 3)) %>%
  arrange(age_grp) %>%
  rename("Sex" = "sex",
         "Age group" = "age_grp",
         "Rate (White)" = "1",
         "Rate (Black)" = "2")
exp_rates_stage1_tab


#----- stage 2 -----#

exp_rates_stage2_tab <- exp_stage2_df %>%
  select(-c(n_enrollee_years, n_admissions)) %>%
  mutate(sex = ifelse(sex == 1, "Male", "Female"),
         age_grp = ifelse(age_grp == "[65,75)", "65-74", age_grp),
         age_grp = ifelse(age_grp == "[75,85)", "75-84", age_grp),
         age_grp = ifelse(age_grp == ">85", "85+", age_grp),
         exp_rate_stage2 = format(round(exp_rate_stage2, 3), nsmall = 3)) %>%
  arrange(age_grp) %>%
  rename("Sex" = "sex",
         "Age group" = "age_grp",
         "Rate (overall)" = "exp_rate_stage2")
exp_rates_stage2_tab


# join tables together (not saving right now)
exp_rates_tab <- left_join(exp_rates_stage1_tab, exp_rates_stage2_tab)


# save tables
write_rds(exp_rates_tab, 
          file = paste0("results/tables/intermediate/hosp_expected_rates.rds"))
# tables joined and written to tex in script 10
```

```{r}
## Aggregate over years ----
## Just tally up the number of person years and hospitalizations over all years
obs_df <- hosp_county_df %>%
    dplyr::group_by(county, race, sex, age_grp) %>% #county, race, sex, age_grp
    dplyr::summarize(n_enrollees = sum(n_enrollees),
                     n_admissions = sum(n_admissions), 
                     obs_rate = n_admissions / n_enrollees,
                     # HPI and PM2.5 are the same across all years
                     med_house_income = first(med_house_income),
                     house_price_income_ratio = first(house_price_income_ratio),
                     pm25 = mean(pm25))

## fill NAs
obs_df %>% 
  filter(n_enrollees == 0) 

obs_df$obs_rate[is.na(obs_df$obs_rate)] <- 0
```

```{r}
## Merge with exp_df ----
hosp_ratios_df <- obs_df %>%
    dplyr::left_join(exp_stage1_df %>%
                         dplyr::select(race, sex, age_grp, exp_rate_stage1),
                     by = c("race", "sex", "age_grp")) %>%
    dplyr::left_join(exp_stage2_df %>%
                         dplyr::select(sex, age_grp, exp_rate_stage2),
                     by = c("sex", "age_grp"))

## Now combine age/sex groups ----
hosp_ratios_df %<>% 
  mutate(
    expected_stage1 = n_enrollees * exp_rate_stage1, 
    expected_stage2 = n_enrollees * exp_rate_stage2,
    observed = n_admissions
  ) %>% 
  dplyr::group_by(county, race) %>%
  dplyr::summarize(
    person_years = sum(n_enrollees),
    expected_stage1 = sum(expected_stage1), 
    expected_stage2 = sum(expected_stage2), 
    observed = sum(observed),
    # HPI and PM2.5 are the same across all years --> just take mean
    med_house_income = mean(med_house_income),
    house_price_income_ratio = mean(house_price_income_ratio),
    pm25 = mean(pm25)) %>%
  dplyr::ungroup()
```


```{r}
# plot observed vs expected
hosp_ratios_df %>% 
  ggplot() + 
  geom_point(aes(x = observed, y = expected_stage2, color = as.factor(race)), alpha = 0.5) + 
  scale_x_sqrt() + 
  scale_y_sqrt()
```

```{r}
# counties with zero observed hospitalizations without ADRD
county_sf %>%
  left_join(hosp_ratios_df, by = "county") %>%
  mutate(zero_observed = (observed == 0)) %>%
  ggplot() + 
  geom_sf(aes(fill = zero_observed), alpha = 1, lwd = 0.0) + 
  facet_grid(~race)
```

```{r}
## Prep data ----
hosp_ratios_df %<>% 
  mutate(
    black = as.integer(if_else(race == 2, 1, 0)),
    # expected = as.integer(ceiling(expected)), # expected values don't need to be integers!
    observed = as.integer(round(observed)), # round normally (must be integers)
    # person_years = as.integer(round(person_years)), # doesn't need to be integers
    log_expected_stage1 = log(expected_stage1 + 0.00001), # to avoid issues with expected = 0
    log_expected_stage2 = log(expected_stage2 + 0.00001) # to avoid issues with expected = 0
  ) %>% 
  left_join(county_fips_df)

# sort by race and then county
hosp_ratios_df %<>%
  arrange(race, county)

# any missing values?
sum(is.na(hosp_ratios_df$c_idx))
sum(is.na(hosp_ratios_df$s_idx))
sum(is.na(hosp_ratios_df$observed))
sum(is.na(hosp_ratios_df$expected_stage1))
sum(is.na(hosp_ratios_df$expected_stage2))
sum(is.na(hosp_ratios_df$person_years))
```


```{r}
write_rds(hosp_ratios_df, "data/symlinks/scratch/hosp_ratios_df.rds")
```
