
```{r setup, include=FALSE}
## Set working directory as project root
library(here)
knitr::opts_knit$set(root.dir = here())
```

Description:
- Outcome: hospitalizations with or without ADRD (sex-age-dual standardized)
- Basic stats (for table 1) and visualizations
- National rates (used for expected counts)
- Observed and expected counts

```{r}
########## user input ########## 

# outcome (adrd or nonadrd)
#outcome <- "adrd"
outcome <- "nonadrd"
```

```{r, message=FALSE, warning=FALSE}
## Load libraries ----
library(tidyverse)
library(magrittr)
library(ggplot2)
library(sf)
library(RColorBrewer)
library(viridis)
library(ggthemes)
library(knitr)
library(kableExtra)
library(xtable)
```

```{r}
## Read data ----
county_df <- read_rds(paste0("data/symlinks/scratch/", outcome, "-dual_county_df.rds"))
county_sf <- read_rds("data/symlinks/scratch/county_sf.rds")
county_fips_df <- read_rds("data/symlinks/scratch/county_fips_df.rds")

length(unique(county_df$county))
length(unique(county_sf$county))
length(unique(county_fips_df$county))

counties_shp_ = unique(county_sf$county)
counties_ = unique(county_df$county)
counties_ = unique(county_fips_df$county)

setdiff(counties_shp_, counties_)
setdiff(counties_, counties_shp_)
setdiff(counties_, counties_shp_)
setdiff(counties_shp_, counties_)
```

```{r}
## Subset ----
##  Subset to population of interest --
county_df %<>%
    filter(age_grp %in% c("[65,75)", "[75,85)", ">85"))

##  Replace NA with 0 --
county_df$n_enrollees[is.na(county_df$n_enrollees)] <- 0 
county_df$n_admissions[is.na(county_df$n_admissions)] <- 0 

counties_shp_ = unique(county_sf$county)
counties_ = unique(county_df$county)

setdiff(counties_shp_, counties_)
setdiff(counties_, counties_shp_)
```

```{r}
# get basic stats from data (before rounding)

# total # of hospitalizations
sum(county_df$n_admissions)

# number of hospitalizations by race
county_df %>%
  group_by(race) %>%
  summarise(total_hosp = sum(n_admissions, na.rm = TRUE))
```

```{r}
# get sex, age, dual distribution of person-years for each race

# table with % of person-years in white vs. black for each stratum 
sex_age_dual_dist_tab <- county_df %>%
  group_by(race, sex, age_grp, dual) %>%
  summarise(total_py = sum(n_enrollees)) %>%
  group_by(sex, age_grp, dual) %>%
  mutate(pct_py = round(100 * total_py / sum(total_py), 1)) %>%
  mutate(total_pct_py = paste0(scales::comma(round(total_py, 0)), 
                               " (", pct_py, "\\%)")) %>%
  group_by(sex, age_grp, dual) %>%
  mutate(total_white_black_py = scales::comma(sum(total_py))) %>%
  select(-c(total_py, pct_py)) %>%
  spread(key = race, value = total_pct_py) %>%
  ungroup() %>%
  mutate(sex = ifelse(sex == 1, "Male", "Female"),
         age_grp = ifelse(age_grp == "[65,75)", "aged 65-74", age_grp),
         age_grp = ifelse(age_grp == "[75,85)", "aged 75-84", age_grp),
         age_grp = ifelse(age_grp == ">85", "aged 85+", age_grp),
         dual = ifelse(dual == 0, "Medicaid ineligible", "Medicaid eligible"),
         Stratum = paste0(sex, ", ", age_grp, ", ", dual)) %>%
  arrange(age_grp) %>%
  rename("White" = `1`,
         "Black" = `2`,
         "Total" = total_white_black_py) %>%
  select(c("Stratum", "White", "Black", "Total"))
sex_age_dual_dist_tab
```

```{r}
# simpler stats for new table 1

# overall
county_df %>%
  group_by(race) %>%
  summarise(py = sum(n_enrollees)) %>%
  mutate(py_pct = 100 * py/sum(py))

# sex (overall)
county_df %>%
  group_by(sex) %>%
  summarise(py = sum(n_enrollees)) %>%
  mutate(py_pct = 100 * py/sum(py))
# sex(by race)
county_df %>%
  group_by(race, sex) %>% 
  summarise(count = sum(n_enrollees), .groups = "drop") %>%
  group_by(race) %>%
  mutate(percent = 100 * count / sum(count)) %>%
  ungroup()

# dual (overall)
county_df %>%
  group_by(dual) %>%
  summarise(py = sum(n_enrollees)) %>%
  mutate(py_pct = 100 * py/sum(py))
# dual (by race)
county_df %>%
  group_by(race, dual) %>% 
  summarise(count = sum(n_enrollees), .groups = "drop") %>%
  group_by(race) %>%
  mutate(percent = 100 * count / sum(count)) %>%
  ungroup()

# age (overall)
county_df %>%
  group_by(age_grp) %>%
  summarise(py = sum(n_enrollees)) %>%
  mutate(py_pct = 100 * py/sum(py))
# age (by race)
county_df %>%
  group_by(race, age_grp) %>% 
  summarise(count = sum(n_enrollees), .groups = "drop") %>%
  group_by(race) %>%
  mutate(percent = 100 * count / sum(count)) %>%
  ungroup()

```


## Observed vs expected

We're using overall rates (ignoring race) to get expected counts, but we will still present race-specific rates in a table.

```{r}
# get race-specific national rates for each sex/age combination 
exp_race_specific <- county_df %>%
    dplyr::group_by(race, sex, age_grp, dual) %>% # race, sex, age_grp, dual
    dplyr::summarize(
        n_admissions = sum(n_admissions),
        n_enrollee_years = sum(n_enrollees),
        exp_rate = n_admissions / n_enrollee_years
    )

# get overall national rates for each sex/age combination 
exp_overall <- county_df %>%
    dplyr::group_by(sex, age_grp, dual) %>% # sex, age_grp, dual
    dplyr::summarize(
        n_admissions = sum(n_admissions),
        n_enrollee_years = sum(n_enrollees),
        exp_rate = n_admissions / n_enrollee_years
    )
```

```{r}
# make tables of standardized rates

#----- race-specific -----#

exp_race_specific_tab <- exp_race_specific %>%
  select(-c(n_enrollee_years, n_admissions)) %>%
  spread(key = "race", value = "exp_rate") %>%
  mutate(sex = ifelse(sex == 1, "Male", "Female"),
         age_grp = ifelse(age_grp == "[65,75)", "65-74", age_grp),
         age_grp = ifelse(age_grp == "[75,85)", "75-84", age_grp),
         age_grp = ifelse(age_grp == ">85", "85+", age_grp),
         `1` = format(round(`1`, 3), nsmall = 3),
         `2` = format(round(`2`, 3), nsmall = 3)) %>%
  arrange(age_grp) %>%
  rename("Sex" = "sex",
         "Age group" = "age_grp",
         "Rate (White)" = "1",
         "Rate (Black)" = "2")
exp_race_specific_tab


#----- overall (using these to get expected counts) -----#

exp_overall_tab <- exp_overall %>%
  select(-c(n_enrollee_years, n_admissions)) %>%
  mutate(sex = ifelse(sex == 1, "Male", "Female"),
         age_grp = ifelse(age_grp == "[65,75)", "65-74", age_grp),
         age_grp = ifelse(age_grp == "[75,85)", "75-84", age_grp),
         age_grp = ifelse(age_grp == ">85", "85+", age_grp),
         exp_rate = format(round(exp_rate, 3), nsmall = 3)) %>%
  arrange(age_grp) %>%
  rename("Sex" = "sex",
         "Age group" = "age_grp",
         "Rate (overall)" = "exp_rate")
exp_overall_tab


# join tables together
exp_rates_tab <- left_join(exp_race_specific_tab, exp_overall_tab)

# save tables
write_rds(exp_rates_tab, 
          file = paste0("results/tables/", outcome, "-dual_expected_rates.rds"))
```


```{r}
## Aggregate over years ----
## Just tally up the number of person years and hospitalizations over all years
obs_df <- county_df %>%
    dplyr::group_by(county, race, sex, age_grp, dual) %>% #county, race, sex, age_grp, dual
    dplyr::summarize(n_enrollees = sum(n_enrollees),
                     n_admissions = sum(n_admissions), 
                     obs_rate = n_admissions / n_enrollees,
                     # HPI and PM2.5 are the same across all years
                     med_house_income = first(med_house_income),
                     house_price_income_ratio = first(house_price_income_ratio),
                     pm25 = mean(pm25))

## fill NAs
obs_df %>% 
  filter(n_enrollees == 0) 

obs_df$obs_rate[is.na(obs_df$obs_rate)] <- 0
```

```{r}
# ## Merge with exp_df ----
# ratios_df <- obs_df %>%
#     dplyr::left_join(exp_stage1_df %>%
#                          dplyr::select(race, sex, age_grp, dual, exp_rate_stage1),
#                      by = c("race", "sex", "age_grp", "dual")) %>%
#     dplyr::left_join(exp_stage2_df %>%
#                          dplyr::select(sex, age_grp, dual, exp_rate_stage2),
#                      by = c("sex", "age_grp", "dual"))
# 
# ## Now aggregate age ----
# # here is where dual drops out!! along with age and sex
# 
# ratios_df %<>% 
#   mutate(
#     expected_stage1 = n_enrollees * exp_rate_stage1, 
#     expected_stage2 = n_enrollees * exp_rate_stage2,
#     observed = n_admissions
#   ) %>% 
#   dplyr::group_by(county, race) %>%
#   dplyr::summarize(
#     person_years = sum(n_enrollees),
#     expected_stage1 = sum(expected_stage1), 
#     expected_stage2 = sum(expected_stage2), 
#     observed = sum(observed),
#     # HPI and PM2.5 are the same across all years --> just take mean
#     med_house_income = mean(med_house_income),
#     house_price_income_ratio = mean(house_price_income_ratio),
#     pm25 = mean(pm25)) %>%
#   dplyr::ungroup()
```

```{r}
## Merge with exp_df ----
ratios_df <- obs_df %>%
    dplyr::left_join(exp_overall %>%
                         dplyr::select(sex, age_grp, dual, exp_rate),
                     by = c("sex", "age_grp", "dual"))

## Now aggregate age ----
# here is where dual drops out!! along with age and sex

ratios_df %<>% 
  mutate(
    expected = n_enrollees * exp_rate,
    observed = n_admissions
  ) %>% 
  dplyr::group_by(county, race) %>%
  dplyr::summarize(
    person_years = sum(n_enrollees),
    expected = sum(expected), 
    observed = sum(observed),
    # HPI and PM2.5 are the same across all years --> just take mean
    med_house_income = mean(med_house_income),
    house_price_income_ratio = mean(house_price_income_ratio),
    pm25 = mean(pm25)) %>%
  dplyr::ungroup()
```


```{r}
# plot observed vs expected
ratios_df %>% 
  ggplot() + 
  geom_point(aes(x = observed, y = expected, color = as.factor(race)), alpha = 0.5) + 
  scale_x_sqrt() + 
  scale_y_sqrt()
```

```{r}
## Prep data ----
ratios_df %<>% 
  mutate(
    black = as.integer(if_else(race == 2, 1, 0)),
    # expected = as.integer(ceiling(expected)), # expected values don't need to be integers!
    observed = as.integer(round(observed)), # round normally (must be integers)
    # person_years = as.integer(round(person_years)), # doesn't need to be integers
    log_expected = log(expected + 0.00001) # to avoid issues with expected = 0
  ) %>% 
  left_join(county_fips_df)

# sort by race and then county
ratios_df %<>%
  arrange(race, county)

# any missing values?
sum(is.na(ratios_df$c_idx))
sum(is.na(ratios_df$s_idx))
sum(is.na(ratios_df$observed))
sum(is.na(ratios_df$expected))
sum(is.na(ratios_df$person_years))
```

```{r}
write_rds(ratios_df, paste0("data/symlinks/scratch/", outcome, "-dual_ratios_df.rds"))
```
