
```{r, message=FALSE, warning=FALSE}
## load packages ----
library(tidyverse)
library(magrittr)
```

```{r}
####
# Download adjacency
####

## Import data ----
county_adj_df <- readr::read_delim(
    '../data/input/local/county_adjacency.txt',
    delim = "\t",
    escape_double = FALSE,
    col_names = c("name_i", "fips_i",
                  "name_j", "fips_j"),
    trim_ws = TRUE
)

county_adj_df
```

```{r}
## Forward fill ----
county_adj_df <- zoo::na.locf(county_adj_df)

## Remove self loops and add state fips ----
county_adj_df <- county_adj_df %>%
    dplyr::filter(fips_i != fips_j) %>%
    dplyr::mutate(state_i = substr(fips_i, 1, 2),
                  state_j = substr(fips_j, 1, 2))

## Fix FIPS ----
## Bedford City got lumped together with Bedford county in CMF data
county_adj_df <- county_adj_df %>%
    dplyr::filter(fips_i != "51515",
                  fips_j != "51515")

## Now remove states/territories we won't use ----
county_adj_df <- dplyr::filter(county_adj_df,
                                  state_i %in% c("37"),
                                  state_j %in% c("37"))

county_adj_df
```

```{r}
####
# Create IDs and dummies
####

## Adding dummy FIPS ----
add_dummy_county_ids <- function(county_adj_df) {
  ## Just returns a County Adjacency matrix with two new columns -- each
  ## representing a dummy variable from 1:n_counties
  
  ## Sort by FIPS
  new_adj <- dplyr::arrange(county_adj_df, fips_i, fips_j)
  
  ## Make a dummy dictionary that with FIPS as the key and a dummy as value.
  dummies <- as.list(1:length(unique(new_adj$fips_i)))
  names(dummies) <- unique(new_adj$fips_i)
  
  ## Then make a dummy for node_i and node_j
  new_adj$dummy_i <-
    unlist(dummies[new_adj$fips_i], use.names = FALSE)
  new_adj$dummy_j <-
    unlist(dummies[new_adj$fips_j], use.names = FALSE)
  
  return(new_adj)
}

add_dummy_state_ids <- function(county_adj_df) {
  ## Just returns a County Adjacency matrix with two new columns -- each
  ## representing a dummy variable from 1:n_states
  
  ## Sort by FIPS
  new_adj <- dplyr::arrange(county_adj_df, fips_i, fips_j)
  
  ## Make a dummy dictionary that with FIPS as the key and a dummy as value.
  dummies <- as.list(1:length(unique(new_adj$state_i)))
  names(dummies) <- unique(new_adj$state_i)
  
  ## Then make a dummy for node_i and node_j
  new_adj$dummy_state_i <-
    unlist(dummies[new_adj$state_i], use.names = FALSE)
  new_adj$dummy_state_j <-
    unlist(dummies[new_adj$state_j], use.names = FALSE)
  
  return(new_adj)
}

county_adj_df <- add_dummy_county_ids(county_adj_df)
county_adj_df <- add_dummy_state_ids(county_adj_df)

county_adj_df
```

```{r}
####
# Explode as n_counties x n_counties matrix
####

make_county_adj_matrix <- function(county_adj_df) {
    ## Converts a County Adjacency dataframe into a traditional adjacency matrix
    ## of size n_counties x n_counties with 1 representing neighbors.
    
    ## Number of neighbors
    num <- county_adj_df %>%
        dplyr::group_by(dummy_i) %>%
        dplyr::summarize(neighbors_i = dplyr::n()) %>%
        dplyr::pull(neighbors_i)
    
    ## List of neighbors
    adj <- county_adj_df$dummy_j
    
    ## Create an appropriately sized matrix
    n_nodes <- length(num)
    A <- matrix(0L, nrow = n_nodes, ncol = n_nodes)
    
    ## Loop through num and adj and assign 1 to neighbors
    start_ix <- end_ix <- 0
    for (node in seq_along(num)) {
        for (n_neigh in num[node]) {
            start_ix  <- end_ix + 1
            end_ix    <- end_ix + n_neigh
            
            neighbors <- adj[start_ix:end_ix]
            
            A[node, neighbors] <- 1L
        }
    }
    return(A)
}

county_adj_matrix <- make_county_adj_matrix(county_adj_df)

county_adj_matrix[1:10, 1:10]
```

```{r}
####
# Make sparse
####

make_county_adj_sparse_list <- function(adj_matrix) {
  ## This is taken from mbjoseph CARstan repo -- returns a sparse
  ## representation of an adjacency matrix in the format that Stan needs
  ## Number of neighbors
  D_sparse <- rowSums(adj_matrix)
  
  ## Kyle Foreman script -- undirected graph so second line removes dupes
  W_sparse <- which(adj_matrix == 1, arr.ind = TRUE)
  W_sparse <- W_sparse[W_sparse[, 1] < W_sparse[, 2], ]
  
  ## Get eigenvalues of D^(-.5) * W * D^(-.5) for determinant computations
  invsqrtD <- diag(1 / sqrt(D_sparse))
  quadformDAD <- invsqrtD %*% adj_matrix %*% invsqrtD
  lambdas <- eigen(quadformDAD)$values
  
  ## Number of edges
  W_n <- nrow(W_sparse)
  
  return(list(
    D_sparse = D_sparse,
    W_sparse = W_sparse,
    lambdas = lambdas,
    W_n = W_n
  ))
}

## Save a sparse adjacency representation (for Stan) ----
county_adj_sparse_list <- make_county_adj_sparse_list(county_adj_matrix)
names(county_adj_sparse_list)
```

```{r}
####
# Obtain a table of county IDs
####

## Save a unique mapping of FIPS to state and county dummy codes ----
county_fips_df <- county_adj_df %>%
    dplyr::select(
        county_name = name_i,
        fipschar = fips_i,
        fips_st = state_i,
        c_idx = dummy_i,
        s_idx = dummy_state_i
    ) %>%
    dplyr::distinct() %>%
    dplyr::mutate(st_abbr = unlist(lapply(strsplit(county_name, split = ", "),
                                          function(x)
                                              x[[2]])))
county_fips_df
```

```{r}
write_rds(county_adj_df, "../data/intermediate/county_adj_df.rds")
write_rds(county_adj_sparse_list, "../data/intermediate/county_adj_sparse_list.rds")
write_rds(county_fips_df, "../data/intermediate/county_fips_df.rds")
```

