
```{r setup, include=FALSE}
## Set working directory as project root
library(here)
knitr::opts_knit$set(root.dir = here())
```

```{r, message=FALSE, warning=FALSE}
## Load libraries ----
library(tidyverse)
library(magrittr)
library(bayesplot)
library(rstan)
```

```{r}
# path with model results
# results_path <- "adrd/m1/model_run_20240307"
#results_path <- "adrd/m2/model_run_20240307"
#results_path <- "adrd/m3/model_run_20240308"
results_path <- "hosp/m2/model_run_20240315"


# load stan object
stanfit_object <- read_rds(paste0("results/models/", results_path, "/stanfit_object.rds"))

# ## Read data ----
# #slurm job number 1307317 for m0 is labeled model_run_20230311_185502
# # stanfit_object <- read_rds("results/models/adrd/m1/model_run_20231109_142035/stanfit_object.rds")
# 
# # stanfit_object1 <- read_rds("results/models/adrd/m1/model_run_20240123_162901/stanfit_object.rds")
# # 
# # stanfit_object2 <- read_rds("results/models/adrd/m1/model_run_20240123_161610/stanfit_object.rds")
# 
# # this is the one with 10,000 iterations
# stanfit_object <- read_rds("results/models/adrd/m1/model_run_20240131_220929/stanfit_object.rds")
# 
# # just looking at another model
# stanfit_object <- read_rds("results/models/adrd/m1/model_run_20240131_215726/stanfit_object.rds")
# # convergence is way better even with fewer iterations!! check parameters
# 
# # try the only m4 that finished running
# stanfit_object <- read_rds("results/models/adrd/m4/model_run_20240130_162455/stanfit_object.rds")
# 
# # try single chain from m2 that finished running with array
# stanfit_object <- read_rds("results/models/adrd/m2/old/model_run_20240209_15/stanfit_object_3.rds")
# 
# 
# #------- all four chains actually finished running for m2!!
# # folder with results
# folder_path <- "results/models/adrd/m2/model_run_20240212_2204/"
# # Create a list of the four model fit objects
# stanfit_list <- list(
#   read_rds(paste0(folder_path, "stanfit_object_1.rds")),
#   read_rds(paste0(folder_path, "stanfit_object_2.rds")),
#   read_rds(paste0(folder_path, "stanfit_object_3.rds")),
#   read_rds(paste0(folder_path, "stanfit_object_4.rds"))
# )
# 
# # Convert the list of model fits to a stan fit object
# stanfit_object <- sflist2stanfit(stanfit_list)
# # save for scripts 5 and 6
# save(stanfit_object, file = paste0(folder_path, "stanfit_object.rds"))
# 
# 
# #------- 8 chains
# # folder with results
# folder_path <- "results/models/adrd/m2/model_run_20240216_1406/"
# # Create a list of the four model fit objects
# stanfit_list <- list(
#   read_rds(paste0(folder_path, "stanfit_object_1.rds")),
#   read_rds(paste0(folder_path, "stanfit_object_2.rds")),
#   read_rds(paste0(folder_path, "stanfit_object_3.rds")),
#   read_rds(paste0(folder_path, "stanfit_object_4.rds")),
#   read_rds(paste0(folder_path, "stanfit_object_5.rds")),
#   read_rds(paste0(folder_path, "stanfit_object_6.rds")),
#   read_rds(paste0(folder_path, "stanfit_object_7.rds")),
#   read_rds(paste0(folder_path, "stanfit_object_8.rds"))
# )
# 
# # Convert the list of model fits to a stan fit object
# stanfit_object <- sflist2stanfit(stanfit_list)
# # save for scripts 5 and 6
# write_rds(stanfit_object, file = paste0(folder_path, "stanfit_object.rds"))
# 
# 
# #------- weak prior
# # folder with results
# folder_path <- "results/models/adrd/m2/model_run_20240220_2054/"
# # Create a list of the four model fit objects
# stanfit_list <- list(
#   read_rds(paste0(folder_path, "stanfit_object_2.rds")),
#   read_rds(paste0(folder_path, "stanfit_object_3.rds")),
#   read_rds(paste0(folder_path, "stanfit_object_5.rds"))
# )
# 
# 
# 
# #------ first attempt at all-cause hosp!
# # folder with results
# folder_path <- "results/models/hosp/m2/"
# # Create a list of the four model fit objects
# stanfit_list <- list(
#   read_rds(paste0(folder_path, "model_run_20240229_1532/stanfit_object_1.rds"))
# )
# 
# 
# 
# # Convert the list of model fits to a stan fit object
# stanfit_object <- sflist2stanfit(stanfit_list)
# # save for scripts 5 and 6
# write_rds(stanfit_object, file = paste0(folder_path, "stanfit_object.rds"))
```

```{r}
list_of_draws <- rstan::extract(stanfit_object)
print(names(list_of_draws))
```

```{r}
rhat_of_draws <- rhat(stanfit_object)
mcmc_rhat(rhat_of_draws)
```

```{r}
names(rhat_of_draws)[1:100]

# what % of parameters have R < 1.10?
length(rhat_of_draws[rhat_of_draws < 1.10]) / length(rhat_of_draws)
```

```{r}
rhat_of_draws[c('alpha[1]', # white surface intercept
                'alpha[2]', # black surface intercept
                'beta[1]',
                'beta[2]',
                'delta', # shared surface scaling factor
                'nu[1]', # state random effect
                'lp__') # Stan's lp__ variable
              ] 
```

```{r}
rhat_of_draws[c('sigma_u[1]', # SD of CAR part
                'sigma_u[2]', # SD of CAR part
                'sigma_u[3]', # SD of CAR part
                'sigma_v[1]', # SD of iid spatial part
                'sigma_v[2]', # SD of iid spatial part
                'sigma_v[3]', # SD of iid spatial part
                'sigma_s', # SD of state random effect
                'tau_u[1]', # precision of CAR part
                'tau_u[2]', # precision of CAR part
                'tau_u[3]', # precision of CAR part
                'tau_v[1]', # precision of iid spatial part
                'tau_v[2]', # precision of iid spatial part
                'tau_v[3]' # precision of iid spatial part
                )
              ]
```

```{r}
# phi
mcmc_rhat(rhat_of_draws[grep('phi', names(rhat_of_draws))])
```

```{r}
# psi
mcmc_rhat(rhat_of_draws[grep('psi\\[1', names(rhat_of_draws))])
```

```{r}
# psi
mcmc_rhat(rhat_of_draws[grep('psi\\[2', names(rhat_of_draws))])
```

```{r}
# nu
mcmc_rhat(rhat_of_draws[grep('nu', names(rhat_of_draws))])
```

```{r}
# beta
mcmc_rhat(rhat_of_draws[grep('beta', names(rhat_of_draws))])
```



#### Lauren experimenting

```{r}
# try some trace plots
mcmc_trace(stanfit_object, pars = "alpha[1]")
mcmc_trace(stanfit_object, pars = "delta")
mcmc_trace(stanfit_object, pars = "psi[1,62]")

# now try trace plots specifically for variables with high Rhat values

# get high rhat vars
high_rhat <- rhat_of_draws[order(desc(rhat_of_draws))[1:50]]

mcmc_trace(stanfit_object, pars = "sigma_v[3]")
mcmc_trace(stanfit_object, pars = "sigma_v[2]")
mcmc_trace(stanfit_object, pars = "lp__")
mcmc_trace(stanfit_object, pars = "tau_v[2]")


```


```{r}
# Get summary information, including effective sample size
summary_info <- summary(stanfit_object)

# Extract the effective sample size for each parameter 
ess <- summary_info$summary[, "n_eff"]
hist(ess)

# aim for min to be around 1,000
```

