
```{r setup, include=FALSE}
## Set working directory as project root
library(here)
knitr::opts_knit$set(root.dir = here())
```

```{r, message=FALSE, warning=FALSE}
## Load libraries ----
library(tidyverse)
library(magrittr)
library(rstan)
```

```{r}
# choose model
model <- "m1"

#slurm job number 1307317 for m0 is labeled model_run_20230311_185502
if(model == "m1"){
  stanfit_object <- read_rds(paste0(
    "results/models/adrd/m1/model_run_20231109_142035/stanfit_object.rds"
    ))
} else if(model == "m2"){
  stanfit_object <- read_rds(paste0(
    "results/models/adrd/m2/model_run_*/stanfit_object.rds"
    ))
} else if(model == "m3"){
  stanfit_object <- read_rds(paste0(
    "results/models/adrd/m3/model_run_*/stanfit_object.rds"
    ))
} else if(model == "m4"){
  stanfit_object <- read_rds(paste0(
    "results/models/adrd/m4/model_run_*/stanfit_object.rds"
    ))
}

class(stanfit_object)
```


```{r}
## Read data ----
adrd_ratios_df <- read_rds('data/symlinks/scratch/adrd_ratios_df.rds')
adrd_ratios_df
```

```{r}
county_fips_df <- read_rds("data/symlinks/scratch/county_fips_df.rds")
county_fips_df
```

```{r}
stanfit_summary <- summary(stanfit_object)
## summary stats of fixed effects ----
stanfit_summary$summary[c('alpha[1]', 'alpha[2]', 'delta'), ]
```

```{r}
## Define functions ----
extract_samples <- function(stanfit) {
    ## Extract samples from a stanfit object and return a list of variables
    ## NOTE: Random effects will be matrices of dimensions iterations x areas
    ##       while the fixed effects will just be columns of length iterations
    
    ## Extract the samples of fixed effects from stan_fit object
    fixed_pars <- stanfit@model_pars[grepl(stanfit@model_pars,
                                           pattern = "alpha|beta|delta|sigma")]
    x <- as.matrix(stanfit, pars = fixed_pars)
    
    ## Get a list of the names and make them prettier
    var_names <-
        gsub(x = colnames(x),
             pattern = "\\[|\\]",
             replacement = "")
    
    ## Turn the named matrix into a list of vectors
    x <- split(x, c(col(x)))
    
    ## Put back in the variable names
    names(x) <- var_names
    
    ## Now extract the random effects and attach the random effects
    random_pars <- stanfit@model_pars[grepl(stanfit@model_pars,
                                            pattern = "nu|psi|phi")]
    r_effs <- as.matrix(stanfit, pars = random_pars)
    x$psi1 <- r_effs[, grep(x = colnames(r_effs),
                            pattern = 'psi[1',
                            fixed = TRUE)]
    x$psi2 <- r_effs[, grep(x = colnames(r_effs),
                            pattern = 'psi[2',
                            fixed = TRUE)]
    x$phi  <- r_effs[, grep(x = colnames(r_effs),
                            pattern = 'phi',
                            fixed = TRUE)]
    x$nu   <- r_effs[, grep(x = colnames(r_effs),
                            pattern = 'nu',
                            fixed = TRUE)]
    
    return(x)
}
```

```{r}
## organize samples from stanfit_object ----
stanfit_samples <- extract_samples(stanfit_object)

names(stanfit_samples)
length(stanfit_samples$alpha1)
dim(stanfit_samples$phi)
dim(stanfit_samples$nu)
```

# log relative risk

```{r}
## obtain posterior predictive values ----
## Make a version of nu that is expanded such that every state column
## repeats as many times as their are counties. Then we can just add
## the expanded matrix when calculating posterior quantities.
nu_counts <- county_fips_df %>%
    dplyr::group_by(s_idx) %>%
    dplyr::summarize(count = dplyr::n()) %>%
    dplyr::mutate(c_sum = cumsum(count))

## Initialize a holder
nu_expanded <- matrix(NA,
                      nrow = nrow(stanfit_samples$psi1),
                      ncol = max(nu_counts$c_sum))

for (s in 1:nrow(nu_counts)) {
    start_ix <- ifelse(length(nu_counts$c_sum[s - 1]) > 0,
                       nu_counts$c_sum[s - 1], 0) + 1
    end_ix <- nu_counts$c_sum[s]
    
    nu_expanded[, start_ix:end_ix] <- stanfit_samples$nu[, s]
}

# white log relative risk
posterior_white <- stanfit_samples$alpha1 + stanfit_samples$psi1 + 
  (stanfit_samples$phi * stanfit_samples$delta) + 
  nu_expanded

# black log relative risk
posterior_black <- stanfit_samples$alpha2 + stanfit_samples$psi2 +
            (stanfit_samples$phi / stanfit_samples$delta) +
            nu_expanded

dim(posterior_white)
dim(posterior_white)
```

```{r}
# risk ratios
posterior_risk_ratio <- exp(posterior_black - posterior_white)

pos_med_rr <- data.frame(
  risk_ratio = matrixStats::colMedians(posterior_risk_ratio),
  c_idx = 1:ncol(posterior_risk_ratio)
)

# which columns (counties) have risk ratios significantly different from 1?
pos_med_rr$risk_ratio_sig <- (colMeans(posterior_risk_ratio > 1) > 0.8) | (colMeans(posterior_risk_ratio < 1) > 0.8)

```


```{r}
# posterior median log relative risk
pos_med <- rbind(
  tibble(
    pos_med_y = matrixStats::colMedians(posterior_white), 
    race = 1, 
    c_idx = 1:ncol(posterior_white)), 
  tibble(
    pos_med_y = matrixStats::colMedians(posterior_black), 
    race = 2, 
    c_idx = 1:ncol(posterior_black))
)

pos_med %>% 
  mutate(race = as.character(race)) %>% 
  ggplot() + 
  geom_density(aes(x = pos_med_y, color = race), linewidth = 1) + 
  theme_classic()
```

```{r}
# join pos_med and pos_med_rr
pos_med <- pos_med %>%
  dplyr::left_join(pos_med_rr, by = c("c_idx"))
```


```{r}
## Add in correct fipschar ----
pos_med <- adrd_ratios_df %>%
  mutate(y = log(observed) - log(expected)) %>% 
  dplyr::left_join(pos_med, by = c("c_idx", "race"))

pos_med %>% 
  ggplot() +
  geom_point(aes(x = y, y = pos_med_y, col = as.factor(race)))
```

## Decompose log ratios

```{r}
summary(stanfit_samples$delta)
```


```{r}
shared_w <- (stanfit_samples$phi * stanfit_samples$delta)
shared_b <- (stanfit_samples$phi / stanfit_samples$delta)

# posterior median
shared <- rbind(
  tibble(
    shared = matrixStats::colMedians(shared_w), 
    shared_unscaled = matrixStats::colMedians(stanfit_samples$phi), 
    race = 1, 
    c_idx = 1:ncol(shared_w)), 
  tibble(
    shared = matrixStats::colMedians(shared_b), 
    shared_unscaled = matrixStats::colMedians(stanfit_samples$phi), 
    race = 2, 
    c_idx = 1:ncol(shared_b))
)

# is exp(shared) (phi*delta for white, phi/delta for black) for each country for each race sig diff from 1?
# note: delta is same for white and black in a give county, shared_sig will be the same for white and black in a given county
phi_delta_sig <- rbind(
  tibble(
    race = 1,  
    shared_sig = 
      (colMeans(exp(shared_w) > 1) > 0.8) | 
      (colMeans(exp(shared_w) < 1) > 0.8),
    c_idx = 1:ncol(shared_w)),
  tibble(
    race = 2,  
    shared_sig = 
      (colMeans(exp(shared_b) > 1) > 0.8) | 
      (colMeans(exp(shared_b) < 1) > 0.8),
    c_idx = 1:ncol(shared_b))
)

# is exp(phi) (shared, unscaled) for each county significantly different from 1?
# (this is how significance is defined in figure 2 caption)
phi_sig <- data.frame(
    shared_unscaled_sig = 
      (colMeans(exp(stanfit_samples$phi) > 1) > 0.8) | 
      (colMeans(exp(stanfit_samples$phi) < 1) > 0.8),
    c_idx = 1:ncol(stanfit_samples$phi)
)

# Join sig columns
shared %<>% 
  dplyr::left_join(phi_delta_sig, by = c("c_idx", "race")) %>%
  dplyr::left_join(phi_sig, by = c("c_idx"))

## Add in correct fipschar ----
pos_med %<>% 
  dplyr::left_join(shared, by = c("c_idx", "race"))

shared %>% 
  mutate(race = as.character(race)) %>% 
  ggplot() + 
  geom_density(aes(x = shared_unscaled), size = 1) + 
  geom_density(aes(x = shared, color = race), size = 1) + 
  theme_classic()
```

```{r}
specific_w <- stanfit_samples$psi1
specific_b <- stanfit_samples$psi2

# posterior median
specific <- rbind(
  tibble(
    specific = matrixStats::colMedians(specific_w), 
    race = 1, 
    c_idx = 1:ncol(specific_w)), 
  tibble(
    specific = matrixStats::colMedians(specific_b), 
    race = 2, 
    c_idx = 1:ncol(specific_b))
)

# is exp(psi) for each county for each race significantly different from 1?
# (this is how significance is defined in figure 2 caption)
psi_sig <- rbind(
  tibble(
    race = 1,  
    specific_sig = 
      (colMeans(exp(specific_w) > 1) > 0.8) | 
      (colMeans(exp(specific_w) < 1) > 0.8),
    c_idx = 1:ncol(specific_w)),
  tibble(
    race = 2,  
    specific_sig = 
      (colMeans(exp(specific_b) > 1) > 0.8) | 
      (colMeans(exp(specific_b) < 1) > 0.8),
    c_idx = 1:ncol(specific_b))
)

# Join sig column
specific %<>% 
  dplyr::left_join(psi_sig, by = c("c_idx", "race"))

## Add in correct fipschar ----
pos_med %<>% 
  dplyr::left_join(specific, by = c("c_idx", "race"))

specific %>% 
  mutate(race = as.character(race)) %>% 
  ggplot() + 
  geom_density(aes(x = specific, color = race), size = 1) + 
  theme_classic()
```


## Empirical variance

```{r}



```



```{r}
# report distribution of county-level relative risks (exp(pos_med_y) which is exp(log lambda))

#----- for white people:

lambda_w <- pos_med |>
  filter(race == 1) |>
  pull(pos_med_y) |>
  exp()

# get min, max, median
min(lambda_w)
median(lambda_w)
max(lambda_w)

# get 5th and 95th percentiles
quantile(lambda_w, c(0.05, 0.95))
# relative risk at 95th percentile is 3.0 times higher than at 5th percentile


#----- for Black people:

lambda_b <- pos_med |>
  filter(race == 2) |>
  pull(pos_med_y) |>
  exp()

# get min, max, median
min(lambda_b)
median(lambda_b)
max(lambda_b)

# get 5th and 95th percentiles
quantile(lambda_b, c(0.05, 0.95))
# relative risk at 95th percentile is 3.1 times higher than at 5th percentile
```

```{r}
# report distribution of county-level risk ratios

min(pos_med$risk_ratio)
median(pos_med$risk_ratio)
max(pos_med$risk_ratio)
```

```{r}
write_rds(pos_med, paste0("data/intermediate/adrd-", model, "_pos_med.rds"))
write_rds(stanfit_samples, paste0("data/intermediate/adrd-", model, "_stanfit_samples.rds"))
write_rds(stanfit_summary, paste0("data/intermediate/adrd-", model, "_stanfit_summary.rds"))
```
