
```{r, message=FALSE, warning=FALSE}
## Load libraries ----
library(tidyverse)
library(magrittr)
library(sf)
library(cowplot)
library(RColorBrewer)
```

```{r}
## Read data ----
pos_med <- read_rds('../data/intermediate/pos_med.rds')
county_sf <- read_sf("../data/input/local/tl_2022_us_county/tl_2022_us_county.shp")

dim(county_sf)
names(county_sf)
```

## Observed vs Predicted

### log ratios (y)

```{r}
pos_med_sf <- county_sf %>% 
  mutate(
    county = as.integer(GEOID)
  ) %>% 
  select(county) %>% 
  right_join(pos_med)

pos_med_sf %>% 
  mutate(
    res = y - pos_med_y,
    res_is_out = if_else(abs(res) > 2/3, 1, 0) 
  ) %>% 
  ggplot() +
  geom_sf(aes(fill = exp(y), col = as.factor(res_is_out)), lwd = 0.2) +
  facet_grid(~race) +
  theme(legend.position = "bottom")
```

### posterior median log ratios (pos_med_y)

In this model the "prediction" is a smoothed version of the observed.

```{r}
pos_med_sf %>% 
  mutate(
    res = y - pos_med_y,
    res_is_out = if_else(abs(res) > 2/3, 1, 0) 
  ) %>% 
  ggplot() +
  geom_sf(aes(fill = exp(pos_med_y), col = as.factor(res_is_out)), lwd = 0.2) +
  facet_grid(~race) +
  theme(legend.position = "bottom")
```

## Risk decomposition

## shared unscaled

```{r}
shared_ <- c(pos_med$shared_unscaled, pos_med$specific)
myPalette <- colorRampPalette(rev(RColorBrewer::brewer.pal(11, "Spectral")))
sc <- scale_fill_gradientn(colors = myPalette(100), 
                           limits = c(min(shared_), max(shared_)))

p1 <- pos_med_sf %>% 
  filter(race == 1) %>% 
  ggplot() +
  geom_sf(aes(fill = specific), lwd = 0.2) + 
  theme_map() +
  labs(subtitle = "white specific") + 
  theme(legend.title = element_blank()) + 
  sc

p2 <- pos_med_sf %>% 
  filter(race == 1) %>% #shared_unscaled is non-race specific
  ggplot() +
  geom_sf(aes(fill = shared_unscaled), lwd = 0.2) + 
  theme_map() + 
  labs(subtitle = "shared unscaled") + 
  sc

p3 <- pos_med_sf %>% 
  filter(race == 2) %>% 
  ggplot() +
  geom_sf(aes(fill = specific), lwd = 0.2) + 
  theme_map() + 
  labs(subtitle = "black specific") +
  sc
  
p <- cowplot::plot_grid(
  p1 + theme(legend.position = "none"), 
  p2 + theme(legend.position = "none"), 
  p3  + theme(legend.position = "none"),
  nrow = 3)

cowplot::plot_grid(
  p, 
  cowplot::get_legend(p1), 
  ncol = 2
)
```

## shared unscaled

```{r}
shared_ <- c(pos_med$shared, pos_med$specific)
myPalette <- colorRampPalette(rev(RColorBrewer::brewer.pal(11, "Spectral")))
sc <- scale_fill_gradientn(colors = myPalette(100), 
                           limits = c(min(shared_), max(shared_)))

p1 <- pos_med_sf %>% 
  filter(race == 1) %>% 
  ggplot() +
  geom_sf(aes(fill = specific), lwd = 0.2) + 
  theme_map() +
  labs(subtitle = "white specific") + 
  theme(legend.title = element_blank()) + 
  sc

p2 <- pos_med_sf %>% 
  filter(race == 1) %>% #shared_unscaled is non-race specific
  ggplot() +
  geom_sf(aes(fill = shared), lwd = 0.2) + 
  theme_map() + 
  labs(subtitle = "shared white") + 
  sc

p3 <- pos_med_sf %>% 
  filter(race == 2) %>% #shared_unscaled is non-race specific
  ggplot() +
  geom_sf(aes(fill = shared), lwd = 0.2) + 
  theme_map() + 
  labs(subtitle = "shared black") + 
  sc

p4 <- pos_med_sf %>% 
  filter(race == 2) %>% 
  ggplot() +
  geom_sf(aes(fill = specific), lwd = 0.2) + 
  theme_map() + 
  labs(subtitle = "black specific") +
  sc
  
p <- cowplot::plot_grid(
  p1 + theme(legend.position = "none"), 
  p2 + theme(legend.position = "none"), 
  p3  + theme(legend.position = "none"),
  p4  + theme(legend.position = "none"),
  nrow = 4)

cowplot::plot_grid(
  p, 
  cowplot::get_legend(p1), 
  ncol = 2
)
```
