
```{r, message=FALSE, warning=FALSE}
## Load libraries ----
library(tidyverse)
library(magrittr)
library(rstan)
```

```{r}
## Read data ----
adrd_rates_df <- read_rds('../data/intermediate/adrd_ratios_df_.rds')
county_fips_df <- read_rds('../data/intermediate/county_fips_df_.rds')

adrd_rates_df %<>%  
  left_join(
    county_fips_df %>% 
      mutate(county = as.integer(fipschar))
  )

stanfit_object <- read_rds("./models/model_run_20230211_075658/stanfit_object.rds")

class(stanfit_object)
```

```{r}
## Define functions ----
extract_samples <- function(stanfit) {
    ## Extract samples from a stanfit object and return a list of variables
    ## NOTE: Random effects will be matrices of dimensions iterations x areas
    ##       while the fixed effects will just be columns of length iterations
    
    ## Extract the samples of fixed effects from stan_fit object
    fixed_pars <- stanfit@model_pars[grepl(stanfit@model_pars,
                                           pattern = "alpha|beta|delta|sigma")]
    x <- as.matrix(stanfit, pars = fixed_pars)
    
    ## Get a list of the names and make them prettier
    var_names <-
        gsub(x = colnames(x),
             pattern = "\\[|\\]",
             replacement = "")
    
    ## Turn the named matrix into a list of vectors
    x <- split(x, c(col(x)))
    
    ## Put back in the variable names
    names(x) <- var_names
    
    ## Now extract the random effects and attach the random effects
    random_pars <- stanfit@model_pars[grepl(stanfit@model_pars,
                                            pattern = "nu|psi|phi")]
    r_effs <- as.matrix(stanfit, pars = random_pars)
    x$psi1 <- r_effs[, grep(x = colnames(r_effs),
                            pattern = 'psi[1',
                            fixed = TRUE)]
    x$psi2 <- r_effs[, grep(x = colnames(r_effs),
                            pattern = 'psi[2',
                            fixed = TRUE)]
    x$phi  <- r_effs[, grep(x = colnames(r_effs),
                            pattern = 'phi',
                            fixed = TRUE)]
    x$nu   <- r_effs[, grep(x = colnames(r_effs),
                            pattern = 'nu',
                            fixed = TRUE)]
    
    return(x)
}
```

```{r}
## organize samples from stanfit_object ----
stanfit_samples <- extract_samples(stanfit_object)

names(stanfit_samples)
length(stanfit_samples$alpha1)
dim(stanfit_samples$phi)
```

```{r}
dim(stanfit_samples$nu)
```

```{r}
apply(stanfit_samples$nu, 2, summary)
```

```{r}
summary(stanfit_samples$alpha1)
sd(stanfit_samples$alpha1)
summary(stanfit_samples$alpha2)
sd(stanfit_samples$alpha2)
summary(stanfit_samples$delta)
```


```{r}
state_effects <- county_fips_df %>% 
  distinct(s_idx, st_abbr)

state_effects$effect <- apply(stanfit_samples$nu, 2, median)

state_effects %>% 
  arrange(effect)
```


# log ratios

```{r}
## obtain posterior predictive values ----
## Make a version of nu that is expanded such that every state column
## repeats as many times as their are counties. Then we can just add
## the expanded matrix when calculating posterior quantities.
## Prep data ----
adrd_ratios_df <- adrd_rates_df %>% 
  mutate(
    black = as.integer(if_else(race == 2, 1, 0)),
    expected = as.integer(ceiling(expected)) + 1, 
    observed = as.integer(ceiling(observed)) + 1
  ) %>% 
  left_join(
    county_fips_df %>% 
      mutate(county = as.integer(fipschar))
  )

## validate no NA ----
#summary(log(adrd_ratios_df$expected))
#summary(log(adrd_ratios_df$observed))
adrd_ratios_df <- adrd_ratios_df[!is.na(adrd_ratios_df$c_idx), ]
adrd_ratios_df <- adrd_ratios_df[adrd_ratios_df$s_idx != 52, ]

nu_counts <- adrd_ratios_df %>%
  dplyr::filter(race == 1) %>% 
    dplyr::group_by(s_idx, st_abbr) %>%
    dplyr::summarize(count = dplyr::n())

nu_counts$c_sum <- cumsum(nu_counts$count)

nu_counts
```

```{r}
## Initialize a holder
nu_expanded <- matrix(NA,
                      nrow = nrow(stanfit_samples$psi1),
                      ncol = max(nu_counts$c_sum))

for (s in 1:nrow(nu_counts)) {
    start_ix <- ifelse(length(nu_counts$c_sum[s - 1]) > 0,
                       nu_counts$c_sum[s - 1], 0) + 1
    end_ix <- nu_counts$c_sum[s]
    
    nu_expanded[, start_ix:end_ix] <- stanfit_samples$nu[, s]
}

# white log ratios
posterior_white <- stanfit_samples$alpha1 + stanfit_samples$psi1 + 
  (stanfit_samples$phi * stanfit_samples$delta) + 
  nu_expanded

# black log ratios
posterior_black <- stanfit_samples$alpha2 + stanfit_samples$psi2 +
            (stanfit_samples$phi / stanfit_samples$delta) +
            nu_expanded

dim(posterior_white)
dim(posterior_white)
```

```{r}
# posterior median log ratios
pos_med <- rbind(
  tibble(
    pos_med_y = matrixStats::colMedians(posterior_white), 
    race = 1, 
    c_idx = 1:ncol(posterior_white)), 
  tibble(
    pos_med_y = matrixStats::colMedians(posterior_black), 
    race = 2, 
    c_idx = 1:ncol(posterior_black))
)

pos_med %>% 
  mutate(race = as.character(race)) %>% 
  ggplot() + 
  geom_density(aes(x = pos_med_y, color = race), size = 1) + 
  theme_classic()
```


```{r}
## Add in correct fipschar ----
pos_med <- adrd_rates_df %>%
  mutate(y = log(observed) - log(expected)) %>% 
  dplyr::left_join(pos_med, by = c("c_idx", "race"))

pos_med %>% 
  ggplot() +
  geom_point(aes(x = y, y = pos_med_y, col = as.factor(race)))
```

## Decompose log ratios

```{r}
summary(stanfit_samples$delta)
```


```{r}
shared_w <- (stanfit_samples$phi * stanfit_samples$delta)
shared_b <- (stanfit_samples$phi / stanfit_samples$delta)

# posterior median
shared <- rbind(
  tibble(
    shared = matrixStats::colMedians(shared_w), 
    shared_unscaled = matrixStats::colMedians(stanfit_samples$phi), 
    race = 1, 
    c_idx = 1:ncol(shared_w)), 
  tibble(
    shared = matrixStats::colMedians(shared_b), 
    shared_unscaled = matrixStats::colMedians(stanfit_samples$phi), 
    race = 2, 
    c_idx = 1:ncol(shared_b))
)

## Add in correct fipschar ----
pos_med %<>% 
  dplyr::left_join(shared, by = c("c_idx", "race"))

shared %>% 
  mutate(race = as.character(race)) %>% 
  ggplot() + 
  geom_density(aes(x = shared_unscaled), size = 1) + 
  geom_density(aes(x = shared, color = race), size = 1) + 
  theme_classic()
```

```{r}
specific_w <- stanfit_samples$psi1
specific_b <- stanfit_samples$psi2

# posterior median
specific <- rbind(
  tibble(
    specific = matrixStats::colMedians(specific_w), 
    race = 1, 
    c_idx = 1:ncol(specific_w)), 
  tibble(
    specific = matrixStats::colMedians(specific_b), 
    race = 2, 
    c_idx = 1:ncol(specific_b))
)

## Add in correct fipschar ----
pos_med %<>% 
  dplyr::left_join(specific, by = c("c_idx", "race"))

specific %>% 
  mutate(race = as.character(race)) %>% 
  ggplot() + 
  geom_density(aes(x = specific, color = race), size = 1) + 
  theme_classic()
```

```{r}
write_rds(pos_med, "../data/intermediate/m0-pos_med.rds")
write_rds(stanfit_samples, "../data/intermediate/m0-stanfit_samples.rds")
write_rds(stanfit_summary, "../data/intermediate/m0-stanfit_summary.rds")
```
