
```{r setup, include=FALSE}
## Set working directory as project root
library(here)
knitr::opts_knit$set(root.dir = here())
```

```{r, message=FALSE, warning=FALSE}
## Load libraries ----
library(tidyverse)
library(magrittr)
library(sf)
library(cowplot)
library(viridis)
library(RColorBrewer)
library(ggpubr)
```

```{r}
## Read model results
stanfit_samples <- read_rds("data/intermediate/m0-stanfit_samples.rds")
stanfit_summary <- read_rds("data/intermediate/m0-stanfit_summary.rds")

## Read data ----
county_sf <- read_rds("data/symlinks/temp/county_sf.rds")
pos_med <- read_rds("data/intermediate/m0-pos_med.rds")

pos_med_sf <- county_sf %>% 
  select(county) %>% 
  right_join(pos_med)

dim(county_sf)
dim(pos_med_sf)
colnames(pos_med_sf)
```

```{r}
county_sf <- read_rds("data/symlinks/temp/county_sf.rds")
county_fips_df <- read_rds("data/symlinks/temp/county_fips_df.rds")
state_sf <- read_sf("data/county/tl_2015_us_state/tl_2015_us_state.shp")
state_sf %<>% 
  left_join(
    county_sf %>% 
      left_join(county_fips_df) %>% 
      st_drop_geometry() %>% 
      distinct(STATEFP, s_idx, st_abbr)
  ) %>% 
  filter(!is.na(s_idx))
```


## Observed vs Predicted

### log ratios (y)

```{r}
pos_med_sf %>% 
  mutate(
    res = y - pos_med_y,
    res_is_out = if_else(abs(res) > 2/3, 1, 0) 
  ) %>% 
  ggplot() +
  geom_sf(aes(fill = exp(y), col = as.factor(res_is_out)), lwd = 0.2) +
  facet_grid(~race) +
  theme(legend.position = "bottom")
```

### posterior median log ratios (pos_med_y)

In this model the "prediction" is a smoothed version of the observed.

```{r}
pos_med_sf %>% 
  ggplot() +
  geom_sf(aes(fill = pos_med_y), lwd = 0.00) +
  facet_grid(~race) +
  scale_fill_viridis(option = "D") + 
  theme_map() + 
  theme(legend.position = "bottom") 
```

## Risk decomposition

## state effects

```{r}
param = rownames(stanfit_summary$summary)
nu = tibble(
  param = param[grep("nu", param)],
  med = stanfit_summary$summary[grep("nu", param),"50%"],
  s_idx = 1:length(grep("nu", param))
)

state_sf %>% 
  left_join(nu) %>% 
  ggplot() + 
  geom_sf(aes(fill = med))
```

## shared unscaled

```{r}
summary(pos_med$shared_unscaled)
hist(pos_med$shared_unscaled)
```

```{r}
summary(pos_med$specific)
hist(pos_med$specific)
```

```{r}
pos_med_sf %<>% 
  mutate(
    shared_unscaled_inliers = if_else(shared_unscaled > -1 & shared_unscaled < 1, 
                                      shared_unscaled, as.numeric(NA)),
    shared_unscaled_outliers = if_else(shared_unscaled <= -1 | shared_unscaled >= 1, 
                                       shared_unscaled, as.numeric(NA)),
    shared_unscaled_outliers = if_else(shared_unscaled_outliers <= -1, -1, shared_unscaled_outliers),
    shared_unscaled_outliers = if_else(shared_unscaled_outliers >= 1, 1, shared_unscaled_outliers)
  ) 

pos_med_sf %>% 
  st_drop_geometry() %>% 
  select(shared_unscaled, shared_unscaled_inliers, shared_unscaled_outliers)
```

```{r}
filter(pos_med_sf, !is.na(shared_unscaled_outliers)) %>% 
  st_drop_geometry() %>% 
  select(shared_unscaled, shared_unscaled_inliers, shared_unscaled_outliers)
```

```{r}
myPalette <- colorRampPalette(rev(RColorBrewer::brewer.pal(11, "Spectral")))
sc <- scale_fill_gradientn(colors = myPalette(100), 
                           limits = c(-1, 1))

p1 <- pos_med_sf %>% 
  filter(race == 1) %>% 
  ggplot() +
  geom_sf(aes(fill = specific), lwd = 0.0) + 
  theme_map() +
  labs(subtitle = "white specific") + 
  theme(legend.title = element_blank()) + 
  sc

p2 <- pos_med_sf %>% 
  filter(race == 1) %>% #shared_unscaled is non-race specific
  ggplot() +
  geom_sf(aes(fill = shared_unscaled_inliers), lwd = 0.0) + 
  geom_sf(data = filter(pos_med_sf, shared_unscaled_outliers == 1), color = "red", lwd = 0.5) + 
  geom_sf(data = filter(pos_med_sf, shared_unscaled_outliers == -1), color = "blue", lwd = 0.5) + 
  theme_map() + 
  labs(subtitle = "shared unscaled") + 
  sc

p3 <- pos_med_sf %>% 
  filter(race == 2) %>% 
  ggplot() +
  geom_sf(aes(fill = specific), lwd = 0.0) + 
  theme_map() + 
  labs(subtitle = "black specific") +
  sc
  
p <- cowplot::plot_grid(
  p1 + theme(legend.position = "none"), 
  p2 + theme(legend.position = "none"), 
  p3  + theme(legend.position = "none"),
  nrow = 3)

cowplot::plot_grid(
  p, 
  cowplot::get_legend(p1), 
  ncol = 2
)
```

```{r}
filter(pos_med_sf, person_years == 0) %>% 
  st_drop_geometry() %>% 
  select(county, race, person_years, shared_unscaled, shared_unscaled_inliers, shared_unscaled_outliers)
```

```{r}
pos_med_sf %<>% 
  mutate(
    specific = if_else(person_years == 0, as.numeric(NA), specific),
    shared_unscaled_inliers = if_else(person_years == 0, as.numeric(NA), shared_unscaled_inliers),
    shared_unscaled_outliers = if_else(person_years == 0, as.numeric(NA), shared_unscaled_outliers)
  )
```

```{r}
myPalette <- colorRampPalette(rev(RColorBrewer::brewer.pal(11, "Spectral")))
sc <- scale_fill_gradientn(colors = myPalette(100), 
                           limits = c(-1, 1))

p1 <- pos_med_sf %>% 
  filter(race == 1) %>% 
  ggplot() +
  geom_sf(aes(fill = specific), lwd = 0.0) + 
  theme_map() +
  labs(subtitle = "white specific") + 
  theme(legend.title = element_blank()) + 
  sc

p2 <- pos_med_sf %>% 
  filter(race == 1) %>% #shared_unscaled is non-race specific
  ggplot() +
  geom_sf(aes(fill = shared_unscaled_inliers), lwd = 0.0) + 
  geom_sf(data = filter(pos_med_sf, shared_unscaled_outliers == 1), color = "red", lwd = 0.5) + 
  geom_sf(data = filter(pos_med_sf, shared_unscaled_outliers == -1), color = "blue", lwd = 0.5) + 
  theme_map() + 
  labs(subtitle = "shared unscaled") + 
  sc

p3 <- pos_med_sf %>% 
  filter(race == 2) %>% 
  ggplot() +
  geom_sf(aes(fill = specific), lwd = 0.0) + 
  theme_map() + 
  labs(subtitle = "black specific") +
  sc
  
p <- cowplot::plot_grid(
  p1 + theme(legend.position = "none"), 
  p2 + theme(legend.position = "none"), 
  p3  + theme(legend.position = "none"),
  nrow = 3)

cowplot::plot_grid(
  p, 
  cowplot::get_legend(p1), 
  ncol = 2
)
```

## shared unscaled

```{r}
shared_ <- c(pos_med$shared, pos_med$specific)
myPalette <- colorRampPalette(rev(RColorBrewer::brewer.pal(11, "Spectral")))
sc <- scale_fill_gradientn(colors = myPalette(100), 
                           limits = c(min(shared_), max(shared_)))

p1 <- pos_med_sf %>% 
  filter(race == 1) %>% 
  ggplot() +
  geom_sf(aes(fill = specific), lwd = 0.00) + 
  theme_map() +
  labs(subtitle = "white specific") + 
  theme(legend.title = element_blank()) + 
  sc

p2 <- pos_med_sf %>% 
  filter(race == 1) %>% #shared_unscaled is non-race specific
  ggplot() +
  geom_sf(aes(fill = shared), lwd = 0.00) + 
  theme_map() + 
  labs(subtitle = "shared white") + 
  sc

p3 <- pos_med_sf %>% 
  filter(race == 2) %>% #shared_unscaled is non-race specific
  ggplot() +
  geom_sf(aes(fill = shared), lwd = 0.00) + 
  theme_map() + 
  labs(subtitle = "shared black") + 
  sc

p4 <- pos_med_sf %>% 
  filter(race == 2) %>% 
  ggplot() +
  geom_sf(aes(fill = specific), lwd = 0.00) + 
  theme_map() + 
  labs(subtitle = "black specific") +
  sc
  
p <- cowplot::plot_grid(
  p1 + theme(legend.position = "none"), 
  p2 + theme(legend.position = "none"), 
  p3  + theme(legend.position = "none"),
  p4  + theme(legend.position = "none"),
  nrow = 2, 
  ncol = 2)

cowplot::plot_grid(
  p, 
  cowplot::get_legend(p1), 
  ncol = 2, 
  rel_widths = c(0.8, 0.2)
)
```
