
```{r setup, include=FALSE}
## Set working directory as project root
library(here)
knitr::opts_knit$set(root.dir = here())
```

```{r, message=FALSE, warning=FALSE}
## Load libraries ----
library(tidyverse)
library(sf)
library(magrittr)
library(viridis)
library(cowplot)
```

## Load data for adrd and hosp

```{r}
# choose which model to use
#model <- "m1"
model <- "m2"
#model <- "m3"

## Read data ----
county_sf <- read_rds("data/symlinks/scratch/county_sf.rds")
pos_med_adrd <- read_rds(paste0("data/intermediate/adrd_pos_med.rds"))
pos_med_hosp <- read_rds(paste0("data/intermediate/hosp_pos_med.rds"))

pos_med_adrd <- pos_med_adrd[[model]]
pos_med_hosp <- pos_med_hosp[[model]]


# join adrd and hosp
pos_med <- merge(pos_med_adrd, pos_med_hosp, all = TRUE, 
                 by = c("county", "race", "person_years", "med_house_income", 
                        "house_price_income_ratio", "pm25", "black", "fipschar", 
                        "fips_st", "c_idx", "s_idx"),
                 suffixes = c("_adrd", "_hosp"))
rm(pos_med_adrd, pos_med_hosp)

pos_med_sf <- county_sf %>% 
  select(county) %>% 
  right_join(pos_med)

colnames(pos_med_sf)

# load state data
county_fips_df <- read_rds("data/symlinks/scratch/county_fips_df.rds")
state_sf <- read_sf("data/county/cb_2015_us_state/cb_2015_us_state_20m.shp")
state_sf %<>% 
  left_join(
    county_sf %>% 
      left_join(county_fips_df) %>% 
      st_drop_geometry() %>% 
      distinct(STATEFP, s_idx)
  ) %>% 
  filter(!is.na(s_idx))
```

```{r}
# change projection to Albers Equal Area Conic (good for maps of US)
pos_med_sf <- st_transform(pos_med_sf, 
                           crs = st_crs("+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=37.5
                                        +lon_0=-96 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs"))
state_sf <- st_transform(state_sf, 
                           crs = st_crs("+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=37.5
                                        +lon_0=-96 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs"))
```

```{r}
# race labels for plotting
race_labels <- c(
  `1` = "White",
  `2` = "Black"
)
```

```{r}
# make new columns for rate of hospitalization (observed/person-years)
# and expected rate of hospitalization (expected/person-years)
pos_med_sf %<>% 
  mutate(rate_obs_adrd = observed_adrd/person_years,
         rate_exp_adrd = expected_adrd/person_years,
         rate_obs_hosp = observed_hosp/person_years,
         rate_exp_hosp = expected_hosp/person_years)
```


## Pre-modeling

```{r}
# person-years, observed counts, raw observed/expected ratios (all before modeling)

# I want to facet by parameter, so I need to gather the columns of interest
param_dist <- pos_med_sf |>
  st_drop_geometry() |>
  mutate(exp_y_adrd = exp(y_adrd),
         exp_y_hosp = exp(y_hosp)#,
         # exp_pos_med_y_adrd = exp(pos_med_y_adrd),
         # exp_pos_med_y_hosp = exp(pos_med_y_hosp)
         ) |>
  gather(key = "parameter", value = "value", 
         c(person_years, 
           observed_adrd,
           observed_hosp,
           exp_y_adrd,
           exp_y_hosp#,
           #exp_pos_med_y_adrd,
           #exp_pos_med_y_hosp
           )) |>
  select(county, race, parameter, value)

# look at NA values
# NA values are for ADRD rate the 71 
param_dist |>
  group_by(parameter) |>
  summarise(num_NA = sum(is.na(value)))
# these are just the 71 counties with 0 black person-years, so I can ignore them

# I want to plot on log scale, so change any 0s to 0.00000001
param_dist %<>%
  mutate(value = ifelse(value == 0, 0.00000001, value))

# set order of plots
param_dist$parameter <- factor(param_dist$parameter,
                               levels = c("person_years", "observed_adrd", "observed_hosp", 
                                          "exp_y_adrd", "exp_y_hosp"))

# plot
param_dist |>
  filter(!is.na(value)) |>
  mutate(race = factor(ifelse(race == 1, "White", "Black"),
                       levels = c("White", "Black"))) %>% 
  ggplot() +
  geom_density(aes(value, col = as.factor(race))) +
  labs(x = "",
       y = "Density",
       col = "") +
  scale_x_log10(labels = scales::comma) +
  facet_wrap(~parameter, scales = "free", 
             nrow = 3,
             labeller = as_labeller(c(person_years = "Person years",
                                      observed_adrd = "Observed hosp. w/ ADRD",
                                      observed_hosp = "Observed hosp. w/o ADRD",
                                      exp_y_adrd = "Raw observed/expected hosp. w/ ADRD",
                                      exp_y_hosp = "Raw observed/expected hosp. w/o ADRD"))) +
  theme_bw() +
  theme(strip.background = element_rect(fill = "white"),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        panel.grid = element_blank(),
        legend.position = "bottom")

# plotting x-axis on log scale!!

```



```{r}
# what % of all hosp have ADRD code?

# get a new column for observed ADRD / observed hosp %
pos_med_sf %<>%
  mutate(adrd_pct = (observed_adrd / (observed_adrd + observed_hosp)) * 100)

# get weighted avg. % by race
# what % of all hospitalizations had ADRD code?

# get total ADRD hosp by race
# and total other hosp by race

pos_med %>%
  group_by(race) %>%
  summarise(total_adrd = sum(observed_adrd),
            total_hosp = sum(observed_hosp)) %>%
  mutate(adrd_pct = total_adrd / (total_adrd + total_hosp))


# look at distribution of this variable for white vs. black
pos_med_sf |>
  mutate(race = factor(ifelse(race == 1, "White", "Black"),
                       levels = c("White", "Black"))) %>% 
  ggplot() +
  geom_density(aes(adrd_pct, col = as.factor(race))) +
  labs(x = "% of all hospitalizations with ADRD code",
       y = "Density",
       col = "") +
  theme_bw() +
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        panel.grid = element_blank())

# now map this variable!

pos_med_sf |>
  # cap at 30%
  mutate(adrd_pct = ifelse(adrd_pct > 30, 30, adrd_pct)) |>
  # exclude counties with < 100 hosp
  mutate(adrd_pct = ifelse(observed_hosp < 100, NA, adrd_pct)) |>
  ggplot() +
  geom_sf(aes(fill = adrd_pct), lwd = 0.1) +
  geom_sf(data = state_sf, fill = NA, col = "black", lwd = 0.1) +
  labs(fill = "% of hosp. w/ ADRD code") +
  scale_fill_viridis(option = "D") + 
  facet_grid(~race, labeller = as_labeller(race_labels)) +
  theme_map() +
  theme(legend.position = "bottom",
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 8)
        )

# # also try white only (more stable) ==> could combine white + black
# pos_med_sf |>
#   # # limit to rows with at least 25 person-years
#   #mutate(adrd_pct = ifelse(person_years < 50, NA, adrd_pct)) |>
#   #mutate(adrd_pct = ifelse(adrd_pct > 20, 20, adrd_pct)) |>
#   mutate(ifelse(observed_hosp < 400, NA, observed_hosp)) |>
#   filter(race == 1) %>%
#   ggplot() +
#   geom_sf(aes(fill = adrd_pct), lwd = 0.0) +
#   geom_sf(data = state_sf, fill = NA, col = "white", lwd = 0.1) +
#   labs(fill = "% of hosp. w/ ADRD code (white only)") +
#   scale_fill_viridis(option = "D") + 
#   theme_map() +
#   theme(legend.position = "bottom",
#         legend.title = element_text(size = 10),
#         legend.text = element_text(size = 8)
#         )

```

## Model results

```{r}
# compare distributions of risk ratios
pos_med_sf %>%
  st_drop_geometry() %>%
  filter(race == 1) %>% # choose one race for risk ratios
  gather(key = "outcome", "risk_ratio", risk_ratio_adrd, risk_ratio_hosp) %>%
  mutate(outcome = ifelse(outcome == "risk_ratio_adrd", 
                          "ADRD", "All other hosp.")) %>%
  ggplot() +
  geom_density(aes(x = risk_ratio, col = outcome)) +
  geom_vline(xintercept = 1, lty = 2) +
  labs(x = "Risk ratio",
       y = "Density",
       col = "Outcome") +
  theme_bw() +
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        panel.grid = element_blank())
```

```{r}
# get ratios of risk ratios and map

pos_med_sf %<>%
  mutate(ratio_of_risk_ratios = risk_ratio_adrd / risk_ratio_hosp)

sc <- scale_fill_gradient2(high = "orange", mid = "white", low = "blue", na.value = "gray50",
                         midpoint = 1)

pos_med_sf |>
  #mutate(adrd_pct = ifelse(adrd_pct > 20, 20, adrd_pct)) |>
  filter(race == 1) %>%
  ggplot() +
  geom_sf(aes(fill = ratio_of_risk_ratios), lwd = 0.1) +
  geom_sf(data = state_sf, fill = NA, lwd = 0.1) +
  labs(fill = "Ratio of risk ratios \n(ADRD/other hosp)") +
  theme_map() +
  theme(legend.position = "bottom",
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 8)
        ) +
  sc

# how do we decide which ones are statistically significantly different from 1?

# wait, something is weird here.

# imagine a county where black risk is higher for ADRD and all-cause hosp
# if the disparity is stronger for ADRD, ratio of ratios will be > 1
# if the disparity is stronger for all-cause hosp, ratio of ratios will be < 1
# ratio of ratios > 1 indicates that "racism" for black people is worse for ADRD

# now imagine a county where white risk is higher for ADRD and all-cause hosp
# if the disparity is stronger for ADRD (i.e. risk ratio is smaller, farther from 1), then ratio of ratios will be < 1
# if the disparity is stronger for all-cause hosp, ratio of ratios will be > 1
# ratio of ratios > 1 indicates that "racism" for white people is worse for all-cause

# example

# county A:
# RR for ADRD = 1.1
# RR for all-cause = 2.2
# ratio of ratios = 0.5
# disparities are stronger for all-cause hosp and worse for Black people

# county B:
# RR for ADRD = 0.4
# RR for all-cause = 0.8
# ratio of ratios = 0.5
# disparities are stronger for ADRD and worse for white people

# county C:
# RR for ADRD = 0.6
# RR for all-cause = 1.2
# ratio of ratios = 0.5
# disparities are in different directions (ADRD worse for white, all-cause hosp worse for black)

# ratio of risk ratios = 0.5 just tells us that RR is greater for ADRD than for all-cause hosp, but we don't know if this means the risk ratio for ADRD is closer to or farther from the null than the risk ratio for all-cause hosp
# we really want to know which one is farther from the null, not which one is strictly greater


```

```{r}
# okay, thinking about alternatives

# what about lambdas for each race?

# pos_med_sf %<>%
#   mutate(ratio_of_pos_med_y = pos_med_y_adrd / pos_med_y_hosp)
# 
# pos_med_sf |>
#   mutate(ratio_of_pos_med_y = ifelse(ratio_of_pos_med_y < -5, -5, ratio_of_pos_med_y),
#          ratio_of_pos_med_y = ifelse(ratio_of_pos_med_y > 5, 5, ratio_of_pos_med_y)) |>
#   ggplot() +
#   geom_sf(aes(fill = ratio_of_pos_med_y), lwd = 0.1) +
#   geom_sf(data = state_sf, fill = NA, col = "black", lwd = 0.1) +
#   labs(fill = "lambda ADRD/lambda hosp") +
#   facet_grid(~race, labeller = as_labeller(race_labels)) +
#   theme_map() +
#   theme(legend.position = "bottom",
#         legend.title = element_text(size = 10),
#         legend.text = element_text(size = 8)
#         ) +
#   sc

```

```{r}
# in counties where black people were significantly worse off (RR > 1) for both ADRD and hosp, which one was stronger?
# plot ADRD RR / hosp RR

pos_med_sf |>
  #mutate(adrd_pct = ifelse(adrd_pct > 20, 20, adrd_pct)) |>
  filter(race == 1) %>%
  mutate(ratio_of_risk_ratios = ifelse(
    risk_ratio_adrd > 1 & risk_ratio_sig_adrd & risk_ratio_hosp > 1 & risk_ratio_sig_hosp,
    ratio_of_risk_ratios, NA)) %>%
  ggplot() +
  geom_sf(aes(fill = ratio_of_risk_ratios), lwd = 0.1) +
  geom_sf(data = state_sf, fill = NA, col = "white", lwd = 0.1) +
  labs(fill = "Ratio of risk ratios \n(ADRD/other hosp)") +
  theme_map() +
  theme(legend.position = "bottom",
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 8)
        ) +
  sc

```

```{r}
# plot with three categories

# new column to compare RRs
pos_med_sf %<>%
  mutate(RR_comp = ifelse(risk_ratio_adrd > 1 & risk_ratio_hosp > 1, "black_worse_both", NA)) %>%
  mutate(RR_comp = ifelse(risk_ratio_adrd < 1 & risk_ratio_hosp < 1, "white_worse_both", RR_comp)) %>%
  mutate(RR_comp = ifelse(risk_ratio_adrd < 1 & risk_ratio_hosp > 1 |
                            risk_ratio_adrd > 1 & risk_ratio_hosp < 1, "different", RR_comp))

pos_med_sf |>
  filter(race == 1) %>%
  ggplot() +
  geom_sf(aes(fill = RR_comp), lwd = 0.1) +
  geom_sf(data = state_sf, fill = NA, lwd = 0.1) +
  labs(fill = "ADRD vs. hosp risk ratios") +
  theme_map()

```

