
```{r setup, include=FALSE}
## Set working directory as project root
library(here)
knitr::opts_knit$set(root.dir = here())
```

```{r, message=FALSE, warning=FALSE}
## Load libraries ----
library(tidyverse)
library(magrittr)
library(rstan)
library(ggthemes)
library(viridis)
library(sf)
library(knitr)
library(kableExtra)
library(xtable)
```

```{r}
#####----- user input -----#####

# select outcome
#outcome <- "adrd"
outcome <- "nonadrd"

# Medicaid-adjusted?
dual <- FALSE
#dual <- TRUE
```

```{r}
# load adrd ratios
if(dual){
  ratios_df <- read_rds(paste0("data/symlinks/scratch/", outcome, "-dual_ratios_df.rds"))
} else {
  ratios_df <- read_rds(paste0("data/symlinks/scratch/", outcome, "_ratios_df.rds"))
}

# load county fips data
county_fips_df <- read_rds("data/symlinks/scratch/county_fips_df.rds")

# read scaling factor from previous script
scaling_factor <- read_rds("data/intermediate/scaling_factor.rds")
```

##### STAGE 1 #####

```{r}
# Load data
model_path <- "data/models/working/"

# get all models in working model directory
all_files <- list.files(model_path, pattern = ".rds")

# get current file based on user-input
if(dual){
  current_file <- all_files[grepl(paste0("stage1_", outcome, "-dual.rds$"), all_files)]
} else {
  current_file <- all_files[grepl(paste0("stage1_", outcome, ".rds$"), all_files)]
}

# read models
stanfit_stage1 <- read_rds(paste0(model_path, current_file))

# extract posteriors for all parameters
stanfit_samples_stage1 <- extract(stanfit_stage1)
```

```{r}
# see which variables are available in model output
stanfit_stage1@model_pars
```

```{r}

#-- get set up for storing state random effects (need to repeat for each county per state)

# get number of counties in each state
nu_counts <- county_fips_df %>%
  dplyr::group_by(s_idx) %>%
  dplyr::summarize(count = dplyr::n()) %>%
  dplyr::mutate(c_sum = cumsum(count))

# need to repeat the state effect for each county in the state
nu_expanded_stage1 <- matrix(NA,
                             nrow = length(stanfit_samples_stage1$alpha),
                             ncol = max(nu_counts$c_sum))

# fill in nu_expanded with state random effects
for (s in 1:nrow(nu_counts)) {
  start_ix <- ifelse(length(nu_counts$c_sum[s - 1]) > 0,
                     nu_counts$c_sum[s - 1], 0) + 1
  end_ix <- nu_counts$c_sum[s]

  nu_expanded_stage1[, start_ix:end_ix] <- stanfit_samples_stage1$nu[, s]
}


#----- get scaled phis (need to scale raw phis)

# get matrix of raw phis
raw_phis <- stanfit_samples_stage1$phi

# get values to scale by (different for each posterior draw, same for each county)
scale_for_phis <- stanfit_samples_stage1$sigma * sqrt(1 / scaling_factor)

# scale each row/posterior draw of the raw phis by that draw's scale
scaled_phis <- matrix(NA, nrow = nrow(raw_phis), ncol = ncol(raw_phis))
for(j in 1:ncol(raw_phis)){
  scaled_phis[,j] <- raw_phis[,j] * scale_for_phis
}

# save scaled phis
phi_mat <-  scaled_phis


#----- log relative risk

# calculate log lambda
log_lambda_stage1_mat <- as.vector(stanfit_samples_stage1$alpha) + 
  nu_expanded_stage1 +
  stanfit_samples_stage1$convolved_re * as.vector(stanfit_samples_stage1$sigma)

```

```{r}
# get posterior means and determine significance

# function to lapply to all these lists
post_mean_sig_stage1 <- function(posterior_matrix, param_name, 
                                check_sig = c(FALSE, TRUE), null_value){
  
  # set up a data frame for results
  return_df <- data.frame(county = ratios_df$county[ratios_df$race == 1])
  
  # get column means and add to data frame
  posterior_means <- colMeans(posterior_matrix)
  return_df[[param_name]] <- posterior_means
  
  # check for significance and add to dataframe
  if(check_sig){
    
    q025s <- apply(posterior_matrix, 2, quantile, 0.025) # get 2.5%
    q100s <- apply(posterior_matrix, 2, quantile, 0.100) # get 10%
    q900s <- apply(posterior_matrix, 2, quantile, 0.900) # get 90%
    q975s <- apply(posterior_matrix, 2, quantile, 0.975) # get 97.5%
    
    # NOT significant if null falls in the credible interval
    posterior_sig_80 <- ifelse(q100s < null_value & q900s > null_value, FALSE, TRUE)
    posterior_sig_95 <- ifelse(q025s < null_value & q975s > null_value, FALSE, TRUE)
    
    return_df[[paste0(param_name, "_sig_80")]] <- posterior_sig_80
    return_df[[paste0(param_name, "_sig_95")]] <- posterior_sig_95
  }

  return(return_df)
}
```

```{r}
# apply function
log_lambda_stage1 <- post_mean_sig_stage1(log_lambda_stage1_mat, 
                                          param_name = "log_lambda_stage1", 
                                          check_sig = TRUE, 
                                          null_value = 0)
phi <- post_mean_sig_stage1(phi_mat,
                            param_name = "phi", 
                            check_sig = TRUE, 
                            null_value = 0)
```

```{r}
# get sd of posterior samples

lambda_stage1_sd <- apply(log_lambda_stage1_mat, 2, sd)
phi_sd <- apply(phi_mat, 2, sd)

# save SDs
if(dual){
  write_rds(lambda_stage1_sd, paste0("data/intermediate/", outcome, "-dual_lambda_stage1_sd.rds"))
  write_rds(phi_sd, paste0("data/intermediate/", outcome, "-dual_phi_sd.rds"))
} else {
  write_rds(lambda_stage1_sd, paste0("data/intermediate/", outcome, "_lambda_stage1_sd.rds"))
  write_rds(phi_sd, paste0("data/intermediate/", outcome, "_phi_sd.rds"))
}
```

```{r}
# join elements in log_lambda and phi
stage1_model_results <- merge(log_lambda_stage1, phi, by = "county")
```


##### STAGE 2 #####

```{r}

# get all models in working model directory
all_files <- list.files(model_path, pattern = ".rds")

# get current file based on user-input
if(dual){
  current_file <- all_files[grepl(paste0("stage2_", outcome, "-dual.rds$"), all_files)]
} else {
  current_file <- all_files[grepl(paste0("stage2_", outcome, ".rds$"), all_files)]
}

# read models
stanfit_stage2 <- read_rds(paste0(model_path, current_file))

# extract posteriors for all parameters
stanfit_samples_stage2 <- extract(stanfit_stage2)
```

```{r}
# see which variables are available in model output
stanfit_stage2@model_pars
```

```{r}
#-- get set up for storing state random effects (need to repeat for each county per state)

# need to repeat the state effect for each county in the state
nu_expanded_stage2 <- matrix(NA,
                             nrow = nrow(stanfit_samples_stage2$psi1),
                             ncol = max(nu_counts$c_sum))

# fill in nu_expanded with state random effects
for (s in 1:nrow(nu_counts)) {
  start_ix <- ifelse(length(nu_counts$c_sum[s - 1]) > 0,
                     nu_counts$c_sum[s - 1], 0) + 1
  end_ix <- nu_counts$c_sum[s]

  nu_expanded_stage2[, start_ix:end_ix] <- stanfit_samples_stage2$nu[, s]
}


#----- get scaled psis (need to scale raw psis)

# get matrices of raw psis
raw_psi1s <- stanfit_samples_stage2$psi1
raw_psi2s <- stanfit_samples_stage2$psi2

# get values to scale by (different for each posterior draw, same for each county)
scale_for_psi1s <- (stanfit_samples_stage2$sigma1 / sqrt(scaling_factor)) * sqrt(stanfit_samples_stage2$rho1)
scale_for_psi2s <- (stanfit_samples_stage2$sigma2 / sqrt(scaling_factor)) * sqrt(stanfit_samples_stage2$rho2)

# scale each row/posterior draw of the raw psis by that draw's scale
scaled_psi1s <- matrix(NA, nrow = nrow(raw_psi1s), ncol = ncol(raw_psi1s))
for(j in 1:ncol(scaled_psi1s)){
  scaled_psi1s[,j] <- raw_psi1s[,j] * scale_for_psi1s
}
scaled_psi2s <- matrix(NA, nrow = nrow(raw_psi2s), ncol = ncol(raw_psi2s))
for(j in 1:ncol(scaled_psi2s)){
  scaled_psi2s[,j] <- raw_psi2s[,j] * scale_for_psi2s
}

# save scaled psis
psi_white_mat <-  scaled_psi1s
psi_black_mat <-  scaled_psi2s


#----- log relative risk

# calculate log lambda for white and black
log_lambda_white_mat <- as.vector(stanfit_samples_stage2$alpha1) + 
  nu_expanded_stage2 +
  stanfit_samples_stage2$convolved_re_sigma[,1:(ncol(stanfit_samples_stage2$convolved_re_sigma)/2)] # white only
log_lambda_black_mat <- as.vector(stanfit_samples_stage2$alpha2) + 
  nu_expanded_stage2 +
  stanfit_samples_stage2$convolved_re_sigma[,((ncol(stanfit_samples_stage2$convolved_re_sigma)/2) + 1):
                                   ncol(stanfit_samples_stage2$convolved_re_sigma)] # black only

# calculate risk ratios
risk_ratio_mat <- exp(log_lambda_black_mat - log_lambda_white_mat)
```

```{r}
# store risk ratio posterior distribution to compare across outcomes
rr_post <- risk_ratio_mat %>% as.data.frame()

# name columns with counties (must be in the same order!!)
names(rr_post) <- ratios_df$county[ratios_df$race == 1]

# save matrix
if(dual){
  write_rds(rr_post, paste0("data/intermediate/", outcome, "-dual_risk_ratio_post.rds"))
} else {
  write_rds(rr_post, paste0("data/intermediate/", outcome, "_risk_ratio_post.rds"))
}
```

```{r}
# get posterior means and determine significance

# function to lapply to all these lists
post_mean_sig_stage2 <- function(posterior_matrix, param_name, 
                                check_sig = c(FALSE, TRUE), null_value, 
                                race = NULL){
  
  # set up a data frame for results
  return_df <- data.frame(county = ratios_df$county[ratios_df$race == 1])
  
  # get column means and add to data frame
  posterior_means <- colMeans(posterior_matrix)
  return_df[[param_name]] <- posterior_means
  
  # check for significance and add to dataframe
  if(check_sig){
    
    q025s <- apply(posterior_matrix, 2, quantile, 0.025) # get 2.5%
    q100s <- apply(posterior_matrix, 2, quantile, 0.100) # get 10%
    q900s <- apply(posterior_matrix, 2, quantile, 0.900) # get 90%
    q975s <- apply(posterior_matrix, 2, quantile, 0.975) # get 97.5%
    
    # NOT significant if null falls in the credible interval
    posterior_sig_80 <- ifelse(q100s < null_value & q900s > null_value, FALSE, TRUE)
    posterior_sig_95 <- ifelse(q025s < null_value & q975s > null_value, FALSE, TRUE)
    
    return_df[[paste0(param_name, "_sig_80")]] <- posterior_sig_80
    return_df[[paste0(param_name, "_sig_95")]] <- posterior_sig_95
  }
  
  # if race is specified, make a column for race
  if(!is.null(race)){
    return_df$race <- race
  }

  return(return_df)
}
```

```{r}
# apply function
log_lambda_white <- post_mean_sig_stage2(log_lambda_white_mat, 
                                         param_name = "log_lambda_stage2", check_sig = TRUE, 
                                         null_value = 0, race = 1)
log_lambda_black <- post_mean_sig_stage2(log_lambda_black_mat, 
                                         param_name = "log_lambda_stage2", check_sig = TRUE, 
                                         null_value = 0, race = 2)
psi_white <- post_mean_sig_stage2(psi_white_mat, 
                                  param_name = "psi", check_sig = TRUE, 
                                  null_value = 0, race = 1)
psi_black <- post_mean_sig_stage2(psi_black_mat,
                                  param_name = "psi", check_sig = TRUE, 
                                  null_value = 0, race = 2)
risk_ratio <- post_mean_sig_stage2(risk_ratio_mat,
                                   param_name = "risk_ratio", check_sig = TRUE, 
                                   null_value = 1)
```

```{r}
# join elements in lists
stage2_model_results <- list()

# bind rows for two races
log_lambda_both <- rbind.data.frame(log_lambda_white, log_lambda_black)
psi_both <- rbind.data.frame(psi_white, psi_black)

# now merge results for log lambda and psi
stage2_model_results <- merge(log_lambda_both, psi_both, by = c("county", "race"))

# and join with risk ratios (not race specific)
stage2_model_results <- merge(stage2_model_results, risk_ratio, by = "county")

```

```{r}
# get standard deviation of posterior samples
lambda_white_sd <- apply(log_lambda_white_mat, 2, sd)
lambda_black_sd <- apply(log_lambda_black_mat, 2, sd)
psi_white_sd <- apply(psi_white_mat, 2, sd)
psi_black_sd <- apply(psi_black_mat, 2, sd)

# save
if(dual){
  write_rds(lambda_white_sd, paste0("data/intermediate/", outcome, "-dual_lambda_white_sd.rds"))
  write_rds(lambda_black_sd, paste0("data/intermediate/", outcome, "-dual_lambda_black_sd.rds"))
  write_rds(psi_white_sd, paste0("data/intermediate/", outcome, "-dual_psi_white_sd.rds"))
  write_rds(psi_black_sd, paste0("data/intermediate/", outcome, "-dual_psi_black_sd.rds"))
} else {
  write_rds(lambda_white_sd, paste0("data/intermediate/", outcome, "_lambda_white_sd.rds"))
  write_rds(lambda_black_sd, paste0("data/intermediate/", outcome, "_lambda_black_sd.rds"))
  write_rds(psi_white_sd, paste0("data/intermediate/", outcome, "_psi_white_sd.rds"))
  write_rds(psi_black_sd, paste0("data/intermediate/", outcome, "_psi_black_sd.rds"))
}
```

```{r}
# join stage 1 and stage 2 results

# join dfs from stage 1 and stage 2
model_results <- merge(stage1_model_results, stage2_model_results, by = "county")

# save results
if(dual){
  write_rds(model_results, paste0("data/intermediate/", outcome, "-dual_model_results.rds"))
} else {
  write_rds(model_results, paste0("data/intermediate/", outcome, "_model_results.rds"))
}
```


##### Empirical variance table #####

# this section works if m1, m2, and m3 exist (otherwise error)

```{r}
# # function to get median, mean, 2.5 percentile, 97.5 percentile
# # as_data_frame() is now deprecated, but as.data.frame() doesn't work here
# # this gives us the median, 2.5 percentile, and 97.5 percentile of a vector
# quick_summarize <- function(x) {
#     new_df <- x %>%
#         dplyr::as_data_frame() %>%
#         dplyr::summarize(
#             median = stats::median(value),
#             p025 = stats::quantile(value, .025),
#             p975 = stats::quantile(value, .975)
#         )
#     return(new_df)
# }
```

```{r}
# # initialize list
# empiric_vars <- list()
# 
# # loop through models
# for (i in 1:length(stanfit_list_stage1)){
# 
#   # get the between-county variance for each posterior sample
#   # then report the median between-county variance and a CI for that estimate
# 
# 
#   # mini table for total risk stage 1
#   empiric_var_risks_stage1 <- matrixStats::rowVars(log_lambda_stage1_mats[[i]]) %>%
#     quick_summarize() %>%
#     dplyr::mutate(race = "--",
#                   param = "Total risk stage 1")
# 
# 
#   # mini table for total risk stage 2
#   empiric_var_risks_stage2 <- rbind(
#     matrixStats::rowVars(log_lambda_white_mats[[i]]) %>%
#         quick_summarize() %>%
#           dplyr::mutate(race = "White"),
#     matrixStats::rowVars(log_lambda_black_mats[[i]]) %>%
#         quick_summarize() %>%
#           dplyr::mutate(race = "Black")
#   ) %>%
#       dplyr::mutate(param = "Total risk stage 2")
# 
# 
#   # mini table for shared risk
#   empiric_var_shared_risk <- matrixStats::rowVars(phi_mats[[i]]) %>%
#     quick_summarize() %>%
#     dplyr::mutate(race = "--",
#                   param = "Shared risk")
# 
# 
#   # mini table for race-specific risk
#   empiric_var_race_specific <- rbind(
#     matrixStats::rowVars(psi_white_mats[[i]]) %>%
#         quick_summarize() %>%
#           dplyr::mutate(race = "White"),
#     matrixStats::rowVars(psi_black_mats[[i]]) %>%
#         quick_summarize() %>%
#           dplyr::mutate(race = "Black")
#   ) %>%
#       dplyr::mutate(param = "Race-specific risk")
# 
# 
#   #-----------------------------------------------
#   # # mini table for fraction shared risk
#   # empiric_shared_var_frac <- rbind(
#   #     quick_summarize(
#   #         matrixStats::rowVars(stanfit_samples[[i]]$phi * stanfit_samples[[i]]$delta) /
#   #             (
#   #                 matrixStats::rowVars(stanfit_samples[[i]]$phi * stanfit_samples[[i]]$delta) +
#   #                     matrixStats::rowVars(stanfit_samples[[i]]$psi1)
#   #             )
#   #     ) %>%
#   #         dplyr::mutate(race = "White"),
#   #     quick_summarize(
#   #         matrixStats::rowVars(stanfit_samples[[i]]$phi / stanfit_samples[[i]]$delta) /
#   #             (
#   #                 matrixStats::rowVars(stanfit_samples[[i]]$phi / stanfit_samples[[i]]$delta) +
#   #                     matrixStats::rowVars(stanfit_samples[[i]]$psi2)
#   #             )
#   #     ) %>%
#   #         dplyr::mutate(race = "Black")
#   # ) %>%
#   #     dplyr::mutate(param = "fraction shared risk")
#   #-----------------------------------------------
# 
# 
# 
#   # mini table for state risk
#   empiric_var_state_vars <- rbind(
#       quick_summarize(stanfit_samples_stage1[[i]]$sigma_s ^ 2) %>%
#           dplyr::mutate(
#               race = "--",
#               param = "State variance stage 1"
#           ),
#       quick_summarize(stanfit_samples_stage2[[i]]$sigma_s ^ 2) %>%
#           dplyr::mutate(
#               race = "--",
#               param = "State variance stage 2"
#           )
#   )
# 
#   # bind all mini tables together
#   empiric_vars[[i]] <- rbind(
#       empiric_var_risks_stage1,
#       empiric_var_risks_stage2,
#       empiric_var_state_vars,
#       empiric_var_shared_risk,
#       empiric_var_race_specific
#   ) %>%
#       dplyr::select(race, param, dplyr::everything()) %>%
#       dplyr::mutate(
#           param = factor(
#               param,
#               levels =  c(
#                   "Total risk stage 1",
#                   "Total risk stage 2",
#                   "Shared risk",
#                   "Race-specific risk",
#                   "State variance stage 1",
#                   "State variance stage 2"
#               ),
#               ordered = TRUE
#           ),
#           race = factor(
#               race,
#               levels = c("White", "Black", "--"),
#               ordered = TRUE
#           )
#       )
# 
#   # sort table
#   empiric_vars[[i]] <- empiric_vars[[i]] %>%
#       dplyr::arrange(param, race)
# 
#   # new column formatted with posterior median and 95% CI
#   empiric_vars[[i]]$median_ci <- paste0(format(round(empiric_vars[[i]]$median, 3),
#                                                      scientific = FALSE), " (",
#                                    format(round(empiric_vars[[i]]$p025, 3),
#                                                      scientific = FALSE), ", ",
#                                    format(round(empiric_vars[[i]]$p975, 3),
#                                                      scientific = FALSE), ")")
# 
#   # rename columns
#   empiric_vars[[i]] <- empiric_vars[[i]] |>
#     select(-c(median, p025, p975)) |>
#     rename(Parameter = param,
#               Race = race,
#            Estimate = median_ci)
# }
# 
# # name list elements for clarity
# #names(empiric_vars) <- c("adrd_m1", "adrd_m2", "adrd_m3")
# names(empiric_vars) <- sub("stage1_", "", names(stage1_model_results))
# 
# # save table with results
# if(dual){
#   write_rds(empiric_vars,
#           file = paste0("results/tables/intermediate/", outcome, "-dual_empirical_variance.rds"))
# } else {
#   write_rds(empiric_vars,
#           file = paste0("results/tables/intermediate/", outcome, "_empirical_variance.rds"))
# }
```


# Get model beta estimates

# this section works if m1, m2, and m3 exist (otherwise error)

```{r}

# # beta_df <- data.frame(matrix(nrow = length(beta_white_vecs)*2, ncol = 5)) |>
# #   setNames(c("model", "race", "post_mean", "q5", "q95"))
# # 
# # beta_df$model <- rep(names(adrd_model_results), times = 2)
# # beta_df$race <- rep(c("White", "Black"), each = length(names(adrd_model_results)))
# 
# # function to get posterior medians & credible intervals from beta lists
# extract_beta_info <- function(x){
#   if(is.null(x)){
#     return(c(NA))
#   } else {
#     post_mean <- mean(x) |> exp() |> round(3) 
#     q5 <- quantile(x, 0.05) |> exp() |> round(3)
#     q95 <- quantile(x, 0.95) |> exp() |> round(3)
#     #return(c(post_mean = post_mean, q5, q95))
#     return(paste0(post_mean, " (", q5, ", ", q95, ")"))
#   }
# }
# 
# # table with white betas
# beta_white <- lapply(beta_white_vecs, extract_beta_info) |>
#   bind_cols() |>
#   gather(key = "model", value = "estimate") |>
#   mutate(race = "White")
# 
# # table with black betas
# beta_black <- lapply(beta_black_vecs, extract_beta_info) |>
#   bind_cols() |>
#   gather(key = "model", value = "estimate") |>
#   mutate(race = "Black")
# 
# # clean table
# beta_df <- rbind(beta_white, beta_black) |>
#   filter(!is.na(estimate)) |>
#   arrange(model) |>
#   mutate(parameter = paste0(model, ", ", race)) |>
#   select(parameter, estimate) |>
#   mutate(parameter = case_when(
#     parameter == "stage2_adrd_m2, White" ~ 
#       "White effect of PIR ($e^{\\beta_{\\text{PIR, 1}}}$)",
#     parameter == "stage2_adrd_m2, Black" ~ 
#       "Black effect of PIR ($e^{\\beta_{\\text{PIR, 2}}}$)",
#     parameter == "stage2_adrd_m3, White" ~ 
#       "White effect of PM2.5 ($e^{\\beta_{\\text{PM2.5, 1}}}$)",
#     parameter == "stage2_adrd_m3, Black" ~ 
#       "Black effect of PM2.5 ($e^{\\beta_{\\text{PM2.5, 2}}}$)"
#   )) |>
#   rename(Parameter = parameter,
#          "Estimate (95\\% CI)" = estimate)
# 
# # write to rds (create adrd + hosp table in script 11)
# if(dual){
#   write_rds(beta_df, file = paste0("results/tables/intermediate/", outcome, "-dual_beta_df.rds"))
# } else {
#   write_rds(beta_df, file = paste0("results/tables/intermediate/", outcome, "_beta_df.rds"))
# }
# 
# # # get table in latex
# # print(xtable(beta_df, type = "latex"), 
# #       file = "results/tables/final/adrd_betas.tex",
# #       sanitize.text.function = identity, # don't escape math symbols
# #       include.rownames = FALSE) 
```


