
```{r setup, include=FALSE}
## Set working directory as project root
library(here)
knitr::opts_knit$set(root.dir = here())
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r, message=FALSE, warning=FALSE}
## Load libraries ----
library(tidyverse)
library(magrittr)
library(sf)
library(cowplot)
library(viridis)
library(RColorBrewer)
library(ggpubr)
library(pander)
library(data.table)
library(ggthemes)
library(knitr)
library(kableExtra)
library(xtable)
```

```{r}
# set path for saving figures
fig_path <- "results/figures/final/"
```

## Load data

```{r}
# load list with all model results and bind into df
hosp_res <- read_rds("data/intermediate/hosp_model_results.rds")
hosp_res <- bind_rows(hosp_res, .id = "model")

# # limiting to model 1 for now
# hosp_res <- hosp_res %>%
#   filter(model == "hosp_m1")
```

```{r}
## Read data ----
hosp_ratios_df_comb <- read_rds('data/symlinks/scratch/hosp_combined_data.rds')
hosp_ratios_df <- read_rds('data/symlinks/scratch/hosp_ratios_df.rds')
county_sf <- read_rds("data/symlinks/scratch/county_sf.rds")
county_sf_zero_b <- read_rds("data/symlinks/scratch/county_sf_zero_b.rds")

hosp_res_sf <- county_sf %>% 
  select(county) %>% 
  right_join(hosp_ratios_df_comb) %>%
  right_join(hosp_ratios_df) %>%
  right_join(hosp_res)

colnames(hosp_res_sf)
```

```{r}
county_fips_df <- read_rds("data/symlinks/scratch/county_fips_df.rds")
state_sf <- read_sf("data/county/cb_2015_us_state/cb_2015_us_state_20m.shp")
state_sf %<>% 
  left_join(
    county_sf %>% 
      left_join(county_fips_df) %>% 
      st_drop_geometry() %>% 
      distinct(STATEFP, s_idx)
  ) %>% 
  filter(!is.na(s_idx))
```

```{r}
# change projection to Albers Equal Area Conic (good for maps of US)

hosp_res_sf <- st_transform(hosp_res_sf, 
                           crs = st_crs("+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=37.5
                                        +lon_0=-96 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs"))
state_sf <- st_transform(state_sf, 
                           crs = st_crs("+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=37.5
                                        +lon_0=-96 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs"))
county_sf_zero_b <- st_transform(county_sf_zero_b,
                                 crs = st_crs("+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=37.5
                                        +lon_0=-96 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs"))
```

```{r}
# race labels for plotting
race_labels <- c(
  `1` = "White",
  `2` = "Black"
)
```

```{r}
# add a column for lambda in stage 2
hosp_res_sf %<>%
  mutate(y_stage2 = log(observed/expected_stage2))
```

## Pre-modeling visualizations of observed and expected

### Expected rates table

```{r}
exp_rates_1 <- read_rds(paste0("results/tables/intermediate/hosp_expected_rates_race-specific.rds"))
exp_rates_2 <- read_rds(paste0("results/tables/intermediate/hosp_expected_rates_overall.rds"))

exp_rates_tab <- left_join(exp_rates_1, exp_rates_2)

# # get table in latex
# print(xtable(exp_rates_tab, type = "latex"), file = "results/tables/final/hosp_national_rates.tex")
```

## Model results

```{r}
# set up data

# gather raw observed/expected and lambdas
stage2_total_risk_df <- hosp_res_sf |>
  mutate(y_stage2 = log(observed/expected_stage2)) |>
  select(county, geometry, model, race,
         y_stage2, log_lambda_stage2) |>
  # gather raw and modeled lambdas
  gather(key = "raw_vs_model", value = "estimate", y_stage2, log_lambda_stage2) %>%
  # separate category for each model
  mutate(raw_vs_model = ifelse(raw_vs_model == "log_lambda_stage2", model, "raw")) %>%
  select(-model) %>%
  distinct()

# set levels for plotting
stage2_total_risk_df$raw_vs_model <- factor(stage2_total_risk_df$raw_vs_model,
                                       levels = c("raw", "hosp_m1", "hosp_m2", "hosp_m3"))

# labels for facets
stage2_total_risk_1m_labels <- c(
  `1` = "White",
  `2` = "Black",
  raw = "Raw\n observed/expected",
  hosp_m1 = "Smoothed\n observed/expected (\u03BB)",
  "1_specific" = "White-specific\n (\u03C8\u2081)",
  "both_shared_unscaled" = "Unscaled shared\n (\u03A6)",
  "2_specific" = "Black-specific\n (\u03C8\u2082)"
)

# plot
stage2_total_risk_df |>
  filter(raw_vs_model == "raw" | raw_vs_model == "hosp_m1") |>
  mutate(estimate = ifelse(estimate >= log(3), log(3)-0.001, estimate)) |>
  ggplot() +
  geom_sf(aes(fill = exp(estimate)), lwd = 0.03) + 
  geom_sf(data = county_sf_zero_b, fill = "gray70", lwd = 0.0) + 
  geom_sf(data = state_sf, fill = NA, col = "white", lwd = 0.1) +
  theme_map() + 
  labs(fill = expression('Relative risk')) +
  facet_grid(race ~ raw_vs_model,
             labeller = as_labeller(stage2_total_risk_1m_labels)
             ) +
  theme(legend.title = element_text(size = 12, vjust = 0.8),
        legend.text = element_text(size = 9),
        legend.position = "bottom",
        strip.text = element_text(size = 12),
        strip.background = element_blank(),
        plot.background = element_rect(fill = "white", color = NA)) +
  # this scale is capping at max in previous plot
  scale_fill_viridis(option = "A", 
                     na.value = "gray70",
                     limits = c(0, 3),
                     labels = c("0", "1", "2", "3+"),
                     guide = guide_colorbar(ticks = FALSE,
                                            barwidth = 12, barheight = 0.5))
#ggsave(paste0(fig_path, "hosp_raw_vs_lambda.pdf"), width = 7, height = 4)
ggsave(paste0(fig_path, "hosp_raw_vs_lambda.png"), width = 6, height = 4, dpi = 1000)
```

### White-specific, Black-specific, and shared risks (three risk surfaces)

```{r}
# set up data

# gather shared and specific columns
shared_specific_df <- hosp_res_sf |>
  select(county, geometry, model, race, 
         phi, phi_sig, psi, psi_sig) |>
  gather(key = "shared_vs_spec", value = "estimate", phi, psi) %>%
  # new sig column for estimate
  mutate(estimate_sig = ifelse(shared_vs_spec == "psi", psi_sig, phi_sig)) |>
  # remove other sig columns for clarity
  select(-c(phi_sig, psi_sig)) |>
  # change race for shared rows
  mutate(race = ifelse(shared_vs_spec == "phi", "both", race)) %>%
  distinct() |>
  mutate(parameter = paste0(race, "_", shared_vs_spec)) 

# set levels for plotting
shared_specific_df$parameter <- factor(shared_specific_df$parameter,
                                       levels = c("1_psi", "both_phi", "2_psi"))

sc <- scale_fill_gradient2(high = "#7600bc", mid = "white", low = "#028A0F", na.value = "gray50",
                         midpoint = 0,
                         guide = guide_colorbar(barwidth = 10, barheight = 1))

# labels for facets
shared_specific_labels_1m <- c(
  #"1_psi" = "White-specific\n (\u03C8\u2081)",
  "1_psi" = "White-specific",
  #"both_phi" = "Shared\n (\u03A6)",
  "both_phi" = "Shared",
  #"2_psi" = "Black-specific\n (\u03C8\u2082)"
  "2_psi" = "Black-specific"
)

# set up data
shared_specific_df %<>%
  mutate(estimate_binary = ifelse(estimate > 0, "High risk", "Low risk")) %>%
  mutate(estimate_binary = ifelse(estimate_sig, estimate_binary, NA))

sc <- scale_fill_gradient2(high = "#7600bc", mid = "white", low = "#028A0F", na.value = "gray50",
                         midpoint = 0,
                         guide = guide_colorbar(barwidth = 10, barheight = 1))

# plot
shared_specific_df |>
  filter(model == "hosp_m1") |>
  ggplot() +
  geom_sf(aes(fill = estimate_binary), lwd = 0.03) + 
  #geom_sf(aes(fill = estimate), lwd = 0.03) + 
  geom_sf(data = county_sf_zero_b, fill = "gray90", lwd = 0.0) + 
  geom_sf(data = state_sf, fill = NA, col = "black", lwd = 0.1) +
  labs(fill = "Risk component:") +
  facet_grid(~ parameter,
             labeller = as_labeller(shared_specific_labels_1m)
             ) +
  theme_map() + 
  theme(legend.title = element_text(size = 10),
        legend.text = element_text(size = 10),
        legend.position = "bottom",
        strip.text = element_text(size = 12),
        strip.background = element_blank(),
        plot.background = element_rect(fill = "white", color = NA)) +
  #sc
  scale_fill_manual(values = c("Low risk" = "#006400",
                               "High risk" = "#B47EE5"),
                     na.value = "gray90")
ggsave(paste0(fig_path, "hosp_shared_vs_specific.png"), width = 7, height = 2.5, dpi = 1000)

# franklin <- shared_specific_df %>%
#   filter(county == "12037" & model == "hosp_m1")
```

### Risk ratios

```{r}
# table of risk ratios < 1, > 1, non-significant

hosp_res_sf %>%
  filter(model == "hosp_m1") %>%
  filter(race == 2) %>% # same risk ratio for white and black rows
  select(-geometry) %>%
  as.data.frame() %>%
  mutate(
    risk_ratio_direction = ifelse(risk_ratio_sig, risk_ratio, as.numeric(NA)),
    risk_ratio_direction = ifelse(risk_ratio_direction < 1, "Risk ratio < 1", "Risk ratio > 1")
  ) %>%
  count(risk_ratio_direction) %>%
  mutate(pcnt = n / sum(n) * 100)
```

```{r}
# plot risk ratios

# set up data

# set boundaries for discrete bins
bin_breaks <- c(0, 0.2, 0.4, 0.6, 0.8, 1, 1.2, 1.4, 1.6, 1.8, 2, 2.2, 2.4, 3.6)

# get bin labels from bin breaks (get mean)
bin_df <- embed(bin_breaks, 2) |> as.data.frame()
bin_means <- rowMeans(bin_df) |> format(nsmall = 1)

# new column for risk ratio bins
hosp_res_sf %<>% 
  mutate(
    risk_ratio = ifelse(risk_ratio_sig, risk_ratio, as.numeric(NA)),
    risk_ratio_bins = cut(risk_ratio, 
                          breaks = bin_breaks,
                          labels = bin_means
                          ))

hosp_risk_ratios <- hosp_res_sf %>% 
  filter(model == "hosp_m1") |>
  select(county, geometry, model, risk_ratio_bins) %>%
  distinct() %>%
  ggplot() +
  geom_sf(aes(fill = risk_ratio_bins), lwd = 0.03) + 
  geom_sf(data = county_sf_zero_b, fill = "gray40", lwd = 0.0) + 
  geom_sf(data = state_sf, fill = NA, col = "black", lwd = 0.2) +
  labs(fill = expression('Risk Ratio (' *lambda[' 2ij']*'/'*lambda[' 1ij']*', Black/White)'),
       title = "Hospitalization without ADRD") +
  theme_map() +
  theme(legend.position = "bottom", 
        #legend.justification = "right", 
        #legend.direction = "vertical",
        legend.title = element_text(size = 12),
        legend.text = element_text(size = 10),
        strip.background = element_blank(),
        plot.background = element_rect(fill = "white", color = NA),
        plot.title = element_text(hjust = 0.5, size = 14, face = "plain")) +
  scale_fill_manual(
    # values = c("#08306b",
    #            "#2171b5",
    #            "#fee6ce",
    #            "#fdd0a2", 
    #            "#fdae6b", 
    #            "#fd8d3c", 
    #            "#f16913",
    #            "#d94801",
    #            "#a63603", 
    #            "#7f2704"),
    values = c("#08306b",
               "#313695",
               "#2171b5",
               "#74add1",
               "#abd9e9",
               "#fee6ce",
               "#fdd0a2", 
               "#fdae6b", 
               "#fd8d3c", 
               "#f16913",
               "#d94801",
               "#a63603", 
               "#7f2704"),
    na.value = "gray40",
    drop = FALSE,
    breaks = levels(unique(hosp_res_sf$risk_ratio_bins))#,
    #na.translate = F      # makes NA white
  ) +
  guides(fill = guide_legend(
    title.position = "top",
    nrow = 1,
            label.position = "bottom",
            keywidth = grid::unit(2, "lines"),
            keyheight = grid::unit(.5, "lines"),
            label.hjust = 0))
hosp_risk_ratios

# save data for plot, not pdf (combine plots across outcomes in script 11)
write_rds(hosp_risk_ratios, file = "data/symlinks/scratch/hosp_risk_ratio_maps.rds")
```

## Look at distributions of post-modeling variables across counties

```{r}
# function to get summary statistics
summarize_column <- function(df, 
                             column_name, 
                             param_name, 
                             exp_transform = FALSE) {
  result <- df %>%
    st_drop_geometry() %>% 
    group_by(model, race) %>%
    summarize(
      min = ifelse(exp_transform,
                   min(exp({{ column_name }}), na.rm = TRUE),
                   min({{ column_name }}, na.rm = TRUE)),
      p050 = ifelse(exp_transform,
                    stats::quantile(exp({{ column_name }}), .05, na.rm = TRUE),
                    stats::quantile({{ column_name }}, .05, na.rm = TRUE)),
      p250 = ifelse(exp_transform,
                    stats::quantile(exp({{ column_name }}), .250, na.rm = TRUE),
                    stats::quantile({{ column_name }}, .250, na.rm = TRUE)),
      p500 = ifelse(exp_transform,
                    stats::median(exp({{ column_name }}), na.rm = TRUE),
                    stats::median({{ column_name }}, na.rm = TRUE)),
      p750 = ifelse(exp_transform,
                    stats::quantile(exp({{ column_name }}), .750, na.rm = TRUE),
                    stats::quantile({{ column_name }}, .750, na.rm = TRUE)),
      p950 = ifelse(exp_transform,
                    stats::quantile(exp({{ column_name }}), .95, na.rm = TRUE),
                    stats::quantile({{ column_name }}, .95, na.rm = TRUE)),
      max = ifelse(exp_transform,
                   max(exp({{ column_name }}), na.rm = TRUE),
                   max({{ column_name }}, na.rm = TRUE))
    ) %>%
    mutate(param = param_name,
           min = round(min, 2),
           p050 = round(p050, 2),
           p250 = round(p250, 2),
           p500 = round(p500, 2),
           p750 = round(p750, 2),
           p950 = round(p950, 2),
           max = round(max, 2))
  return(result)
}


# apply function to get summary stats table
# note: I don't think the first two can come off of FASSE because they show small counts
summary_stats <- rbind(
  # summarize_column(hosp_res_sf, 
  #                  column_name = person_years,
  #                  param_name = "person years"),
  # summarize_column(hosp_res_sf, 
  #                  column_name = observed,
  #                  param_name = "observed"),
  summarize_column(df = hosp_res_sf,
                   column_name = y_stage2,
                   param_name = "Raw observed/expected",
                   exp_transform = TRUE),
  # summarize_column(df = hosp_res_sf, 
  #                  column_name = log_lambda_stage1, 
  #                  param_name = "Standardized risk (lambda) stage 1", 
  #                  exp_transform = TRUE),
  summarize_column(df = hosp_res_sf, 
                   column_name = log_lambda_stage2, 
                   param_name = "Standardized risk ($\\lambda$)", 
                   exp_transform = TRUE),
  summarize_column(df = hosp_res_sf, 
                   column_name = phi, 
                   param_name = "Shared risk ($\\phi_{ij}$)"),
  summarize_column(df = hosp_res_sf, 
                   column_name = psi, 
                   param_name = "Race-specific risk ($\\psi_{dij}$)"),
  summarize_column(df = hosp_res_sf, 
                   column_name = risk_ratio, 
                   param_name = "Risk ratio ($\\lambda_{2ij}/\\lambda_{1ij}$)")
  )

# set order of parameters
summary_stats$param <- factor(summary_stats$param,
                              levels = c("Raw observed/expected",
                                         "Standardized risk ($\\lambda$)", 
                                         "Shared risk ($\\phi_{ij}$)",
                                         "Race-specific risk ($\\psi_{dij}$)", 
                                         "Risk ratio ($\\lambda_{2ij}/\\lambda_{1ij}$)"))


# make certain parameters a single row (same for both races) and arrange
summary_stats %<>%
  filter(!(param %in% c("Shared risk ($\\phi_{ij}$)", 
                                    "Standardized risk (lambda) stage 1",
                                    "Risk ratio ($\\lambda_{2ij}/\\lambda_{1ij}$)") 
           & race == 2)) %>%
  mutate(race = ifelse(param %in% c("Shared risk ($\\phi_{ij}$)", 
                                    "Standardized risk (lambda) stage 1",
                                    "Risk ratio ($\\lambda_{2ij}/\\lambda_{1ij}$)"),
                       "--", race),
         model = str_remove(model, "hosp_")) %>%
  arrange(param, race, model)

# change race and model values
summary_stats %<>%
  mutate(race = ifelse(race == 1, "White", race)) %>%
  mutate(race = ifelse(race == 2, "Black", race)) %>%
  mutate(model = ifelse(model == "hosp_m1", "Unadjusted", model)) %>%
  mutate(model = ifelse(model == "hosp_m2", "Adjusted for HPIR", model)) %>%
  mutate(model = ifelse(model == "hosp_m3", "Adjusted for $PM_{2.5}$", model)) %>%
  select(c(param, everything()))

# display without scientific notation
summary_stats[] <- lapply(summary_stats, function(x) if(is.numeric(x)) format(x, scientific = FALSE) else x)

# rename columns
summary_stats <- summary_stats |>
  rename(Parameter = param,
         Model = model,
            Race = race,
            `Min.` = min,
            `5th` = p050,
            `25th` = p250,
            `Median` = p500,
            `75th` = p750,
            `95th` = p950,
            `Max.` = max)

# unadjusted model only (don't run this if I want all models)
summary_stats <- summary_stats %>%
  filter(Model == "m1")
summary_stats$Model <- NULL

summary_stats
```
