
```{r setup, include=FALSE}
## Set working directory as project root
library(here)
knitr::opts_knit$set(root.dir = here())
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r, message=FALSE, warning=FALSE}
## Load libraries ----
library(tidyverse)
library(magrittr)
library(sf)
library(cowplot)
library(viridis)
library(RColorBrewer)
library(ggpubr)
library(pander)
library(data.table)
library(ggthemes)
library(knitr)
library(kableExtra)
library(xtable)
```

```{r}
#####----- user input -----#####

# select outcome and main vs. sensitivity
#outcome <- "adrd"
#outcome <- "nonadrd"
#outcome <- "adrd-dual"
outcome <- "nonadrd-dual"
```


```{r}
# set path for saving figures
fig_path <- "results/figures/final/"
```

## Load data

```{r}
# load model results
res <- read_rds(paste0("data/intermediate/", outcome, "_model_results.rds"))
```

```{r}
## Read data ----
#ratios_df_comb <- read_rds(paste0('data/symlinks/scratch/', outcome, '_combined_data.rds'))
ratios_df <- read_rds(paste0('data/symlinks/scratch/', outcome, '_ratios_df.rds'))
county_sf <- read_rds("data/symlinks/scratch/county_sf.rds")
county_sf_zero_b <- read_rds("data/symlinks/scratch/county_sf_zero_b.rds")

res_sf <- county_sf %>% 
  select(county) %>% 
  #right_join(ratios_df_comb) %>%
  right_join(ratios_df) %>%
  right_join(res)

colnames(res_sf)
```

```{r}
county_fips_df <- read_rds("data/symlinks/scratch/county_fips_df.rds")
state_sf <- read_sf("data/county/cb_2015_us_state/cb_2015_us_state_20m.shp")
state_sf %<>% 
  left_join(
    county_sf %>% 
      left_join(county_fips_df) %>% 
      st_drop_geometry() %>% 
      distinct(STATEFP, s_idx)
  ) %>% 
  filter(!is.na(s_idx))
```

```{r}
# change projection to Albers Equal Area Conic (good for maps of US)

res_sf <- st_transform(res_sf, 
                           crs = st_crs("+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=37.5
                                        +lon_0=-96 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs"))
# state_sf <- st_transform(state_sf, 
#                            crs = st_crs("+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=37.5
#                                         +lon_0=-96 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs"))
county_sf <- st_transform(county_sf,
                                 crs = st_crs("+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=37.5
                                        +lon_0=-96 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs"))
# county_sf_zero_b <- st_transform(county_sf_zero_b,
#                                  crs = st_crs("+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=37.5
#                                         +lon_0=-96 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs"))
```

```{r}
# race labels for plotting
race_labels <- c(
  `1` = "White",
  `2` = "Black"
)
```

## Pre-modeling visualizations of observed and expected

## Model results

### Stage 2 raw vs. smoothed lambdas

```{r}
# set up data

# gather raw observed/expected and lambdas
stage2_total_risk_df <- res_sf |>
  mutate(y_stage2 = log(observed/expected)) |>
  select(county, geometry, race,
         y_stage2, log_lambda_stage2) |>
  # gather raw and modeled lambdas
  gather(key = "raw_vs_model", value = "estimate", y_stage2, log_lambda_stage2) %>%
  # separate category for each model
  mutate(raw_vs_model = ifelse(raw_vs_model == "log_lambda_stage2", "model", "raw")) %>%
  distinct()

# set levels for plotting
stage2_total_risk_df$raw_vs_model <- factor(stage2_total_risk_df$raw_vs_model,
                                       levels = c("raw", "model"))

# labels for facets
stage2_total_risk_labels <- c(
  `1` = "White",
  `2` = "Black",
  raw = "Raw\n observed/expected",
  model = "Smoothed\n observed/expected (\u03BB)",
  "1_specific" = "White-specific\n (\u03C8\u2081)",
  "both_shared_unscaled" = "Unscaled shared\n (\u03A6)",
  "2_specific" = "Black-specific\n (\u03C8\u2082)"
)

# plot
stage2_total_risk_df |>
  #filter(raw_vs_model == "raw" | raw_vs_model == "adrd_m1") |>
  mutate(estimate = ifelse(estimate >= log(3), log(3)-0.001, estimate)) |>
  ggplot() +
  geom_sf(aes(fill = exp(estimate)), lwd = 0.03) + 
  geom_sf(data = county_sf_zero_b, fill = "gray70", lwd = 0.0) + 
  geom_sf(data = state_sf, fill = NA, col = "white", lwd = 0.1) +
  theme_map() + 
  labs(fill = expression('Relative risk')) +
  facet_grid(race ~ raw_vs_model,
             labeller = as_labeller(stage2_total_risk_labels)
             ) +
  theme(legend.title = element_text(size = 12, vjust = 0.8),
        legend.text = element_text(size = 9),
        legend.position = "bottom",
        strip.text = element_text(size = 12),
        strip.background = element_blank(),
        plot.background = element_rect(fill = "white", color = NA),
        text = element_text(family = "Arial")) +
  # this scale is capping at max in previous plot
  scale_fill_viridis(option = "A", 
                     na.value = "gray70",
                     limits = c(0, 3),
                     labels = c("0", "1", "2", "3+"),
                     guide = guide_colorbar(ticks = FALSE,
                                            barwidth = 12, barheight = 0.5))
#ggsave(paste0(fig_path, "adrd_raw_vs_lambda.pdf"), width = 6, height = 4)
#ggsave(paste0(fig_path, paste0(outcome, "_raw_vs_lambda.png")), width = 6, height = 4, dpi = 1000)


#------------------- lambda only -------------------#

plot_title <- ifelse(str_detect(outcome, "nonadrd"), 
                     "Hospitalization without ADRD",
                     "Hospitalization with ADRD")

# plot
lambda_maps <- stage2_total_risk_df |>
  filter(raw_vs_model != "raw") |>
  mutate(estimate = ifelse(estimate <= log(0.3), log(0.3), estimate),
         estimate = ifelse(estimate >= log(3), log(3)-0.001, estimate)) |>
  ggplot() +
  geom_sf(aes(fill = exp(estimate)), lwd = 0.03) + 
  geom_sf(data = county_sf_zero_b, fill = "gray70", lwd = 0.0) + 
  geom_sf(data = state_sf, fill = NA, col = "white", lwd = 0.1) +
  theme_map() + 
  labs(title = plot_title,
       fill = expression('Relative risk ')) +
  facet_grid(~race,
             labeller = as_labeller(race_labels)
             ) +
  theme(plot.title = element_text(face = "bold"),
        legend.title = element_text(size = 10, vjust = 0.8),
        legend.text = element_text(size = 8),
        legend.position = "bottom",
        strip.text = element_text(size = 12),
        strip.background = element_blank(),
        plot.background = element_rect(fill = "white", color = NA),
        text = element_text(family = "Arial")) +
  # this scale is capping at max in previous plot
  scale_fill_viridis(option = "A", 
                     na.value = "gray70",
                     limits = c(0.3, 3),
                     breaks = c(1, 2, 3),
                     labels = c("1", "2", "3+"),
                     guide = guide_colorbar(ticks = FALSE,
                                            barwidth = 20, barheight = 0.5))
# #ggsave(paste0(fig_path, "adrd_raw_vs_lambda.pdf"), width = 6, height = 4)
# ggsave(paste0(fig_path, paste0("lambda_", outcome, ".png")), width = 6, height = 3, dpi = 1000)

# save data for plot, not pdf (combine plots across outcomes in script 11)
write_rds(lambda_maps, file = paste0("results/figures/intermediate/", outcome, 
                                     "_lambda_maps.rds"))
```

```{r}
# get a table looking at significance for lambdas (using 80%)
res_sf %>%
  select(-geometry) %>%
  as.data.frame() %>%
  group_by(race) %>%
  mutate(
    lambda_direction = ifelse(log_lambda_stage2_sig_80, log_lambda_stage2, as.numeric(NA)),
    lambda_direction = ifelse(lambda_direction < 0, "Lambda < 1", "Lambda > 1")
  ) %>%
  count(lambda_direction) %>%
  mutate(pcnt = n / sum(n) * 100)

```


### White-specific, Black-specific, and shared risks (three risk surfaces)

```{r}
# set up data

# gather shared and specific columns
shared_specific_df <- res_sf |>
  select(county, geometry, race, 
         phi, phi_sig_80, phi_sig_95, psi, psi_sig_80, psi_sig_95) |>
  gather(key = "shared_vs_spec", value = "estimate", phi, psi) %>%
  # new sig columns for estimate
  mutate(estimate_sig_80 = ifelse(shared_vs_spec == "psi", psi_sig_80, phi_sig_80),
         estimate_sig_95 = ifelse(shared_vs_spec == "psi", psi_sig_95, phi_sig_95)) |>
  # remove other sig columns for clarity
  select(-c(psi_sig_80, psi_sig_95, phi_sig_80, phi_sig_95)) |>
  # change race for shared rows
  mutate(race = ifelse(shared_vs_spec == "phi", "both", race)) %>%
  distinct() |>
  mutate(parameter = paste0(race, "_", shared_vs_spec)) 

# set levels for plotting
shared_specific_df$parameter <- factor(shared_specific_df$parameter,
                                       levels = c("1_psi", "both_phi", "2_psi"))

# labels for facets
shared_specific_labels <- c(
  #"1_psi" = "White-specific\n (\u03C8\u2081)",
  "1_psi" = "White-specific risk",
  #"both_phi" = "Shared\n (\u03A6)",
  "both_phi" = "Shared risk",
  #"2_psi" = "Black-specific\n (\u03C8\u2082)"
  "2_psi" = "Black-specific risk"
)

# consider middle 80% of posterior, middle 95% of posterior, or all
sig_shared_specific <- 80
#sig_shared_specific <- 95
#sig_shared_specific <- 0

# change to NA if non-significant
shared_specific_df %<>%
  mutate(estimate_80 = ifelse(estimate_sig_80, estimate, NA),
         estimate_95 = ifelse(estimate_sig_95, estimate, NA),
         estimate_0 = estimate,
         estimate_sig = case_when(
           sig_shared_specific == 0 ~ estimate_0,
           sig_shared_specific == 80 ~ estimate_80,
           sig_shared_specific == 95 ~ estimate_95
         ))

sc <- scale_fill_gradient2(high = "#7600bc", mid = "white", low = "#028A0F", na.value = "gray40",
                         #midpoint = 0,
                         midpoint = 1,
                         limits = c(0.7, 1.7),
                         breaks = c(0.7, 0.9, 1.1, 1.3, 1.5, 1.7),
                         # this will overwrite labels!! make sure labels match actual values
                         labels = c("<0.7", "0.9", "1.1", "1.3", "1.5", ">1.7"), 
                         guide = guide_colorbar(ticks = FALSE, barwidth = 20, barheight = 0.5,
                                                title.position = "top", title.hjust = 0.5))

plot_title <- ifelse(str_detect(outcome, "nonadrd"), 
                     "Hospitalization without ADRD",
                     "Hospitalization with ADRD")

shared_specific_plot <- shared_specific_df |>
  # exponentiate and restrict values for plotting
  mutate(exp_estimate = exp(estimate_sig),
         exp_estimate = ifelse(exp_estimate < 0.7, 0.7, exp_estimate),
         exp_estimate = ifelse(exp_estimate > 1.7, 1.7, exp_estimate)
         ) %>%
  #filter(model == "adrd_m1") |>
  ggplot() +
  geom_sf(aes(fill = exp_estimate), lwd = 0) + 
  geom_sf(data = county_sf_zero_b, fill = "gray40", lwd = 0.0) + 
  geom_sf(data = state_sf, fill = NA, col = "black", lwd = 0.1) +
  labs(title = plot_title,
       fill = "Component estimates, relative risk scale") +
  facet_grid(~ parameter,
             labeller = as_labeller(shared_specific_labels)
             ) +
  theme_map() + 
  theme(plot.title = element_text(size = 12, face = "bold"),
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 10),
        legend.position = "bottom",
        legend.justification = "center",
        strip.text = element_text(size = 12),
        strip.background = element_blank(),
        plot.background = element_rect(fill = "white", color = NA),
        text = element_text(family = "Arial")) +
  sc
shared_specific_plot

# ggsave(paste0(fig_path, paste0(outcome, "_shared_vs_specific_", sig_shared_specific, ".png")), width = 7, height = 2.5, dpi = 1000)
# ggsave(paste0(fig_path, paste0(outcome, "_shared_vs_specific_", sig_shared_specific, ".png")), width = 7, height = 2.5, dpi = 1000)

# save data for plot, not pdf (combine plots across outcomes in script 11)
write_rds(shared_specific_plot, file = paste0("results/figures/intermediate/", outcome, 
                                     "_shared_vs_specific_", sig_shared_specific, ".rds"))
```

```{r}
#---------------- same as above but using binary (low/high risk) estimates instead

# # make estimates binary (low vs. high risk)
# shared_specific_df %<>%
#   mutate(estimate_binary = ifelse(estimate > 0, "High risk", "Low risk")) %>%
#   mutate(estimate_binary_80 = ifelse(estimate_sig_80, estimate_binary, NA),
#          estimate_binary_95 = ifelse(estimate_sig_95, estimate_binary, NA),
#          estimate_binary_0 = estimate_binary)
# 
# 
# # plot
# shared_specific_df |>
#   #filter(model == "adrd_m1") |>
#   ggplot() +
#   geom_sf(aes(fill = !!sym(paste0("estimate_binary_", sig_shared_specific))), lwd = 0.03) + 
#   geom_sf(data = county_sf_zero_b, fill = "gray90", lwd = 0.0) + 
#   geom_sf(data = state_sf, fill = NA, col = "black", lwd = 0.1) +
#   labs(fill = "Risk component:") +
#   facet_grid(~ parameter,
#              labeller = as_labeller(shared_specific_labels)
#              ) +
#   theme_map() + 
#   theme(legend.title = element_text(size = 10),
#         legend.text = element_text(size = 10),
#         legend.position = "bottom",
#         strip.text = element_text(size = 12),
#         strip.background = element_blank(),
#         plot.background = element_rect(fill = "white", color = NA)) +
#   scale_fill_manual(values = c("Low risk" = "#006400", 
#                                "High risk" = "#B47EE5"),
#                     na.value = "gray90")
```


### Risk ratios

```{r}
# table of risk ratios < 1, > 1, non-significant

# for 80%
res_sf %>%
  #filter(model == "adrd_m1") %>%
  filter(race == 2) %>% # same risk ratio for white and black rows
  select(-geometry) %>%
  as.data.frame() %>%
  mutate(
    risk_ratio_direction = ifelse(risk_ratio_sig_80, risk_ratio, as.numeric(NA)),
    risk_ratio_direction = ifelse(risk_ratio_direction < 1, "Risk ratio < 1", "Risk ratio > 1")
  ) %>%
  count(risk_ratio_direction) %>%
  mutate(pcnt = n / sum(n) * 100)
```

```{r}
# plot risk ratios

# set up data

# set boundaries for discrete bins
bin_breaks <- c(#0, 0.2, 
                0.6, 0.8, 1, 1.2, 1.4, 1.6, 1.8, 2, 2.2, 2.4, 3.6)

# get bin labels from bin breaks (get mean)
bin_df <- embed(bin_breaks, 2) |> as.data.frame()
bin_means <- rowMeans(bin_df) |> format(nsmall = 1)

# choose 80% or 95% for significance (or show all counties)
sig_rr <- 80
#sig_rr <- 95
#sig_rr <- 0

# new column for risk ratio bins (with significance)
res_sf <- res_sf %>% 
  mutate(risk_ratio_sig = case_when(
    sig_rr == 80 ~ risk_ratio_sig_80,
    sig_rr == 95 ~ risk_ratio_sig_95,
    sig_rr == 0 ~ TRUE
    ),
    risk_ratio_sig_only = ifelse(risk_ratio_sig, risk_ratio, as.numeric(NA)),
    risk_ratio_bins = cut(risk_ratio_sig_only, 
                          breaks = bin_breaks,
                          labels = bin_means
                          ))

# get title based on outcome
rr_title <- ifelse(str_detect(outcome, "nonadrd"), 
                   "Hospitalization without ADRD",
                   "Hospitalization with ADRD")

risk_ratios <- res_sf %>% 
  #filter(model == "adrd_m1") |>
  select(county, geometry, risk_ratio_bins) %>%
  distinct() %>%
  ggplot() +
  geom_sf(aes(fill = risk_ratio_bins), lwd = 0.03) + 
  geom_sf(data = county_sf_zero_b, fill = "gray40", lwd = 0.0) + 
  geom_sf(data = state_sf, fill = NA, col = "black", lwd = 0.2) +
  labs(fill = expression('Risk Ratio \n(Black/White)'),
       #fill = expression('Risk Ratio (' *lambda[' 2ij']*'/'*lambda[' 1ij']*', Black/White)'),
       title = rr_title) +
  theme_map() +
  theme(legend.position = "right", 
        #legend.justification = "right", 
        #legend.direction = "vertical",
        legend.title = element_text(size = 12),
        legend.text = element_text(size = 10),
        strip.background = element_blank(),
        plot.background = element_rect(fill = "white", color = NA),
        plot.title = element_text(hjust = 0.5, size = 14, face = "plain")) +
  scale_fill_manual(
    values = c(#"#08306b",
               #"#313695",
               #"#2171b5",
               "#74add1",
               "#abd9e9",
               "#fee6ce",
               "#fdd0a2", 
               "#fdae6b", 
               "#fd8d3c", 
               "#f16913",
               "#d94801",
               "#a63603", 
               "#7f2704"),
    na.value = "gray40",
    drop = FALSE,
    breaks = levels(unique(res_sf$risk_ratio_bins))#,
    #na.translate = F      # makes NA white
  ) +
  guides(fill = guide_legend(
    title.position = "top",
    #nrow = 1,
    label.position = "right",
    keywidth = grid::unit(.5, "lines"),
    keyheight = grid::unit(1, "lines"),
    label.hjust = 0))
risk_ratios

# save data for plot, not pdf (combine plots across outcomes in script 11)
write_rds(risk_ratios, file = paste0("results/figures/intermediate/", outcome, 
                                     "_risk_ratio_maps_", sig_rr, ".rds"))
```

## Look at distributions of post-modeling variables across counties

```{r}
# function to get summary statistics
summarize_column <- function(df, 
                             column_name, 
                             param_name, 
                             exp_transform = FALSE) {
  result <- df %>%
    st_drop_geometry() %>% 
    group_by(race) %>%
    summarize(
      min = ifelse(exp_transform,
                   min(exp({{ column_name }}), na.rm = TRUE),
                   min({{ column_name }}, na.rm = TRUE)),
      p050 = ifelse(exp_transform,
                    stats::quantile(exp({{ column_name }}), .05, na.rm = TRUE),
                    stats::quantile({{ column_name }}, .05, na.rm = TRUE)),
      p250 = ifelse(exp_transform,
                    stats::quantile(exp({{ column_name }}), .250, na.rm = TRUE),
                    stats::quantile({{ column_name }}, .250, na.rm = TRUE)),
      p500 = ifelse(exp_transform,
                    stats::median(exp({{ column_name }}), na.rm = TRUE),
                    stats::median({{ column_name }}, na.rm = TRUE)),
      p750 = ifelse(exp_transform,
                    stats::quantile(exp({{ column_name }}), .750, na.rm = TRUE),
                    stats::quantile({{ column_name }}, .750, na.rm = TRUE)),
      p950 = ifelse(exp_transform,
                    stats::quantile(exp({{ column_name }}), .95, na.rm = TRUE),
                    stats::quantile({{ column_name }}, .95, na.rm = TRUE)),
      max = ifelse(exp_transform,
                   max(exp({{ column_name }}), na.rm = TRUE),
                   max({{ column_name }}, na.rm = TRUE))
    ) %>%
    mutate(param = param_name,
           min = round(min, 2),
           p050 = round(p050, 2),
           p250 = round(p250, 2),
           p500 = round(p500, 2),
           p750 = round(p750, 2),
           p950 = round(p950, 2),
           max = round(max, 2)) %>%
    ungroup()
  return(result)
}


# apply function to get summary stats table
# note: I don't think the first two can come off of FASSE because they show small counts
summary_stats <- rbind(
  # summarize_column(adrd_res_sf, 
  #                  column_name = person_years,
  #                  param_name = "person years"),
  # summarize_column(adrd_res_sf, 
  #                  column_name = observed,
  #                  param_name = "observed"),
  # summarize_column(df = res_sf,
  #                  column_name = y_stage2,
  #                  param_name = "Raw observed/expected",
  #                  exp_transform = TRUE),
  # summarize_column(df = adrd_res_sf, 
  #                  column_name = log_lambda_stage1, 
  #                  param_name = "Standardized risk (lambda) stage 1", 
  #                  exp_transform = TRUE),
  summarize_column(df = res_sf, 
                   column_name = log_lambda_stage2, 
                   param_name = "Relative risk ($\\lambda$)", 
                   exp_transform = TRUE),
  summarize_column(df = res_sf, 
                   column_name = phi, 
                   param_name = "Shared risk ($\\phi_{ij}$)"),
  summarize_column(df = res_sf, 
                   column_name = psi, 
                   param_name = "Race-specific risk ($\\psi_{dij}$)"),
  summarize_column(df = res_sf, 
                   column_name = risk_ratio, 
                   param_name = "Risk ratio ($\\lambda_{2ij}/\\lambda_{1ij}$)")
  )

# set order of parameters
summary_stats$param <- factor(summary_stats$param,
                              levels = c("Raw observed/expected",
                                         "Relative risk ($\\lambda$)", 
                                         "Shared risk ($\\phi_{ij}$)",
                                         "Race-specific risk ($\\psi_{dij}$)", 
                                         "Risk ratio ($\\lambda_{2ij}/\\lambda_{1ij}$)"))


# make certain parameters a single row (same for both races) and arrange
summary_stats %<>%
  filter(!(param %in% c("Shared risk ($\\phi_{ij}$)", 
                                    "Relative risk (lambda) stage 1",
                                    "Risk ratio ($\\lambda_{2ij}/\\lambda_{1ij}$)") 
           & race == 2)) %>%
  mutate(race = ifelse(param %in% c("Shared risk ($\\phi_{ij}$)", 
                                    "Relative risk (lambda) stage 1",
                                    "Risk ratio ($\\lambda_{2ij}/\\lambda_{1ij}$)"),
                       "--", race)#,
         #model = str_remove(model, "adrd_")
         ) %>%
  #arrange(param, race, model)
  arrange(param, race)

# change race and model values
summary_stats %<>%
  mutate(race = ifelse(race == 1, "White", race)) %>%
  mutate(race = ifelse(race == 2, "Black", race)) %>%
  # mutate(model = ifelse(model == "adrd_m1", "Unadjusted", model)) %>%
  # mutate(model = ifelse(model == "adrd_m2", "Adjusted for HPIR", model)) %>%
  # mutate(model = ifelse(model == "adrd_m3", "Adjusted for $PM_{2.5}$", model)) %>%
  select(c(param, everything()))

# display without scientific notation
summary_stats[] <- lapply(summary_stats, function(x) if(is.numeric(x)) format(x, scientific = FALSE) else x)

# rename columns
summary_stats <- summary_stats |>
  rename(Parameter = param,
         Race = race,
         `Min.` = min,
         `5th` = p050,
         `25th` = p250,
         `Median` = p500,
         `75th` = p750,
         `95th` = p950,
         `Max.` = max)

# unadjusted model only (don't run this if I want all models)
# summary_stats <- summary_stats %>%
#   filter(Model == "m1")
#summary_stats$Model <- NULL

View(summary_stats)
```

## Standard deviation in posterior samples

```{r}
sd_lambda_stage1 <- read_rds(paste0("data/intermediate/", outcome, "_lambda_stage1_sd.rds"))
sd_phi <- read_rds(paste0("data/intermediate/", outcome, "_phi_sd.rds"))
sd_lambda_white <- read_rds(paste0("data/intermediate/", outcome, "_lambda_white_sd.rds"))
sd_lambda_black <- read_rds(paste0("data/intermediate/", outcome, "_lambda_black_sd.rds"))
sd_psi_white <- read_rds(paste0("data/intermediate/", outcome, "_psi_white_sd.rds"))
sd_psi_black <- read_rds(paste0("data/intermediate/", outcome, "_psi_black_sd.rds"))

# bind SDs with county sf
check_sds <- cbind(county_sf, sd_lambda_stage1, sd_phi, sd_lambda_white, sd_lambda_black,
                    sd_psi_white, sd_psi_black)

# gather SD columns
check_sds %<>%
  select(county, sd_lambda_stage1, sd_phi, sd_lambda_white, sd_lambda_black,
                    sd_psi_white, sd_psi_black) %>%
  gather(key = "parameter", value = "sd", -c(county, geometry))

check_sds$parameter <- factor(check_sds$parameter,
                               levels = c("sd_lambda_stage1", 
                                          "sd_lambda_white", 
                                          "sd_lambda_black",
                                          "sd_phi", 
                                          "sd_psi_white", 
                                          "sd_psi_black"))

# labels for plotting
param_labels <- c(
  sd_lambda_stage1 = "\u03BB\u1D62\u2C7C (Overall)",
  sd_lambda_white = "\u03BB\u2081\u1D62\u2C7C (White)",
  sd_lambda_black = "\u03BB\u2082\u1D62\u2C7C (Black)",
  sd_phi = "\u03A6\u1D62\u2C7C (Shared)",
  sd_psi_white = "\u03C8\u2081\u1D62\u2C7C (White-specific)",
  sd_psi_black = "\u03C8\u2082\u1D62\u2C7C (Black-specific)"
)

plot_title <- ifelse(str_detect(outcome, "nonadrd"), 
                     "Hospitalization without ADRD",
                     "Hospitalization with ADRD")

# plot SD
sd_maps <- check_sds %>%
  mutate(sd = ifelse(sd > 0.4, 0.4, sd)) %>%
  ggplot() +
  geom_sf(aes(fill = sd), lwd = 0.0) +
  geom_sf(data = county_sf_zero_b, fill = "gray50", lwd = 0.0) +
  geom_sf(data = state_sf, fill = NA, lwd = 0.3, col = "black") +
  labs(title = plot_title,
       fill = "Posterior standard deviation   ") +
  scale_fill_gradient2(high = "red3", low = "white", na.value = "gray50",
                       limits = c(0, 0.4),
                       guide = guide_colorbar(ticks = FALSE,
                                              barwidth = 12, barheight = 1)) +
  #scale_fill_viridis(option = "G", direction = -1) +
  facet_wrap(~parameter, nrow = 2,
             labeller = as_labeller(param_labels)) +
  theme_map() +
  theme(plot.title = element_text(size = 14, face = "bold"),
        legend.position = "bottom",
        strip.background = element_blank(),
        strip.text = element_text(size = 14),
        legend.title = element_text(size = 12),
        legend.text = element_text(size = 10),
        plot.background = element_rect(fill = "white", color = NA),
        text = element_text(family = "Arial"))

# ggsave(file = paste0(fig_path, paste0("posterior_sd_", outcome, ".png")), width = 8, height = 5, dpi = 1000)

# save data for plot, not pdf (combine plots across outcomes in script 11)
write_rds(sd_maps, file = paste0("results/figures/intermediate/", outcome, 
                                     "_posterior_sd.rds"))
```
