
```{r setup, include=FALSE}
## Set working directory as project root
library(here)
knitr::opts_knit$set(root.dir = here())
```

```{r, message=FALSE, warning=FALSE}
## Load libraries ----
library(tidyverse)
library(sf)
library(magrittr)
library(viridis)
library(cowplot)
library(ggpubr)
library(knitr)
library(kableExtra)
library(xtable)
```

```{r}
# set path for saving figures
fig_path <- "results/figures/final/"
```


## Load data for adrd and hosp

```{r}
# choose which model to use
model <- "m1"
#model <- "m2"
#model <- "m3"

## Read data ----
county_sf <- read_rds("data/symlinks/scratch/county_sf.rds")
adrd_res <- read_rds("data/intermediate/adrd_model_results.rds")
hosp_res <- read_rds("data/intermediate/hosp_model_results.rds")

adrd_res <- adrd_res[[paste0("adrd_", model)]]
hosp_res <- hosp_res[[paste0("hosp_", model)]]

## Read non-modeled data ----
adrd_ratios_df_comb <- read_rds('data/symlinks/scratch/adrd_combined_data.rds')
hosp_ratios_df_comb <- read_rds('data/symlinks/scratch/hosp_combined_data.rds')

adrd_ratios_df <- read_rds('data/symlinks/scratch/adrd_ratios_df.rds')
hosp_ratios_df <- read_rds('data/symlinks/scratch/hosp_ratios_df.rds')

adrd_res_df <- adrd_res %>%
  right_join(adrd_ratios_df_comb) %>%
  right_join(adrd_ratios_df)
hosp_res_df <- hosp_res %>%
  right_join(hosp_ratios_df_comb) %>%
  right_join(hosp_ratios_df)


# make a new column for log(observed/expected) separated by race
adrd_res_df %<>%
  mutate(y = log(observed/expected_stage2))
hosp_res_df %<>%
  mutate(y = log(observed/expected_stage2))
# make a new column for log(observed/expected) combined race
adrd_res_df %<>%
  mutate(y_stage1_total = log(observed_total/expected_stage1_total))
hosp_res_df %<>%
  mutate(y_stage1_total = log(observed_total/expected_stage1_total))

# join adrd and hosp
pos_med <- merge(adrd_res_df, hosp_res_df, all = TRUE, 
                 by = c("county", "race", "black", "c_idx", "s_idx", "person_years", 
                        "fipschar", "fips_st", "house_price_income_ratio", "pm25",
                        "med_house_income", "person_years_total"),
                 suffixes = c("_adrd", "_hosp"))

pos_med_sf <- county_sf %>% 
  select(county) %>% 
  right_join(pos_med)

colnames(pos_med_sf)

# load state data
county_fips_df <- read_rds("data/symlinks/scratch/county_fips_df.rds")
state_sf <- read_sf("data/county/cb_2015_us_state/cb_2015_us_state_20m.shp")
state_sf %<>% 
  left_join(
    county_sf %>% 
      left_join(county_fips_df) %>% 
      st_drop_geometry() %>% 
      distinct(STATEFP, s_idx)
  ) %>% 
  filter(!is.na(s_idx))

# load counties with zero Black person-years
county_sf_zero_b <- read_rds("data/symlinks/scratch/county_sf_zero_b.rds")
```

```{r}
# change projection to Albers Equal Area Conic (good for maps of US)
pos_med_sf <- st_transform(pos_med_sf, 
                           crs = st_crs("+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=37.5
                                        +lon_0=-96 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs"))
state_sf <- st_transform(state_sf, 
                           crs = st_crs("+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=37.5
                                        +lon_0=-96 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs"))

county_sf <- st_transform(county_sf, 
                           crs = st_crs("+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=37.5
                                        +lon_0=-96 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs"))
```

```{r}
# race labels for plotting
race_labels <- c(
  `1` = "White",
  `2` = "Black"
)
```

```{r}
# make new columns for rate of hospitalization (observed/person-years)
# and expected rate of hospitalization (expected/person-years)
pos_med_sf %<>% 
  mutate(rate_obs_adrd = observed_adrd/person_years,
         rate_exp_adrd = expected_stage2_adrd/person_years,
         rate_obs_hosp = observed_hosp/person_years,
         rate_exp_hosp = expected_stage2_hosp/person_years)
```


## Pre-modeling

```{r}
# person-years, observed counts, raw observed/expected ratios (all before modeling)

# I want to facet by parameter, so I need to gather the columns of interest
param_dist <- pos_med_sf |>
  st_drop_geometry() |>
  mutate(exp_y_adrd = exp(y_adrd),
         exp_y_hosp = exp(y_hosp)#,
         # exp_pos_med_y_adrd = exp(pos_med_y_adrd),
         # exp_pos_med_y_hosp = exp(pos_med_y_hosp)
         ) |>
  gather(key = "parameter", value = "value", 
         c(person_years, 
           observed_adrd,
           observed_hosp,
           exp_y_adrd,
           exp_y_hosp#,
           #exp_pos_med_y_adrd,
           #exp_pos_med_y_hosp
           )) |>
  select(county, race, parameter, value)

# look at NA values
# NA values are for ADRD rate the 71 
param_dist |>
  group_by(parameter) |>
  summarise(num_NA = sum(is.na(value)))
# these are just the 71 counties with 0 black person-years, so I can ignore them

# I want to plot on log scale, so change any 0s to 0.00000001
param_dist %<>%
  mutate(value = ifelse(value == 0, 0.00000001, value))

# set order of plots
param_dist$parameter <- factor(param_dist$parameter,
                               levels = c("person_years", "observed_adrd", "observed_hosp", 
                                          "exp_y_adrd", "exp_y_hosp"))

# plot
param_dist |>
  filter(!is.na(value)) |>
  mutate(race = factor(ifelse(race == 1, "White", "Black"),
                       levels = c("White", "Black"))) %>% 
  ggplot() +
  geom_density(aes(value, col = as.factor(race))) +
  labs(x = "",
       y = "Density",
       col = "") +
  scale_x_log10(labels = scales::comma) +
  facet_wrap(~parameter, scales = "free", 
             nrow = 3,
             labeller = as_labeller(c(person_years = "Person years",
                                      observed_adrd = "Observed hosp. w/ ADRD",
                                      observed_hosp = "Observed hosp. w/o ADRD",
                                      exp_y_adrd = "Raw observed/expected hosp. w/ ADRD",
                                      exp_y_hosp = "Raw observed/expected hosp. w/o ADRD"))) +
  theme_bw() +
  theme(strip.background = element_rect(fill = "white"),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        panel.grid = element_blank(),
        legend.position = "bottom")

# plotting x-axis on log scale!!

```


```{r}
# look at white vs. black person years
pos_med_sf %>%
  st_drop_geometry() %>%
  group_by(race) %>%
  summarise(q25_py = quantile(person_years, 0.25))
```

```{r}
# another plot of person-years
pos_med_sf %>%
  mutate(race = factor(ifelse(race == 1, "White", "Black"),
                       levels = c("White", "Black"))) %>% 
  ggplot() +
  geom_density(aes(person_years, col = as.factor(race))) +
  scale_x_log10(labels = scales::comma) +
  labs(x = "Person-years contributed in each county", 
       y = "Density",
       color = "") +
  theme_light()

```

```{r}
# total black vs. white person-years
adrd_res_df %>%
  group_by(race) %>%
  summarise(total_py = sum(person_years))
```


```{r}
# counties with zero Black person-years
pos_med_sf %>%
  ggplot() +
  geom_sf(fill = "white", lwd = 0.1) +
  geom_sf(data = county_sf_zero_b, fill = "#FF7F50") +
  geom_sf(data = state_sf, fill = NA, lwd = 0.3) +
  theme_map() +
  theme(legend.position = "none")
```


```{r}
# counties with < 10 observed ADRD hosp
pos_med_sf %>%
  mutate(obs0 = ifelse(person_years < 100, 1, 0)) %>%
  filter(race == 2) %>%
  ggplot() +
  geom_sf(aes(fill = as.factor(obs0)), lwd = 0.1) +
  geom_sf(data = county_sf_zero_b, fill = "skyblue3", lwd = 0.1) +
  geom_sf(data = state_sf, fill = NA, lwd = 0.3) +
  scale_fill_manual(values = c("1" = "skyblue3", "0" = "white")) +
  theme_map() +
  theme(legend.position = "none")
```

```{r}
# plot # of neighbors

# load # of border for each county (from adjacency matrix)
n_borders <- read_rds("data/symlinks/scratch/county_adj_sparse_list.rds")$D_sparse

# bind with county sf
check_adj <- cbind(county_sf, n_borders)


library(RColorBrewer)

# plot number of borders
check_adj %>%
  ggplot() +
  geom_sf(aes(fill = as.factor(n_borders)), lwd = 0.1) +
  #geom_sf(aes(fill = n_borders), lwd = 0.1) +
  geom_sf(data = county_sf_zero_b, fill = "gray50", lwd = 0.1) +
  geom_sf(data = state_sf, fill = NA, lwd = 0.3, col = "black") +
  labs(fill = "Number of \nneighbors") +
  #scale_fill_gradient2(high = "darkgreen", low = "white", na.value = "gray50") +
  scale_fill_viridis_d(option = "G", direction = -1) +
  theme_map() +
  theme(legend.position = "right",
        legend.title = element_text(size = 10))

```



```{r}
# what % of all hosp have ADRD code?

# get a new column for observed ADRD / observed hosp %
pos_med_sf %<>%
  mutate(adrd_pct = (observed_adrd / (observed_adrd + observed_hosp)) * 100)

```

```{r}
# get weighted avg. % by race
# what % of all hospitalizations had ADRD code?

# get total ADRD hosp by race
# and total other hosp by race

pos_med %>%
  group_by(race) %>%
  summarise(total_adrd = sum(observed_adrd),
            total_hosp = sum(observed_hosp)) %>%
  mutate(adrd_pct = total_adrd / (total_adrd + total_hosp))
```


```{r}
# # look at distribution of this variable for white vs. black at county-level
# pos_med_sf |>
#   mutate(race = factor(ifelse(race == 1, "White", "Black"),
#                        levels = c("White", "Black"))) %>% 
#   ggplot() +
#   geom_density(aes(adrd_pct, col = as.factor(race))) +
#   labs(x = "% of all hospitalizations with ADRD code",
#        y = "Density",
#        col = "") +
#   theme_bw() +
#   theme(axis.text.y = element_blank(),
#         axis.ticks.y = element_blank(),
#         panel.grid = element_blank())
```


```{r}
# now map this variable!

pos_med_sf |>
  # cap at 30%
  #mutate(adrd_pct = ifelse(adrd_pct > 30, 30, adrd_pct)) |>
  # exclude counties with < 500 person-years
  mutate(adrd_pct = ifelse(person_years < 700, NA, adrd_pct)) |>
  ggplot() +
  geom_sf(aes(fill = adrd_pct), lwd = 0.1) +
  geom_sf(data = state_sf, fill = NA, col = "black", lwd = 0.1) +
  labs(fill = "% of hosp. w/ ADRD code") +
  scale_fill_viridis(option = "D") + 
  facet_grid(~race, labeller = as_labeller(race_labels)) +
  theme_map() +
  theme(legend.position = "bottom",
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 8)
        )
```


```{r}
# try to understand if this makes sense
pct_df <- pos_med_sf %>%
  st_drop_geometry() %>%
  select(county, race, observed_adrd, observed_hosp, adrd_pct)



# look at Freemont, WY (very high % with lots of people)
a = pos_med_sf %>%
  filter(county == 56013)

# Aroostook, ME
b = pos_med_sf %>%
  filter(county == 23003)
```



## Model results

```{r}
# compare distributions of risk ratios
pos_med_sf %>%
  st_drop_geometry() %>%
  filter(race == 1) %>% # choose one race for risk ratios
  gather(key = "outcome", "risk_ratio", risk_ratio_adrd, risk_ratio_hosp) %>%
  mutate(outcome = ifelse(outcome == "risk_ratio_adrd", 
                          "ADRD", "All other hosp.")) %>%
  ggplot() +
  geom_density(aes(x = risk_ratio, col = outcome)) +
  geom_vline(xintercept = 1, lty = 2) +
  labs(x = "Risk ratio",
       y = "Density",
       col = "Outcome") +
  theme_bw() +
  theme(panel.grid = element_blank())
```

```{r}
# get ratios of risk ratios and map

pos_med_sf %<>%
  mutate(ratio_of_risk_ratios = risk_ratio_adrd / risk_ratio_hosp)

sc <- scale_fill_gradient2(high = "orange", mid = "white", low = "blue", na.value = "gray50",
                         midpoint = 1)

pos_med_sf |>
  #mutate(adrd_pct = ifelse(adrd_pct > 20, 20, adrd_pct)) |>
  filter(race == 1) %>%
  ggplot() +
  geom_sf(aes(fill = ratio_of_risk_ratios), lwd = 0.1) +
  geom_sf(data = state_sf, fill = NA, lwd = 0.1) +
  labs(fill = "Ratio of risk ratios \n(ADRD/other hosp)") +
  theme_map() +
  theme(legend.position = "bottom",
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 8)
        ) +
  sc

# how do we decide which ones are statistically significantly different from 1?

# wait, something is weird here.

# imagine a county where black risk is higher for ADRD and all-cause hosp
# if the disparity is stronger for ADRD, ratio of ratios will be > 1
# if the disparity is stronger for all-cause hosp, ratio of ratios will be < 1
# ratio of ratios > 1 indicates that "racism" for black people is worse for ADRD

# now imagine a county where white risk is higher for ADRD and all-cause hosp
# if the disparity is stronger for ADRD (i.e. risk ratio is smaller, farther from 1), then ratio of ratios will be < 1
# if the disparity is stronger for all-cause hosp, ratio of ratios will be > 1
# ratio of ratios > 1 indicates that "racism" for white people is worse for all-cause

# example

# county A:
# RR for ADRD = 1.1
# RR for all-cause = 2.2
# ratio of ratios = 0.5
# disparities are stronger for all-cause hosp and worse for Black people

# county B:
# RR for ADRD = 0.4
# RR for all-cause = 0.8
# ratio of ratios = 0.5
# disparities are stronger for ADRD and worse for white people

# county C:
# RR for ADRD = 0.6
# RR for all-cause = 1.2
# ratio of ratios = 0.5
# disparities are in different directions (ADRD worse for white, all-cause hosp worse for black)

# ratio of risk ratios = 0.5 just tells us that RR is greater for ADRD than for all-cause hosp, but we don't know if this means the risk ratio for ADRD is closer to or farther from the null than the risk ratio for all-cause hosp
# we really want to know which one is farther from the null, not which one is strictly greater


```

```{r}
# okay, thinking about alternatives

# what about lambdas for each race?

# pos_med_sf %<>%
#   mutate(ratio_of_pos_med_y = pos_med_y_adrd / pos_med_y_hosp)
# 
# pos_med_sf |>
#   mutate(ratio_of_pos_med_y = ifelse(ratio_of_pos_med_y < -5, -5, ratio_of_pos_med_y),
#          ratio_of_pos_med_y = ifelse(ratio_of_pos_med_y > 5, 5, ratio_of_pos_med_y)) |>
#   ggplot() +
#   geom_sf(aes(fill = ratio_of_pos_med_y), lwd = 0.1) +
#   geom_sf(data = state_sf, fill = NA, col = "black", lwd = 0.1) +
#   labs(fill = "lambda ADRD/lambda hosp") +
#   facet_grid(~race, labeller = as_labeller(race_labels)) +
#   theme_map() +
#   theme(legend.position = "bottom",
#         legend.title = element_text(size = 10),
#         legend.text = element_text(size = 8)
#         ) +
#   sc

```

```{r}
# in counties where black people were significantly worse off (RR > 1) for both ADRD and hosp, which one was stronger?
# plot ADRD RR / hosp RR

pos_med_sf |>
  #mutate(adrd_pct = ifelse(adrd_pct > 20, 20, adrd_pct)) |>
  filter(race == 1) %>%
  mutate(ratio_of_risk_ratios = ifelse(
    risk_ratio_adrd > 1 & risk_ratio_sig_adrd & risk_ratio_hosp > 1 & risk_ratio_sig_hosp,
    ratio_of_risk_ratios, NA)) %>%
  ggplot() +
  geom_sf(aes(fill = ratio_of_risk_ratios), lwd = 0.1) +
  geom_sf(data = state_sf, fill = NA, col = "white", lwd = 0.1) +
  labs(fill = "Ratio of risk ratios \n(ADRD/other hosp)") +
  theme_map() +
  theme(legend.position = "bottom",
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 8)
        ) +
  sc

```

```{r}
# plot with three categories

# new column to compare RRs
pos_med_sf %<>%
  mutate(RR_comp = ifelse(risk_ratio_adrd > 1 & risk_ratio_hosp > 1, 
                          "black_worse_both", NA)) %>%
  mutate(RR_comp = ifelse(risk_ratio_adrd < 1 & risk_ratio_hosp < 1, 
                          "white_worse_both", RR_comp)) %>%
  mutate(RR_comp = ifelse(risk_ratio_adrd < 1 & risk_ratio_hosp > 1 |
                            risk_ratio_adrd > 1 & risk_ratio_hosp < 1, NA, RR_comp))

png(file = paste0(fig_path, "rr_hosp_vs_adrd.png"), width = 600, height = 400)

pos_med_sf |>
  filter(race == 1) %>%
  ggplot() +
  geom_sf(aes(fill = RR_comp), lwd = 0.1) +
  geom_sf(data = county_sf_zero_b, fill = "white", lwd = 0.0) + 
  geom_sf(data = state_sf, fill = NA, lwd = 0.1, col = "black") +
  labs(fill = "") +
  scale_fill_manual(values = c("black_worse_both" = "#fd8d3c", 
                               "white_worse_both" = "#2171b5"),
                    labels = c("black_worse_both" = "Black risk > White risk for both outcomes", 
                               "white_worse_both" = "White risk > Black risk for both outcomes"),
                    na.value = "gray90") +
  theme_map() +
  theme(legend.position = "bottom") +
  guides(fill = guide_legend(ncol = 1, byrow = TRUE))

dev.off()
```

```{r}
# get risk ratios for ADRD and hosp in the same plot
adrd_risk_ratios_map <- read_rds("results/figures/intermediate/adrd_risk_ratios_map_1m.rds")
hosp_risk_ratios_map <- read_rds("results/figures/intermediate/hosp_risk_ratios_map_1m.rds")

png(file = paste0(fig_path, "risk_ratios_1m.png"), width = 1300, height = 500)

ggarrange(adrd_risk_ratios_map, hosp_risk_ratios_map,
          common.legend = TRUE, 
          legend = "bottom")

dev.off()
```

```{r}
# same but for all three models
adrd_risk_ratios_map <- read_rds("results/figures/intermediate/adrd_risk_ratios_map_3m.rds")
hosp_risk_ratios_map <- read_rds("results/figures/intermediate/hosp_risk_ratios_map_3m.rds")

png(file = paste0(fig_path, "risk_ratios_3m.png"), width = 1300, height = 500)

ggarrange(adrd_risk_ratios_map, hosp_risk_ratios_map,
          nrow = 2,
          common.legend = TRUE, 
          legend = "bottom")

dev.off()
```

# Hospitalization rates table

```{r}
# get ADRD table
adrd_exp_rates_1 <- read_rds(paste0("results/tables/intermediate/adrd_expected_rates_race-specific.rds"))
adrd_exp_rates_2 <- read_rds(paste0("results/tables/intermediate/adrd_expected_rates_overall.rds"))
adrd_exp_rates <- left_join(adrd_exp_rates_1, adrd_exp_rates_2) |>
  rename("ADRD rate (White)" = `Rate (White)`,
         "ADRD rate (Black)" = `Rate (Black)`,
         "ADRD rate (overall)" = `Rate (overall)`)

# get hosp table
hosp_exp_rates_1 <- read_rds(paste0("results/tables/intermediate/hosp_expected_rates_race-specific.rds"))
hosp_exp_rates_2 <- read_rds(paste0("results/tables/intermediate/hosp_expected_rates_overall.rds"))
hosp_exp_rates <- left_join(hosp_exp_rates_1, hosp_exp_rates_2) |>
  rename("Non-ADRD rate (White)" = `Rate (White)`,
         "Non-ADRD rate (Black)" = `Rate (Black)`,
         "Non-ADRD rate (overall)" = `Rate (overall)`)

# join ADRD and hosp
exp_rates_tab <- left_join(adrd_exp_rates, hosp_exp_rates)

# change col names (can have duplicates)
names(exp_rates_tab) <- c("Sex", "Age group", 
                          "White", "Black", "Overall",
                          "White", "Black", "Overall")

# format in kable with header over cols
exp_rates_tab_latex <- kable(exp_rates_tab, "latex", 
      booktabs = TRUE) %>%
  add_header_above(c(" " = 2, "ADRD rate" = 3, "Non-ADRD rate" = 3))

writeLines(exp_rates_tab_latex, "results/tables/final/national_rates.tex")
# note: remove \addlinespace from the resulting table
# also need to add begin table and end table and centering

```


# Covariate effects (beta) table

```{r}
# read adrd + hosp tables
adrd_beta <- read_rds(paste0("results/tables/intermediate/adrd_beta_df.rds"))
hosp_beta <- read_rds(paste0("results/tables/intermediate/hosp_beta_df.rds"))

names(adrd_beta)[2] <- paste0(names(adrd_beta)[2], " ADRD")
names(hosp_beta)[2] <- paste0(names(hosp_beta)[2], " Non-ADRD")

# join
beta_tab <- left_join(adrd_beta, hosp_beta)

# change col names (can have duplicates)
names(beta_tab) <- c("Parameter", "ADRD", "Non-ADRD")

# format in kable with header over cols
beta_tab_latex <- kable(beta_tab, "latex", booktabs = TRUE, escape = FALSE) %>%
  add_header_above(c(" " = 1, "Estimate (95% CI)" = 2))
# don't escape % in header with kable

writeLines(beta_tab_latex, "results/tables/final/betas.tex")
# note: remove \addlinespace from the resulting table
# also need to add begin table and end table and centering

```

# Empirical variance table (adrd + hosp)

```{r}
# load list with ADRD all results and bind into df
adrd_ev <- read_rds(paste0("results/tables/intermediate/adrd_empirical_variance.rds"))
adrd_ev <- bind_rows(adrd_ev, .id = "model")

# spread columns by model
adrd_ev <- adrd_ev |>
  spread(key = model, value = Estimate) |>
  arrange(Parameter) #|>
  # rename(`Unadjusted` = adrd_m1,
  #        `Adjusted for PIR` = adrd_m2,
  #        `Adjusted for PM2.5` = adrd_m3)

# load list with hosp all results and bind into df
hosp_ev <- read_rds(paste0("results/tables/intermediate/hosp_empirical_variance.rds"))
hosp_ev <- bind_rows(hosp_ev, .id = "model")

# spread columns by model
hosp_ev <- hosp_ev |>
  spread(key = model, value = Estimate) |>
  arrange(Parameter) #|>
  # rename(`Unadjusted` = hosp_m1,
  #        `Adjusted for PIR` = hosp_m2,
  #        `Adjusted for PM2.5` = hosp_m3)

# join adrd + hosp
ev <- left_join(adrd_ev, hosp_ev)

# change col names (can have duplicates)
names(ev) <- c("Race", "Parameter", rep(c("Unadjusted", 
                                          "Adjusted for PIR", 
                                          "Adjusted for PM2.5"), times = 2))

# format in kable with header over cols
ev_tab <- kable(ev, "latex", booktabs = TRUE, escape = FALSE) %>%
  add_header_above(c(" " = 2, "ADRD" = 3, "Non-ADRD" = 3))
# don't escape % in header with kable

writeLines(ev_tab, "results/tables/final/empirical_variance.tex")

# print(xtable(ev, type = "latex"),
#       include.rownames = FALSE,
#       file = "results/tables/final/empirical_variance.tex")

```

# Posterior standard deviation map (ADRD + hosp)

```{r}
adrd_sd <- read_rds("results/figures/intermediate/adrd_sd.rds")
hosp_sd <- read_rds("results/figures/intermediate/hosp_sd.rds")

png(file = paste0(fig_path, "posterior_sd.png"), width = 1300, height = 500)

ggarrange(adrd_sd, hosp_sd,
          common.legend = TRUE, 
          legend = "bottom")

dev.off()
```

